### ISSUE TITLE
Windows no more contain "MySQL Connector C 6.1"

### ISSUE THREAD

**Issue by vit1251** [PyMySQL/mysqlclient-python#105]
Building on last MySQL Community does not work. Root cause of this problem MySQL directory _-IC:\Program Files (x86)\MySQL\MySQL Connector C 6.1\include_ no more provided.

Instead this directory I found follow direcotry "C:\Program Files\MySQL\Connector.C++ 1.1"

P.S. Problem occurs on Python 3.5 installing with pip

**Comment by methane** [comment]
dup of #54.
