### ISSUE TITLE
Question: what's the point of `import select` in gevent waiter example?

### ISSUE THREAD

**Issue by rockallite** [PyMySQL/mysqlclient-python#107]
Well, this is not really an issue, but a question instead.

**Q:** What's the point of `import select` in gevent waiter example? I don't see the use of `select` anywhere else in the code.
https://github.com/PyMySQL/mysqlclient-python/blob/master/samples/waiter_gevent.py#L5

**Comment by methane** [comment]
No meaning it can be removed.
BTW, API used by the example (waiter) is experimental and it can be removed in the future release.
Don't use it for your production code.
