### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by kennethreitz** [PyMySQL/mysqlclient-python#119]
Hey there!

We (Python Team at Heroku) are going to be rolling out a change next week, which will effect users of this (wonderful!) library: updating to libmysqlclient 5.7

This PR which fixes this upcoming issue, has been merged, but not yet released.
https://github.com/PyMySQL/mysqlclient-python/pull/109

Is there a chance a quick fix release could be made by then? It'd be much appreciated :)

✨🍰✨

**Comment by methane** [comment]
🍴 released 1.3.8. 🍴
