### ISSUE TITLE
utf8mb4 for windows

### ISSUE THREAD

**Issue by xynon** [PyMySQL/mysqlclient-python#120]
Under Windows the C function [mysql_set_character_set](https://github.com/PyMySQL/mysqlclient-python/blob/master/_mysql.c#L1664) still raises the error "Can't initialize character set" (2019) if you want to set 'utf8mb4'. So it passed as a Python OperationalError. But utf8mb4 can be set by 'SET NAMES utf8mb4'. 

OS: Win10 64bit
Database: 5.5.5-10.1.16-MariaDB
Python Version: 2.7
mysqlclient-python: 1.3.7

It is possible to wrote another exception for that case - in [set_character_set](https://github.com/PyMySQL/mysqlclient-python/blob/master/MySQLdb/connections.py#L338-L344)?

Something like that:
```python
try:
    super(Connection, self).set_character_set(charset)

except AttributeError:
    if self._server_version < (4, 1):
        raise NotSupportedError("server is too old to set charset")
    self.query('SET NAMES %s' % charset)
    self.store_result()

except OperationalError as error:
    if not sys.platform.startswith("win") or error.args[0] != 2019:
        raise
    self.query('SET NAMES %s' % charset)
    self.store_result()
```

MfG Xynon

**Comment by methane** [comment]
What version of mysqlclient do you use?
I think it's because your mysqlclient.lib is too old.

2016/09/29 午後11:26 "xynon" <notifications@github.com>:

**Comment by xynon** [comment]
Where can I find the version of mysqlclient.lib?

**Comment by methane** [comment]
How did you install mysqlclient??

**Comment by xynon** [comment]
The Server is in the bundle of bitnami XAMPP (5.5.5-10.1.16-MariaDB), the MySQL-Client with an Setup for Windows from [dev.mysql.com](http://dev.mysql.com/downloads/installer/)(5.7.15) and the mysqlclient-python from pip(1.3.7)

**Comment by methane** [comment]
You may use binary wheel.
I think Python 2.7 and MySQL Connector/C may be too old.

Could you try this?
https://github.com/PyMySQL/mysqlclient-python/issues/54#issuecomment-244698218

**Comment by methane** [comment]
"SET NAMES %s" is dangerous.  It set only server-side connection encoding.
Encoding mismatch between client and server can cause data broken, or even SQL injection.

When you use 'utf8' in client side, and utf8mb4 on server side, it's safe.
But I won't implement such a dangerous implicit fallback.

**Comment by xynon** [comment]
You are absolutely right. I found the fault on my side.
pip was using a old mysqlclient.lib from **C:\Python27\libs** to build. (VS10 build from **MySQL Connector/C 6.0.2**)
I replaced these with a build from **MySQL Connector/C 6.1.6**. Now **mysql_set_character_set** works correctly and with **mysql_get_character_set_info** got the right values.

By the way it will be great if you take a look for python2.7 wheels. - The most server I see are still using python 2.7.x. 

Anyway, thank you.

**Comment by methane** [comment]
> By the way it will be great if you take a look for a python2.7 wheel. - The most server I see are still using python 2.7.x. 

I'll maint python 2.7 libs as long as it's easy.
In this case, Windows Python 2.7 is based on VC++ 2008 (VC9), the 9 years old compiler.
MySQL Connector/C 6.1.x stop providing vc9 libs. That's why I used Connector/C 6.0 for Python 2.7.

Python 2.7 extension modules depending to external library on Windows is much harder than on Linux,
because many libraries start dropping VC9.
Regardless Python core developers provide bugfix for Python 2.7 until 2020, it doesn't means
everyone can use Python 2.7 + all new features (like utf8mb4 in MySQL).

I'll try building new Connector/C library with VC9 when I have time, but please don't expect it.
I've tired about supporting Python 2 already.

Many library developers paid huge efforts to support both of Python 2 and 3 in many years.
I wonder if more users pay more efforts to move to Python 3...
Moving to Python 3 is much easier than sticking on Python 2and3.

**Comment by xynon** [comment]
I don't know but the mysqlclient.lib is a static library and these I use with the mysqlclient-python interface - so it should be irrelevant whether the lib is compiled with VS10/11/12 or mingw. So long I've the headers and the api interface is the same. Or I'm wrong with this?

You are right if you say that developers paid huge efforts to support both python versions - but many third libraries still not support python3 yet. True, the python3 support has improved over the last years but if you have dependencies to not python3 supported libs then you have a problem to say 'simply move to python 3'.

But I can accept if you don't want support python2 any longer and this is only windows support - I know how to install it without a wheel - so it's ok :)

**Comment by methane** [comment]
> I don't know but the mysqlclient.lib is a static library and these I use with the mysqlclient-python interface - so it should be irrelevant whether the lib is compiled with VS10/11/12 or mingw. So long I've the headers and the api interface is the same. Or I'm wrong with this?

Did you tried?

As long as I've tried, I faced a lot of link errors caused by msvcrt version mismatch.
I can't resolve all of them because I'm not Windows expert. (I use Windows only build windows wheel.  Daily hacking is on Mac and Linux)

If you're expert of Windows development, contribution is welcome!

**Comment by methane** [comment]
> but many third libraries still not support python3 yet.

It was true in last year, but not true in this year.
http://www.infoworld.com/article/3041958/application-development/python-3-gains-a-big-helping-of-library-support.html

**Comment by methane** [comment]
I'm sorry, I haven't read whole your response.
You succeeded to build with VC10 lib in Connector/C 6.1.6, right?
It's good information.  I'll try it.

**Comment by xynon** [comment]
No, I'm truly not an 'expert' for windows...

I 'just' used an VC10 Environment:
- [Win SDK 7.1] (https://www.microsoft.com/en-us/download/details.aspx?id=8279)
- [.NET Framework 4.5](https://www.microsoft.com/en-us/download/details.aspx?id=30653)
- [SDK Patch](https://www.microsoft.com/en-us/download/details.aspx?id=4422)
- [VC 2010 Redist. Package](https://www.microsoft.com/en-us/download/details.aspx?id=5555)

Then you need:
- install the [MySQL Connector/C 6.1.x](https://dev.mysql.com/downloads/connector/c/) for the headers and the static lib
- copying the **mysqlclient.lib** from the installation path 'C:\Program Files (x86)\MySQL\MySQL Connector C 6.1\lib\vs10' to the Python path 'C:\Python27\libs'
- the rest is up to the **setup.py** with **bdist_wininst** as argument. - These are find the default paths and get the headers and the lib automaticly.
(works only with the 32bit versions if you use the 64bit you the setup.py can not resolve the path of the include directory because the (x86) in the path)
- Maybe you need old inttypes these can you find [here](https://code.google.com/archive/p/msinttypes/downloads)

Here my actually [build](https://github.com/PyMySQL/mysqlclient-python/files/503243/mysqlclient-1.3.7-win32-py2.7-egg-and-exe.zip).

And to the other point - like I said there are moving from 2015 to 2016. The problem is you can have many libs with support of python3 but you need only one who has not. :(

**Comment by methane** [comment]
Thank you for imformation.
Could you try wheel in here?
https://github.com/PyMySQL/mysqlclient-python/releases/tag/1.3.8
