### ISSUE TITLE
1.3.8: unicode_literal always adding the _binary prefix

### ISSUE THREAD

**Issue by claudep** [PyMySQL/mysqlclient-python#123]
After the commit 2617620e2782, `unicode_literal` is always adding the `_binary` prefix because `db.literal` inside `unicode_literal`  is called on the encoded value (and encoded values are always bytes).
This is a serious regression!

**Comment by methane** [comment]
Sorry, but could you describe more detail?

Is this problem is on Python 3 only? or Python 2 only? both?

Original report (https://github.com/PyMySQL/mysqlclient-python/pull/106#issuecomment-250590815 ) was on Python 3.5.

> because db.literal inside unicode_literal is called on the encoded value (and encoded values are always bytes).

What the "encoded value" exactly means?

**Comment by claudep** [comment]
My debug session was on Python 3, but it might happen on Python 2 too.
See this line (inside `def _get_unicode_literal()`):
```
return db.literal(str(u).encode(unicode_literal.charset))
```
Before the patch, `db.literal` was using `string_literal` even for bytes, now it uses `bytes_literal`, so as `str(u).encode(unicode_literal.charset)` is always bytes, the return value is always prepended with `_binary`, while the original value is unicode.

**Comment by claudep** [comment]
The solution *might* be to replace
```
return db.literal(str(u).encode(unicode_literal.charset))
```
by
```
return db.string_literal(str(u).encode(unicode_literal.charset))
```
And probably the same for Python 2.

**Comment by vtermanis** [comment]
I think that is the right solution and is an oversight I made when suggesting the original change.
