### ISSUE TITLE
Fedora installation issue

### ISSUE THREAD

**Issue by nicogarcia** [PyMySQL/mysqlclient-python#127]
On fresh Fedora 24 I had to run `sudo dnf install redhat-rpm-config` to be able to install with pip.

Is it my issue or should that command be added to the README?

Thanks!

**Comment by methane** [comment]
I don't use Fedora.  I don't know about Fedora.
But redhat-rpm-config seems not relating to mysqlclient.

Please ask a question at python-list or somewhere else Fedora users lives.
Here is issue not an user forum or user support.

If some Fedora expert can describe why the package is required, I'll add it to README.

**Comment by kaibosh** [comment]
Installing under fedora 25 today received this build error:

`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6c7HcG/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'e
xec'))" install --record /tmp/pip-jiQBe7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-6c7HcG/mysqlclient/
`

Luckily after spotting this issue report, installed redhat-rpm-config and the pip install of this mysqlclient worked fine. :)

redhat-rpm-config contains various macros and scripts used for rpm package creation/management. It's likely to be needed with recent rhel and centos distros also.

https://wiki.centos.org/HowTos/SetupRpmBuildEnvironment

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/6.3_Technical_Notes/redhat-rpm-config.html
