### ISSUE TITLE
Python stops working on upgrading from 1.3.6

### ISSUE THREAD

**Issue by tiwariav** [PyMySQL/mysqlclient-python#128]
I have a django project running smoothly using,
Python 3.5, Django 1.10 and mysqlclient 1.3.6

But on a different enviornment when I installed the latest version of mysqlclient (1.3.9), most manage.py commands caused python to stop and the only error message was a dialog from the windows operating system stating 'Python stopped working'

**Comment by methane** [comment]
Thank you for reporting.
Could you give me minimum and concrete step to reproduce?
I don't use Django. Is the issue specific to Django?

**Comment by tiwariav** [comment]
I don't think its specific to django, but as I only use the library in django apps, I encountered it there. Even reinstalled python, created virtual enviornments, but with the following stack it always returned the same error until I installed a previously downloaded binary from http://www.lfd.uci.edu/~gohlke/pythonlibs/

output of my pip freeze is as following :

alabaster==0.7.9
Babel==2.3.4
beautifulsoup4==4.5.1
colorama==0.3.7
defusedxml==0.4.1
Django==1.10.2
django-allauth==0.27.0
django-background-tasks==1.0.14
django-compat==1.0.13
django-debug-toolbar==1.6
django-debug-toolbar-template-profiler==1.0.1
docutils==0.12
flake8==3.0.4
imagesize==0.7.1
Jinja2==2.8
MarkupSafe==0.23
mccabe==0.5.2
mysqlclient==1.3.9
oauthlib==2.0.0
pep8==1.7.0
Pillow==3.4.1
pycodestyle==2.0.0
pyflakes==1.2.3
Pygments==2.1.3
python3-openid==3.0.10
pytz==2016.7
requests==2.11.1
requests-oauthlib==0.7.0
selenium==2.53.6
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.4.8
sqlparse==0.2.1

**Comment by methane** [comment]
I confirmed, and I removed binary wheel from PyPI.
I'll wait to next MySQL Connector/C release.

BTW, how did you use mysqlclient 1.3.6 on Windows?
Did you build it by yourself?

**Comment by tiwariav** [comment]
No, i got it from here http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by methane** [comment]
I upload Python 3.5 and 3.6 wheels
