### ISSUE TITLE
cursor.execute() can't run multiple queries

### ISSUE THREAD

**Issue by umrashrf** [PyMySQL/mysqlclient-python#130]
This is useful if I am using `LAST_INSERT_ID()`

``` python
cursor.execute("""INSERT INTO a VALUES (...);
INSERT INTO b VALUES (LAST_INSERT_ID(), ...);""")
```

**Comment by methane** [comment]
MySQL client supports multi query and multi resultant.
Why did you think it isn't supported?

What is you actually tried (in reproducible form) and what was you actually got?

**Comment by umrashrf** [comment]
I have tested it myself and it did not work. I will test again and paste error here later (don't have access to work machines right now).

Today I investigated more and found this http://stackoverflow.com/a/20539187/5294371. This answer is for MySQL-python and not for PyMySQL but I assume your API specification is supposed to be very similar.

**Comment by methane** [comment]
> Today I investigated more and found this http://stackoverflow.com/a/20539187/5294371. 

This question was about when error occurred while multi query.
In other words, multi query works normally.

**Comment by terrisgit** [comment]
This program does not work

```
import pymysql
  
connection = pymysql.connect(host='localhost',
                             user='admin',
                             password='password',
                             db='mysql',
                             charset='utf8mb4')

with connection.cursor() as cursor:
    cursor.execute("select 1 from user; select 1 from user")
    print(cursor.fetchall())
    cursor.nextset()
    print(cursor.fetchall())
```

pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select 1 from mysql.user' at line 1")

This program works

```
import pymysql
  
connection = pymysql.connect(host='localhost',
                             user='admin',
                             password='password',
                             db='mysql',
                             charset='utf8mb4')

with connection.cursor() as cursor:
    cursor.execute("select 1 from user")
    print(cursor.fetchall())
```

**Comment by terrisgit** [comment]
My sincere apologies
