### ISSUE TITLE
Paremetized statements in python3?

### ISSUE THREAD

**Issue by Kyu** [PyMySQL/mysqlclient-python#134]
I'm looking to prevent sql injections, and also strings inserted aren't escaped when I do something like this:

```py
db = _mysql.connect('args')
msg_dct = {
"id": "id"
"author": "name",
"content" "content"
}
query = """INSERT INTO messages (id, author, content) VALUES ({id}, "{author}", "{content}") """.format(**msg_dct)

try:
    db.query(query)
except Exception as e:
    with open("errors.txt", "a+", encoding='utf-8') as err:
        print("{0}: {1} on query:\n\n {2}\n\n\n".format(type(e).__name__, str(e), query), file=err)
```
if the content contains any multiple quotes 
I get an error as shows:

ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'Piss paintings are so 1970\'s post-modern"", "")\' at line 1') on query:

 INSERT INTO messages (id, author, content) VALUES (244972282190102538, ""Author", ""Piss paintings are so 1970's post-modern"")

I have a file of 1.6k or so errors

 also while trying to find help i've been told my method leaves space for sql injection
This is the only lib I see that supports python 3, so the help based on py2 is kinda useless

**Comment by methane** [comment]
See here: https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.hdf6lpk11

And here: http://docs.python-guide.org/en/latest/scenarios/db/#db-api
