### ISSUE TITLE
Build mysqlclient under Python27 on Windows

### ISSUE THREAD

**Issue by pyy** [PyMySQL/mysqlclient-python#135]
Hello,

I build mysqlclient.lib under VS2015 and use this file to build mysqlclient-python 1.3.9 with Python3.5.2 successfully. I aslo put some of steps in the wiki page: https://github.com/PyMySQL/mysqlclient-python/wiki/Building-mysqlclient.lib-on-Windows-with-VS2015

```
python setup.py build --compiler msvc
python setup.py bdist_wininst
```

But when I use the same steps to build mysqlclient under Python 2.7.12, I got these errors:
```
C:\Users\...\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.VC\Include\wchar.h(1209) : 
error C2088: '==' : illegal for struct _mysql.c(260) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', 
poible loss of data _mysql.c(290) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', 
poible loss of data _mysql.c(441) : warning C4244: 'initializing' : conversion from 'Py_ssize_t' t'int', 
possible loss of data _mysql.c(781) : warning C4244: 'function' : conversion from 'SOCKET' to 'long'possible loss of data
_mysql.c(1116) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', psible loss of data
_mysql.c(1221) : warning C4244: '=' : conversion from 'Py_ssize_t' to 'int', psible loss of data
_mysql.c(1433) : warning C4267: '=' : conversion from 'size_t' to 'int', possie loss of data
_mysql.c(1435) : warning C4267: '=' : conversion from 'size_t' to 'int', possie loss of data
_mysql.c(1471) : warning C4267: '=' : conversion from 'size_t' to 'int', possie loss of data
_mysql.c(1473) : warning C4267: '=' : conversion from 'size_t' to 'int', possie loss of data
_mysql.c(2236) : warning C4244: 'function' : conversion from '__int64' to 'lon, possible loss of data
error: command 'C:\\Users\\...\\AppData\\Local\\Programs\\Common\\Microsoft\\
sual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2
```

mysqlclient-python 1.3.9

May I ask how to build mysqlclient for Python 2?  Which version of software should I use?
How can I get `mysqlclient-1.3.9-cp27-cp27m-win32.whl`  or `mysqlclient-1.3.9-cp27-cp27m-win_amd64.whl` as showing on pip page. https://pypi.python.org/pypi/mysqlclient

Thank you.

**Comment by methane** [comment]
Sorry, I'm not Windows expert.  I gave up building on Windows.
Please ask a question on StackOverflow or MySQL forum.

**Comment by pyy** [comment]
@methane May I ask who is the auther for 
 mysqlclient-1.3.9-cp27-cp27m-win32.whl or mysqlclient-1.3.9-cp27-cp27m-win_amd64.whl as showing on pip page? https://pypi.python.org/pypi/mysqlclient

Thank you.

**Comment by methane** [comment]
Me.  But I don't want to boot Windows machine only for you.

**Comment by methane** [comment]
**[You must not ask a question on issue tracker](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.hdf6lpk11)**

**Comment by methane** [comment]
https://github.com/PyMySQL/mysqlclient-python/issues/120#issuecomment-250769231
