### ISSUE TITLE
Error installing on Mac OS X

### ISSUE THREAD

**Issue by collinanderson** [PyMySQL/mysqlclient-python#14]
Python 3:
 
    Error loading MySQLdb module: dlopen(/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/_mysql.so, 2): Library not loaded: libmysqlclient.18.dylib
      Referenced from: /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/_mysql.so
      Reason: image not found

Python 2:

    Error loading MySQLdb module: dlopen(/Library/Python/2.7/site-packages/_mysql.so, 2): Library not loaded: libmysqlclient.18.dylib
      Referenced from: /Library/Python/2.7/site-packages/_mysql.so
      Reason: image not found

**Comment by methane** [comment]
It's a common environment problem rather than issue of this library.
http://stackoverflow.com/a/6100648/3430118

**Comment by XiaolinLeo** [comment]
In python3 you can try:
`sudo install_name_tool -change libmysqlclient.18.dylib /usr/local/mysql/lib/libmysqlclient.18.dylib 
 /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/_mysql.so`
In python2
`sudo install_name_tool -change libmysqlclient.18.dylib \
/usr/local/mysql/lib/libmysqlclient.18.dylib \
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/_mysql.so`

**Comment by mikezone** [comment]
> To fix it I had to copy /usr/local/mysql/lib/libmysqlclient.18.dylib to /usr/local/lib/libmysqlclient.18.dylib

I fixed it. Thank u!

**Comment by aCampello** [comment]
Fixed it for me too; although I had to copy everything:

```
cp -r /usr/local/mysql/lib/* /usr/local/lib/
```

**Comment by Satan0069** [comment]
After pasting the code and even installing mysql again it is showing this

-bash: /usr/local/mysql/lib/libmysqlclient.18.dylib: No such file or directory

**Comment by JakobLS** [comment]
@Satan0069 did you find a solution? Please share if so.

**Comment by ManojBadiger** [comment]
> After pasting the code and even installing mysql again it is showing this
> 
> -bash: /usr/local/mysql/lib/libmysqlclient.18.dylib: No such file or directory

Hi check your version.In my case it is 21 instead of 18
so change number.
Or go to chrome  and enter
'/usr/local/mysql/lib/'
copy everything within lib and paste within mysql
