### ISSUE TITLE
Cannot install mysqlclient on Windows 8.1

### ISSUE THREAD

**Issue by vish30** [PyMySQL/mysqlclient-python#146]
I am using Django version 1.10.5 and Python 3.6. I have deployed my Django project using mod_wsgi module on an Apache server. The operating system is Windows 8.1. When I try installing mysqlclient through ```pip install mysqlclient```, I get following error:
```
_mysql.c(29): fatal error C1083: Cannot open include file: 'my_config.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
 ```

**Comment by methane** [comment]
There are many similar issue reported. Please search before submit new issue.

Oracle doesn't release mysqliclient lib for new msvcrt for a long time.
https://dev.mysql.com/downloads/connector/c/6.1.html
