### ISSUE TITLE
mysqlclient 1.3.10 breaks on AppVeyor

### ISSUE THREAD

**Issue by jbremer** [PyMySQL/mysqlclient-python#151]
Thanks for your Windows support etc. I just noticed that version `1.3.10` fails to install properly on AppVeyor. Please find following a failing run from today (again, based on `1.3.10`) and a successful run from yesterday (seemingly based on `1.3.9`).

success: https://ci.appveyor.com/project/jbremer/cuckoo/build/1.0.259
failure: https://ci.appveyor.com/project/jbremer/cuckoo/build/1.0.260

Thanks again! Please let me know what the plan for resolving this matter is, otherwise I'll simply pin to version `1.3.9` for now ;-)

**Comment by methane** [comment]
Instead wheel for Python 3.5 and 3.6 are added, wheel for Python 2.7 is dropped.

Python 2.7 is based on VC++ of VS2008.  It's too old to link libmysqlclient.

**Comment by jbremer** [comment]
Gotcha, `2.7` support was dropped in `1.3.10`. I'll be pinning to `1.3.9` then ;-)

**Comment by methane** [comment]
Why don't you move Python 3 instead of pinning?

**Comment by jbremer** [comment]
Hehe, easier said than done ;-) Our project (https://github.com/cuckoosandbox/cuckoo) has at least a dozen Python2-only dependencies, so moving to Python 3 will require major changes - and not only in our project, but also in 3rd party projects of which I don't necessarily have control.

**Comment by methane** [comment]
I can't believe there are dozen Python2-only dependencies. https://github.com/cuckoosandbox/cuckoo/blob/master/requirements.txt

> 2.7 support was dropped in 1.3.10

strictly speaking, Python 2.7 is supported in mysqlclient 1.3.10, other than Windows.

Oracle stop releasing MySQL Connector/C for VC9, and Official CPython 2.7 is based on VC9.
It means you cannot get any security update from Oracle.

You may be able to build custom Python 2 by VC14 (VS2015), but I recommend to move Python 3 ASAP.

**Comment by jbremer** [comment]
Well, there's still a handful of projects, though ;-) The biggest reason for now is the fact that all of the changes to be Python3-compatible will have to be properly unit tested and this takes a lot of effort. Can only focus on so many things at once.
