### ISSUE TITLE
Install in Docker

### ISSUE THREAD

**Issue by Applemann** [PyMySQL/mysqlclient-python#158]
Hello I am trying install mysqlclient-python in docker with Debian 8
but when I run python3 setup.py install
I get error:
```
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/_mysql.o -lmysqlclient -lpthread -lz -lm -ldl -lssl -lcrypto -o build/lib.linux-x86_64-3.4/_mysql.cpython-34m.so
/usr/bin/ld: cannot find -lssl
/usr/bin/ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

```
I tryed install various packages (openssl, crypto++, libmysqlclient-dev,...) but nothing helped me..
Do you know what exactly I need?

**Comment by asottile** [comment]
You need to install `libssl-dev`.  I think I already answered this for ya on stackoverflow though :D https://stackoverflow.com/a/43010036/812183

**Comment by Applemann** [comment]
Yes it works. :) 
Thank you
