### ISSUE TITLE
error: command 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64

### ISSUE THREAD

**Issue by lyan11** [PyMySQL/mysqlclient-python#159]
(python35) C:\Windows\system32>pip install cvxopt
Collecting cvxopt
  Using cached cvxopt-1.1.9.tar.gz
Building wheels for collected packages: cvxopt
  Running setup.py bdist_wheel for cvxopt ... error
  Complete output from command "C:\Users\Lei Yan\Anaconda2\envs\python35\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\LEIYAN~1\\AppData\\Local\\Temp\\pip-build-yibmq5_h\\cvxopt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\LEIYAN~1\AppData\Local\Temp\tmpbz9wi_w6pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  creating build\lib.win-amd64-3.5\cvxopt
  copying src\python\coneprog.py -> build\lib.win-amd64-3.5\cvxopt
  copying src\python\cvxprog.py -> build\lib.win-amd64-3.5\cvxopt
  copying src\python\info.py -> build\lib.win-amd64-3.5\cvxopt
  copying src\python\misc.py -> build\lib.win-amd64-3.5\cvxopt
  copying src\python\modeling.py -> build\lib.win-amd64-3.5\cvxopt
  copying src\python\msk.py -> build\lib.win-amd64-3.5\cvxopt
  copying src\python\printing.py -> build\lib.win-amd64-3.5\cvxopt
  copying src\python\solvers.py -> build\lib.win-amd64-3.5\cvxopt
  copying src\python\_version.py -> build\lib.win-amd64-3.5\cvxopt
  copying src\python\__init__.py -> build\lib.win-amd64-3.5\cvxopt
  UPDATING build\lib.win-amd64-3.5\cvxopt/_version.py
  set build\lib.win-amd64-3.5\cvxopt/_version.py to '1.1.9'
  running build_ext
  building 'base' extension
  creating build\temp.win-amd64-3.5
  creating build\temp.win-amd64-3.5\Release
  creating build\temp.win-amd64-3.5\Release\src
  creating build\temp.win-amd64-3.5\Release\src\C
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Users\Lei Yan\Anaconda2\envs\python35\include" "-IC:\Users\Lei Yan\Anaconda2\envs\python35\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /Tcsrc/C/base.c /Fobuild\temp.win-amd64-3.5\Release\src/C/base.obj
  base.c
  c:\users\lei yan\appdata\local\temp\pip-build-yibmq5_h\cvxopt\src\c\misc.h(35): error C2146: syntax error: missing ';' before identifier 'z'
  c:\users\lei yan\appdata\local\temp\pip-build-yibmq5_h\cvxopt\src\c\misc.h(35): error C2061: syntax error: identifier 'z'
  c:\users\lei yan\appdata\local\temp\pip-build-yibmq5_h\cvxopt\src\c\misc.h(36): error C2059: syntax error: '}'
  src/C/base.c(46): error C2122: 'void *': prototype parameter in name list illegal
  src/C/base.c(46): error C2122: 'int': prototype parameter in name list illegal
  src/C/base.c(46): error C2122: 'void **': prototype parameter in name list illegal
  src/C/base.c(49): error C2081: 'number': name in formal parameter list illegal
  src/C/base.c(52): error C2081: 'number': name in formal parameter list illegal
  src/C/base.c(55): error C2081: 'number': name in formal parameter list illegal
  src/C/base.c(58): error C2081: 'number': name in formal parameter list illegal
  src/C/base.c(60): error C2146: syntax error: missing ')' before identifier '_complex'
  src/C/base.c(60): error C2061: syntax error: identifier '_complex'
  src/C/base.c(60): error C2059: syntax error: ')'
  src/C/base.c(67): error C2061: syntax error: identifier 'One'
  src/C/base.c(67): error C2059: syntax error: ';'
  src/C/base.c(67): error C2059: syntax error: '['
  src/C/base.c(79): error C2146: syntax error: missing ')' before identifier '_complex'
  src/C/base.c(79): error C2065: '_complex': undeclared identifier
  src/C/base.c(79): error C2059: syntax error: ')'
  src/C/base.c(79): error C2297: '*': illegal, right operand has type 'void'
  src/C/base.c(79): error C2143: syntax error: missing ')' before ';'
  src/C/base.c(95): error C2146: syntax error: missing ')' before identifier '_complex'
  src/C/base.c(95): error C2065: '_complex': undeclared identifier
  src/C/base.c(95): error C2059: syntax error: ')'
  src/C/base.c(95): error C2297: '*': illegal, right operand has type 'void'
  src/C/base.c(95): error C2143: syntax error: missing ')' before ';'
  src/C/base.c(96): error C2146: syntax error: missing ')' before identifier '_complex'
  src/C/base.c(96): error C2065: '_complex': undeclared identifier
  src/C/base.c(96): error C2059: syntax error: ')'
  src/C/base.c(96): error C2297: '*': illegal, right operand has type 'void'
  src/C/base.c(96): error C2143: syntax error: missing ')' before ';'
  src/C/base.c(134): warning C4244: '=': conversion from 'Py_ssize_t' to 'double', possible loss of data
  src/C/base.c(157): error C2146: syntax error: missing ')' before identifier '_complex'
  src/C/base.c(157): error C2065: '_complex': undeclared identifier
  src/C/base.c(157): error C2100: illegal indirection
  src/C/base.c(157): error C2059: syntax error: ')'
  src/C/base.c(157): error C2297: '*': illegal, right operand has type 'void *'
  src/C/base.c(159): error C2146: syntax error: missing ')' before identifier '_complex'
  src/C/base.c(159): error C2065: '_complex': undeclared identifier
  src/C/base.c(159): error C2100: illegal indirection
  src/C/base.c(159): error C2059: syntax error: ')'
  src/C/base.c(159): error C2297: '*': illegal, right operand has type 'void *'
  src/C/base.c(161): error C2146: syntax error: missing ')' before identifier '_complex'
  src/C/base.c(161): error C2065: '_complex': undeclared identifier
  src/C/base.c(161): error C2100: illegal indirection
  src/C/base.c(161): error C2059: syntax error: ')'
  src/C/base.c(161): error C2297: '*': illegal, right operand has type 'void *'
  src/C/base.c(161): error C2297: '*': illegal, right operand has type 'void'
  src/C/base.c(161): error C2143: syntax error: missing ')' before ';'
  src/C/base.c(166): error C2146: syntax error: missing ')' before identifier '_complex'
  src/C/base.c(166): error C2065: '_complex': undeclared identifier
  src/C/base.c(166): error C2100: illegal indirection
  src/C/base.c(166): error C2059: syntax error: ')'
  src/C/base.c(166): error C2297: '*': illegal, right operand has type 'void *'
  src/C/base.c(166): error C2088: '*': illegal for struct
  src/C/base.c(247): warning C4244: 'function': conversion from 'Py_ssize_t' to 'long', possible loss of data
  src/C/base.c(259): error C2146: syntax error: missing ')' before identifier '_complex'
  src/C/base.c(259): error C2065: '_complex': undeclared identifier
  src/C/base.c(259): error C2059: syntax error: ')'
  src/C/base.c(259): error C2297: '*': illegal, right operand has type 'void'
  src/C/base.c(259): error C2143: syntax error: missing ')' before ';'
  src/C/base.c(264): error C2146: syntax error: missing ')' before identifier 'a'
  src/C/base.c(264): error C2081: 'number': name in formal parameter list illegal
  src/C/base.c(264): error C2061: syntax error: identifier 'a'
  src/C/base.c(264): error C2059: syntax error: ';'
  src/C/base.c(264): error C2059: syntax error: ','
  src/C/base.c(264): error C2059: syntax error: ')'
  src/C/base.c(273): error C2146: syntax error: missing ')' before identifier 'a'
  src/C/base.c(273): error C2081: 'number': name in formal parameter list illegal
  src/C/base.c(273): error C2061: syntax error: identifier 'a'
  src/C/base.c(273): error C2059: syntax error: ';'
  src/C/base.c(273): error C2059: syntax error: ','
  src/C/base.c(273): error C2059: syntax error: ')'
  src/C/base.c(281): error C2146: syntax error: missing ')' before identifier 'a'
  src/C/base.c(281): error C2081: 'number': name in formal parameter list illegal
  src/C/base.c(281): error C2061: syntax error: identifier 'a'
  src/C/base.c(281): error C2059: syntax error: ';'
  src/C/base.c(281): error C2059: syntax error: ','
  src/C/base.c(281): error C2059: syntax error: ')'
  src/C/base.c(291): error C2081: 'number': name in formal parameter list illegal
  src/C/base.c(291): error C2065: 'idiv': undeclared identifier
  src/C/base.c(291): error C2065: 'ddiv': undeclared identifier
  src/C/base.c(291): error C2065: 'zdiv': undeclared identifier
  src/C/base.c(291): error C2099: initializer is not a constant
  src/C/base.c(293): error C2146: syntax error: missing ')' before identifier 'a'
  src/C/base.c(293): error C2081: 'number': name in formal parameter list illegal
  src/C/base.c(293): error C2061: syntax error: identifier 'a'
  src/C/base.c(293): error C2059: syntax error: ';'
  src/C/base.c(293): error C2059: syntax error: ','
  src/C/base.c(293): error C2059: syntax error: ')'
  src/C/base.c(302): error C2146: syntax error: missing ')' before identifier 'a'
  src/C/base.c(302): error C2081: 'number': name in formal parameter list illegal
  src/C/base.c(302): error C2061: syntax error: identifier 'a'
  src/C/base.c(302): error C2059: syntax error: ';'
  src/C/base.c(302): error C2059: syntax error: ','
  src/C/base.c(302): error C2059: syntax error: ')'
  src/C/base.c(311): error C2081: 'number': name in formal parameter list illegal
  src/C/base.c(311): error C2065: 'mtx_irem': undeclared identifier
  src/C/base.c(311): error C2065: 'mtx_drem': undeclared identifier
  src/C/base.c(311): error C2099: initializer is not a constant
  src/C/base.c(360): error C2065: 'number': undeclared identifier
  src/C/base.c(360): error C2146: syntax error: missing ';' before identifier 'a'
  src/C/base.c(360): error C2065: 'a': undeclared identifier
  src/C/base.c(360): fatal error C1003: error count exceeds 100; stopping compilation
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for cvxopt
  Running setup.py clean for cvxopt
Failed to build cvxopt
Installing collected packages: cvxopt
  Running setup.py install for cvxopt ... error
    Complete output from command "C:\Users\Lei Yan\Anaconda2\envs\python35\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\LEIYAN~1\\AppData\\Local\\Temp\\pip-build-yibmq5_h\\cvxopt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\LEIYAN~1\AppData\Local\Temp\pip-b83bhphz-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.5
    creating build\lib.win-amd64-3.5\cvxopt
    copying src\python\coneprog.py -> build\lib.win-amd64-3.5\cvxopt
    copying src\python\cvxprog.py -> build\lib.win-amd64-3.5\cvxopt
    copying src\python\info.py -> build\lib.win-amd64-3.5\cvxopt
    copying src\python\misc.py -> build\lib.win-amd64-3.5\cvxopt
    copying src\python\modeling.py -> build\lib.win-amd64-3.5\cvxopt
    copying src\python\msk.py -> build\lib.win-amd64-3.5\cvxopt
    copying src\python\printing.py -> build\lib.win-amd64-3.5\cvxopt
    copying src\python\solvers.py -> build\lib.win-amd64-3.5\cvxopt
    copying src\python\_version.py -> build\lib.win-amd64-3.5\cvxopt
    copying src\python\__init__.py -> build\lib.win-amd64-3.5\cvxopt
    UPDATING build\lib.win-amd64-3.5\cvxopt/_version.py
    set build\lib.win-amd64-3.5\cvxopt/_version.py to '1.1.9'
    running build_ext
    building 'base' extension
    creating build\temp.win-amd64-3.5
    creating build\temp.win-amd64-3.5\Release
    creating build\temp.win-amd64-3.5\Release\src
    creating build\temp.win-amd64-3.5\Release\src\C
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD "-IC:\Users\Lei Yan\Anaconda2\envs\python35\include" "-IC:\Users\Lei Yan\Anaconda2\envs\python35\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /Tcsrc/C/base.c /Fobuild\temp.win-amd64-3.5\Release\src/C/base.obj
    base.c
    c:\users\lei yan\appdata\local\temp\pip-build-yibmq5_h\cvxopt\src\c\misc.h(35): error C2146: syntax error: missing ';' before identifier 'z'
    c:\users\lei yan\appdata\local\temp\pip-build-yibmq5_h\cvxopt\src\c\misc.h(35): error C2061: syntax error: identifier 'z'
    c:\users\lei yan\appdata\local\temp\pip-build-yibmq5_h\cvxopt\src\c\misc.h(36): error C2059: syntax error: '}'
    src/C/base.c(46): error C2122: 'void *': prototype parameter in name list illegal
    src/C/base.c(46): error C2122: 'int': prototype parameter in name list illegal
    src/C/base.c(46): error C2122: 'void **': prototype parameter in name list illegal
    src/C/base.c(49): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(52): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(55): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(58): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(60): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(60): error C2061: syntax error: identifier '_complex'
    src/C/base.c(60): error C2059: syntax error: ')'
    src/C/base.c(67): error C2061: syntax error: identifier 'One'
    src/C/base.c(67): error C2059: syntax error: ';'
    src/C/base.c(67): error C2059: syntax error: '['
    src/C/base.c(79): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(79): error C2065: '_complex': undeclared identifier
    src/C/base.c(79): error C2059: syntax error: ')'
    src/C/base.c(79): error C2297: '*': illegal, right operand has type 'void'
    src/C/base.c(79): error C2143: syntax error: missing ')' before ';'
    src/C/base.c(95): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(95): error C2065: '_complex': undeclared identifier
    src/C/base.c(95): error C2059: syntax error: ')'
    src/C/base.c(95): error C2297: '*': illegal, right operand has type 'void'
    src/C/base.c(95): error C2143: syntax error: missing ')' before ';'
    src/C/base.c(96): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(96): error C2065: '_complex': undeclared identifier
    src/C/base.c(96): error C2059: syntax error: ')'
    src/C/base.c(96): error C2297: '*': illegal, right operand has type 'void'
    src/C/base.c(96): error C2143: syntax error: missing ')' before ';'
    src/C/base.c(134): warning C4244: '=': conversion from 'Py_ssize_t' to 'double', possible loss of data
    src/C/base.c(157): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(157): error C2065: '_complex': undeclared identifier
    src/C/base.c(157): error C2100: illegal indirection
    src/C/base.c(157): error C2059: syntax error: ')'
    src/C/base.c(157): error C2297: '*': illegal, right operand has type 'void *'
    src/C/base.c(159): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(159): error C2065: '_complex': undeclared identifier
    src/C/base.c(159): error C2100: illegal indirection
    src/C/base.c(159): error C2059: syntax error: ')'
    src/C/base.c(159): error C2297: '*': illegal, right operand has type 'void *'
    src/C/base.c(161): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(161): error C2065: '_complex': undeclared identifier
    src/C/base.c(161): error C2100: illegal indirection
    src/C/base.c(161): error C2059: syntax error: ')'
    src/C/base.c(161): error C2297: '*': illegal, right operand has type 'void *'
    src/C/base.c(161): error C2297: '*': illegal, right operand has type 'void'
    src/C/base.c(161): error C2143: syntax error: missing ')' before ';'
    src/C/base.c(166): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(166): error C2065: '_complex': undeclared identifier
    src/C/base.c(166): error C2100: illegal indirection
    src/C/base.c(166): error C2059: syntax error: ')'
    src/C/base.c(166): error C2297: '*': illegal, right operand has type 'void *'
    src/C/base.c(166): error C2088: '*': illegal for struct
    src/C/base.c(247): warning C4244: 'function': conversion from 'Py_ssize_t' to 'long', possible loss of data
    src/C/base.c(259): error C2146: syntax error: missing ')' before identifier '_complex'
    src/C/base.c(259): error C2065: '_complex': undeclared identifier
    src/C/base.c(259): error C2059: syntax error: ')'
    src/C/base.c(259): error C2297: '*': illegal, right operand has type 'void'
    src/C/base.c(259): error C2143: syntax error: missing ')' before ';'
    src/C/base.c(264): error C2146: syntax error: missing ')' before identifier 'a'
    src/C/base.c(264): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(264): error C2061: syntax error: identifier 'a'
    src/C/base.c(264): error C2059: syntax error: ';'
    src/C/base.c(264): error C2059: syntax error: ','
    src/C/base.c(264): error C2059: syntax error: ')'
    src/C/base.c(273): error C2146: syntax error: missing ')' before identifier 'a'
    src/C/base.c(273): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(273): error C2061: syntax error: identifier 'a'
    src/C/base.c(273): error C2059: syntax error: ';'
    src/C/base.c(273): error C2059: syntax error: ','
    src/C/base.c(273): error C2059: syntax error: ')'
    src/C/base.c(281): error C2146: syntax error: missing ')' before identifier 'a'
    src/C/base.c(281): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(281): error C2061: syntax error: identifier 'a'
    src/C/base.c(281): error C2059: syntax error: ';'
    src/C/base.c(281): error C2059: syntax error: ','
    src/C/base.c(281): error C2059: syntax error: ')'
    src/C/base.c(291): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(291): error C2065: 'idiv': undeclared identifier
    src/C/base.c(291): error C2065: 'ddiv': undeclared identifier
    src/C/base.c(291): error C2065: 'zdiv': undeclared identifier
    src/C/base.c(291): error C2099: initializer is not a constant
    src/C/base.c(293): error C2146: syntax error: missing ')' before identifier 'a'
    src/C/base.c(293): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(293): error C2061: syntax error: identifier 'a'
    src/C/base.c(293): error C2059: syntax error: ';'
    src/C/base.c(293): error C2059: syntax error: ','
    src/C/base.c(293): error C2059: syntax error: ')'
    src/C/base.c(302): error C2146: syntax error: missing ')' before identifier 'a'
    src/C/base.c(302): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(302): error C2061: syntax error: identifier 'a'
    src/C/base.c(302): error C2059: syntax error: ';'
    src/C/base.c(302): error C2059: syntax error: ','
    src/C/base.c(302): error C2059: syntax error: ')'
    src/C/base.c(311): error C2081: 'number': name in formal parameter list illegal
    src/C/base.c(311): error C2065: 'mtx_irem': undeclared identifier
    src/C/base.c(311): error C2065: 'mtx_drem': undeclared identifier
    src/C/base.c(311): error C2099: initializer is not a constant
    src/C/base.c(360): error C2065: 'number': undeclared identifier
    src/C/base.c(360): error C2146: syntax error: missing ';' before identifier 'a'
    src/C/base.c(360): error C2065: 'a': undeclared identifier
    src/C/base.c(360): fatal error C1003: error count exceeds 100; stopping compilation
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command ""C:\Users\Lei Yan\Anaconda2\envs\python35\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\LEIYAN~1\\AppData\\Local\\Temp\\pip-build-yibmq5_h\\cvxopt\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\LEIYAN~1\AppData\Local\Temp\pip-b83bhphz-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\LEIYAN~1\AppData\Local\Temp\pip-build-yibmq5_h\cvxopt\

**Comment by lyan11** [comment]
could anybody tell me how to solve it?

**Comment by methane** [comment]
It's totally unrelated to this project.  Go stackoverflow.

**Comment by kikizxd** [comment]
Have you solved this problem?
I also met this question,can you tell me how to solve it?

**Comment by methane** [comment]
@kikizxd Why do you come here?
@lyan11 failed `pip install cvxopt`, but cvxopt is not relating to this project.

**Comment by kikizxd** [comment]
I searched my problem and find this page, I knew you have closed this question and I just try to ask.
Then, have you solved it?

**Comment by methane** [comment]
No, I don't know vcxopt and I'm not interested in it.

And this is my project issue tracker.  All post in here sends notification mail to me.
It means you're sending spam mail to OSS maintainer.

DON'T ask question here.  Go stackoverflow.
