### ISSUE TITLE
compile failing on Centos7 - MariaDB 10.2, python 3.5

### ISSUE THREAD

**Issue by marc-gist** [PyMySQL/mysqlclient-python#160]
I have MariaDB 10.2 installed and working (including devel packages), python35u install and working including devel packages.

When I try to complile/install mysqlclient it fails with `/bin/ld: cannot find -lmariad`
on this command; `gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-3.5/_mysql.o -L/usr/lib64 -L/usr/lib64 -lmariadb -lpython3.5m -o build/lib.linux-x86_64-3.5/_mysql.cpython-35m-x86_64-linux-gnu.so`

any ideas? Thanks!

**Comment by methane** [comment]
**[You must not ask a question on issue tracker](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.hdf6lpk11)**

**Comment by s0m01cp** [comment]
@marc-gist did you figure out the solution for this one. I am having the same issue.

**Comment by marc-gist** [comment]
No @s0m01cp , and unfortunately seems the maintainer doesn't "care" (as not sure why my question/bug is closed, as its clearly an issue).  I installed MySQL community 5.7 from Oracle rpm's and it works fine.

**Comment by methane** [comment]
Have you Google error message?
I found `yum install MariaDB-shared` only one minute, even from phone.

**Comment by methane** [comment]
If you don't know how to use Google well, have you asked the question on Stackoverflow?
You should use community before using issue tracker.  The reason is described well in https://github.com/PyMySQL/mysqlclient-python/issues/160#issuecomment-292758458.

**Comment by Aimiyoo** [comment]
> Have you Google error message?
> I found `yum install MariaDB-shared` only in one minute, even from phone.

nice, it worked
