### ISSUE TITLE
Consider `redhat-rpm-config` in dependencies for Redhat

### ISSUE THREAD

**Issue by Alirezaies** [PyMySQL/mysqlclient-python#164]
Hello and thank you so much for this usefull repository.

I used to use this library on Ubuntu with no problem, then I moved to Fedora and I faced `error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory`

I searched and fixed this problem by `sudo yum install redhat-rpm-config` so I think it is better to add it in the Fedora/RedHat dependencies.

Thank You.

**Comment by Alirezaies** [comment]
And by the way I forgot to say I need to use `pip install --no-binary mysqlclient mysqlclient` to install it but it works well ^_^

**Comment by methane** [comment]
Please report it to Fedora.
`sudo dnf install mysql-devel` should install all dependency to build C code linking libmysqlclient.
