### ISSUE TITLE
SHA2 Cipher

### ISSUE THREAD

**Issue by Abhimanyu310** [PyMySQL/mysqlclient-python#166]
Does mysqlclient support SHA2 ciphers? I am trying to connect to a MySQL remote server that wants me to use SHA2, and I get an error (unknown error number). And I know the error is due to the cipher, since when the SHA2 condition wasn't enforced, I could connect to it. And yes, I can connect to it using MySQL Workbench (the commercial edition, which supports SHA2). 
This is how I set it in my settings.py

```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '#db',
        'USER': '#user',
        'PASSWORD': '#password',
        'HOST': '#host',
        'PORT': '#port',
        'OPTIONS': {
            'ssl': {'ca': '/path/to/ca-cert.pem'}
        }
    }
}
```

**Comment by methane** [comment]
Do you mean TLS cipher?
It's up to your Python's ssl module and OpenSSL used by it.
PyMySQL doesn't do anything about cipher.

**Comment by Abhimanyu310** [comment]
@methane Thank you for the reply. I checked the openssl my Python was using, it was OpenSSL 1.0.2k, which should support SHA256 ciphers, but I still cannot connect. If you have any idea on how I can fix this or if I need to update anything else, then please let me know as it can save me a couple days of figuring it out on my own :)
