### ISSUE TITLE
Error: Symbol not found: _mysql_affected_rows

### ISSUE THREAD

**Issue by MarcSky** [PyMySQL/mysqlclient-python#172]
Hello
I have some error. I try to use Django 1.11 + python3.5 + mysql on my OSX. When i install the library mysqlclient i get error:
`django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module: 
dlopen(/lib/python3.5/site-packages/_mysql.cpython-35m-darwin.so, 2): Symbol not found: _mysql_affected_rows
`
How to fix this error?

**Comment by methane** [comment]
uninstall mysqlclient
remove pip cache
install mysqlclient

**Comment by MarcSky** [comment]
its doesnt help me (

**Comment by methane** [comment]
It's your environment problem.
Here is not Q&A site and I'm not free tech support.
