### ISSUE TITLE
Building against Mariadb 10.2.6

### ISSUE THREAD

**Issue by igremmerlb** [PyMySQL/mysqlclient-python#176]
I am building against MariaDB 10.2.6, which was just released a few days ago as a stable version.  The mysqlclient-python fails to compile with the following error.  To test it's easy to get the docker image:
docker run -it mariadb:10.2.6 bash
apt-get install ...
git clone mysqlclient-python ...
cd ...
python setup.py install

The mariadb:10.2.6 image is based off Debian Jessie 8.8.

I get the following error:
```
> x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Dversion_info=(1,3,10,'final',0) -D__version__=1.3.10 -I/usr/include/mysql -I/usr/include/python2.7 -c _mysql.c -o build/temp.linux-x86_64-2.7/_mysql.o
> In file included from _mysql.c:30:0:
> /usr/include/mysql/mysql.h:438:3: warning: function declaration isn't a prototype [-Wstrict-prototypes]
>    MYSQL_CLIENT_PLUGIN_HEADER
>    ^
> /usr/include/mysql/mysql.h:583:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
>  my_bool STDCALL mysql_embedded();
>  ^
> _mysql.c: In function '_mysql_ConnectionObject_ping':
> _mysql.c:1911:41: error: 'MYSQL' has no member named 'reconnect'
>   if ( reconnect != -1 ) self->connection.reconnect = reconnect;
>                                          ^
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> 
```

Thanks for your help!

**Comment by notFloran** [comment]
Same problem here but with macOS.

For now I use the following workaround with *mariadb-connector-c*: https://stackoverflow.com/a/44268445/2460297

**Comment by NielsH** [comment]
Hi @methane 

There are some references to this issue and the fix for this from the following Ansible issue:
https://github.com/ansible/ansible/issues/25960

Are you perhaps able to comment on this? People aren't fully sure at the moment if the Ansible issue is related to this issue. If you are able to clarify this that would be great.

Thank you!

**Comment by methane** [comment]
@NielsH It seems completely different.  Build error is not runtime segmentation fault.

**Comment by stemid** [comment]
When will this be in a release?

I just tried 1.3.10 and still get the same error on CentOS 7 with MariaDB 10.2. 

In my case the workaround was simply to use MariaDB 5.5 because I don't mind using an older release in this case. But in production I'll likely want 10.2.

**Comment by methane** [comment]
When next MySQL Connector/C is released.
Until then, you can install from master branch.

**Comment by archenroot** [comment]
I just tried following artefact to install:
https://downloads.mariadb.com/MariaDB/mariadb-10.3/yum/centos/6.3/x86_64/rpms/MariaDB-10.3.2-centos6-x86_64-devel.rpm

from:
https://downloads.mariadb.com/MariaDB/mariadb-10.3/yum/centos/6.3/x86_64/rpms/

Same error, how to properly resolve this issue? I using:
pip3 install mysqlclient==1.3.6

**Comment by methane** [comment]
pip3 install https://github.com/PyMySQL/mysqlclient-python

**Comment by archenroot** [comment]
@methane  Thanks budy, this is some long time when I need to use PIP on Centos, otherwise I work with python in Gentoo way, so we wrap everything into our package management system. The command you gave me gives me:
```
[root@lgh-inp-hmi data]# pip3 install https://github.com/PyMySQL/mysqlclient-python
Collecting https://github.com/PyMySQL/mysqlclient-python
  Downloading https://github.com/PyMySQL/mysqlclient-python
     | 153kB 941kB/s
  Cannot unpack file /tmp/pip-wx9zj9_4-unpack/mysqlclient-python (downloaded from /tmp/pip-d3310d21-build, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-d3310d21-build
```

I am on Centos 6

**Comment by archenroot** [comment]
Ok, I did:
`pip3 install git+https://github.com/PyMySQL/mysqlclient-python.git`

**Comment by archenroot** [comment]
I have some progress, but the error still appear, I have on Centos 6 following packages installed:
```
[root@lgh-inp-hmi data]# yum list installed |grep MariaDB
MariaDB-client.x86_64  10.2.7-1.el6     @bull                                   
MariaDB-common.x86_64  10.2.7-1.el6     @bull                                   
MariaDB-compat.x86_64  10.2.7-1.el6     @bull                                   
MariaDB-devel.x86_64   10.2.7-1.el6     @bull                                   
MariaDB-server.x86_64  10.2.7-1.el6     @bull  
```
And when I issue command:
`pip3 install git+https://github.com/PyMySQL/mysqlclient-python.git`
I get error:
```
gcc -pthread -shared -fPIC build/temp.linux-x86_64-3.4/_mysql.o -L/usr/lib64 -lmariadb -lpthread -lz -ldl -lm -lssl -lcrypto -o build/lib.linux-x86_64-3.4/_mysql.cpython-34m.so
    /usr/bin/ld: cannot find -lmariadb
    collect2: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
```

**Comment by 61t** [comment]
@archenroot Thanks you for the trbl, that fixed my issue same in Centos 6 with installation of MariaDB-shared-10.2.14-1.el6 
I installed latest mysqlclient-1.3.12 by the way.

**Comment by 61t** [comment]
@archenroot it's a hard one to connect mysql.h weird issue with MariaDB-shared lib, awesome trbl. You rock.

**Comment by john9393** [comment]
Many thanks Methane ,I had the glitch :"error: 'MYSQL {aka struct st_mysql}' has no member named 'reconnect" with mariadb-10.2.14
and https://github.com/PyMySQL/mysqlclient-python.git SOLVED it.
