### ISSUE TITLE
cursor.executemany multiple insert regression

### ISSUE THREAD

**Issue by romuald** [PyMySQL/mysqlclient-python#178]
Given the following script sample

```python
import MySQLdb

conn = MySQLdb.connect(user='root', db='test')

cur = conn.cursor()
cur.execute('DROP TABLE IF EXISTS bloup');
cur.execute('CREATE TABLE bloup (foo varchar(100), bar varchar(100))')

INSERT = "INSERT INTO bloup(foo, bar) VALUES(%s, %s)"
params = (('foo', 'bar'), ('f2', 'b2'))

cur.executemany(INSERT, params)
cur.execute('COMMIT')
```

Can be checked by using `strace -ewrite python sample.py`

-------

mysqlclient.**1.3.7** will execute one SQL statement (`"INSERT INTO bloup(foo, bar) VALUES\n('foo', 'bar'),\n('f2', 'b2')\n`)

but mysqlclient **1.3.8** and up will execute one SQL statement per tuple (`INSERT INTO bloup(foo, bar) VALUES('foo', 'bar')"`, `INSERT INTO bloup(foo, bar) VALUES('f2', 'b2')"`)

This is impacting setups where the grouping of those inserts is relevant (high latency setup with bulked inserts)

**Comment by methane** [comment]
I made regular expression more strict.
Temporary solution is insert one space between `VALUES` and `(`.

**Comment by romuald** [comment]
Works as a workaround, thank you :)

**Comment by mananshukla6** [comment]
Can an entire dataframe be inserted using cursor.executemany()? I have converted it to string. But it gives me an error while inserting
