### ISSUE TITLE
Connection memory leak without close()

### ISSUE THREAD

**Issue by y-shirai** [PyMySQL/mysqlclient-python#181]
`Connection` object without calling `close()` explicitly will cause memory leak.

### How to reproduce 

```python
import MySQLdb

params = dict(
    host = "...",
    db = "...",
    user = "...",
    passwd = "..."
)

while True:
    conn = MySQLdb.connect(**params)
    # forget conn.close() !!!
```

### Cause?

In [_mysql.c/_mysql_ConnectionObject_dealloc](https://github.com/PyMySQL/mysqlclient-python/blob/master/_mysql.c#L2157), `_mysql_ConnectionObject_clear()` is not called, so it seems that `self->converter` will not be released.

It seems to be a side effect of commit below:
https://github.com/PyMySQL/mysqlclient-python/commit/21a91a2ee20409747e51be4ba4c84e038dbdf6bb#diff-b86fdc88461d69279e84018bca8ea267

### Discussion

I think that calling `close()` explicitly is the best way, but there is room for consideration:
* `Connection` object can be created as context manager (like `with MySQLdb.connect() as cursor:`), but `close()` is not called in `__exit__()`
* `close()` is not found in the [document](https://mysqlclient.readthedocs.io/user_guide.html)

**Comment by methane** [comment]
> In _mysql.c/_mysql_ConnectionObject_dealloc, _mysql_ConnectionObject_clear() is not called, so it seems that self->converter will not be released.

Nice catch.

> Connection object can be created as context manager (like with MySQLdb.connect() as cursor:), but close() is not called in __exit__()

I can't implement it for now, for backward compatibility.

> close() is not found in the document

documented [here](https://www.python.org/dev/peps/pep-0249/#Connection.close).
I don't have motivation to write poor copy of PEP 249 in mysqlclient-python own document.

**Comment by y-shirai** [comment]
Thank you for your quick response.

> I can't implement it for now, for backward compatibility.
Understood.

> documented here.
> I don't have motivation to write poor copy of PEP 249 in mysqlclient-python own document.
I think so too. I will see PEP 249 spec from now on.
