### ISSUE TITLE
debian stretch. no libmysqlclient anymore

### ISSUE THREAD

**Issue by mnach** [PyMySQL/mysqlclient-python#186]
Hi folks!

In debian stretch libmysqlclient replaced by libmariadbclient. [Release notes](https://www.debian.org/releases/stretch/amd64/release-notes/ch-whats-new.html#mariadb-replaces-mysql)

So, after update I have an error:
> ImportError: libmysqlclient.so.18: cannot open shared object file: No such file or directory

I create symlink, but it doesn't helps:
> ImportError: /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18: version `libmysqlclient_18' not found (required by /usr/share/pyenv/versions/3.5.3/envs/pool@3.5.3/lib/python3.5/site-packages/_mysql.cpython-35m-x86_64-linux-gnu.so)

Is there any luck to get this fixed it in future releases?

**Comment by methane** [comment]
I confirmed this library can be used with Debian 9
I suppose you're reusing old binary (via wheel cache).

**Comment by mnach** [comment]
You are right. 
Re-installation with --no-cache-dir flag helps. Library works fine

Thanks!

**Comment by methane** [comment]
You should remove all cache when you upgraded OS.
