### ISSUE TITLE
Error messages with code above 4000 on MariaDB are not displayed

### ISSUE THREAD

**Issue by antoinecarme** [PyMySQL/mysqlclient-python#187]
Hello,

When using a model with too many CTEs, I get the error

***Code: 4003 SQL State: HY000 Too many WITH elements in WITH clause***

when doing an explain but the python client/driver (MySQLdb) does not display it and it displayed an cryptic error (''error totally whack').

A deeper source code analysis shows that the python code expects an error code to be below ***CR_MAX_ERROR***
```
        merr = mysql_errno(&(c->connection));
        if (!merr)
                e = _mysql_InterfaceError;
        else if (merr > CR_MAX_ERROR) {
                PyTuple_SET_ITEM(t, 0, PyInt_FromLong(-1L));
                PyTuple_SET_ITEM(t, 1, PyString_FromString("error totally whack"));
                PyErr_SetObject(_mysql_InterfaceError, t);
                Py_DECREF(t);
                return NULL;
        }
```

but  CR_MAX_ERROR is defined by mariadb as ,
```
../server/include/errmsg.h:#define CR_MAX_ERROR 2999
```

Did this number increase without (mariadb | python-driver) being updated ?

Thanks in advance,

Antoine

PS: I already filed a bug with mariadb here : https://jira.mariadb.org/browse/MDEV-12990

**Comment by methane** [comment]
It's not business of this project.
Link with libmariadbclient.

**Comment by antoinecarme** [comment]
Excellent!!!

 Thanks for the quick response.

**Comment by vuvova** [comment]
It is business of this project, certainly. The check
```c
        else if (merr > CR_MAX_ERROR) {
```
is wrong both for MariaDB and MySQL. There is no client library where CR_MAX_ERROR is the highest possible error number. It is (and always was) highest possible *client error* number. Server error numbers can be both below and above that. In MariaDB and in MySQL.

**Comment by antoinecarme** [comment]
Nice to have the developer of mariadb (@vuvova) discussing with python driver developer (@methane) to help solve my issue.

Cheers !!

**Comment by methane** [comment]
I'm sorry.  I received mail about building almost every day and totally tired.
So I hadn't read your issue carefully.

**Comment by vuvova** [comment]
No problem! Thanks for the quick fix!

**Comment by antoinecarme** [comment]
Guys,

You made my day. Perfect. 

After a git fetch and rebase, reinstall, I now get the real message in my tests ;)

```
TEST_STATUS GradientBoostingClassifier_('db2', 'db2+ibm_db://db:db@localhost:50000/db')_None success None
TEST_STATUS GradientBoostingClassifier_('sqltm', 'sqlite://')_None success None
TEST_STATUS GradientBoostingClassifier_('mssql', 'mssql+pymssql://sa:Micro123@SklearnTestDB/db?charset=utf8&timeout=180')_None success None
TEST_STATUS GradientBoostingClassifier_('pgsql', 'postgresql://db:db@localhost/db?port=5432')_None success None
TEST_STATUS GradientBoostingClassifier_('mysql', 'mysql://db:db@localhost/db')_None failure OperationalError:(_mysql_exceptions.OperationalError) (4003, 'Too many WITH elements in WITH clause') [SQL: "WITH `DT_node_lookup` AS \n(SELECT `ADS`.`index` AS `index`, CASE WHEN (`ADS`.`XD_50` <= -0.4414560794830322
TEST_STATUS GradientBoostingClassifier_('oracle', 'oracle+cx_oracle://db:dba@xe')_None success None

```

Thanks a lot for keeping the quality of mariadb and its python driver at this level.

Regards,

Antoine
