### ISSUE TITLE
OSX - installation failed

### ISSUE THREAD

**Issue by johaven** [PyMySQL/mysqlclient-python#189]
Python version: 3.6.1
Osx: 10.12.5

```python
pip install mysqlclient
Collecting mysqlclient
  Using cached mysqlclient-1.3.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gk/1zzx8k855qj02gb3flvt_tfw0000gn/T/pip-build-_gwy_khc/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/private/var/folders/gk/1zzx8k855qj02gb3flvt_tfw0000gn/T/pip-build-_gwy_khc/mysqlclient/setup_posix.py", line 54, in get_config
        libraries = [dequote(i[2:]) for i in libs if i.startswith('-l')]
      File "/private/var/folders/gk/1zzx8k855qj02gb3flvt_tfw0000gn/T/pip-build-_gwy_khc/mysqlclient/setup_posix.py", line 54, in <listcomp>
        libraries = [dequote(i[2:]) for i in libs if i.startswith('-l')]
      File "/private/var/folders/gk/1zzx8k855qj02gb3flvt_tfw0000gn/T/pip-build-_gwy_khc/mysqlclient/setup_posix.py", line 12, in dequote
        if s[0] in "\"'" and s[0] == s[-1]:
    IndexError: string index out of range

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/gk/1zzx8k855qj02gb3flvt_tfw0000gn/T/pip-build-_gwy_khc/mysqlclient/
```

**Comment by methane** [comment]
Report it to Oracle, not here.

**Comment by johaven** [comment]
Why Oracle ? Setup_posix.py crashed, it does not catch error no ?

**Comment by methane** [comment]
Why don't you search closed issues?
I answered same question many many many times!!!

Since I use Github, many users ask to me very easily.
I must reply them while it's Oracle's fault!
But since Oracle doesn't use Github for issue tracker, no one report it to Oracle!!

Please read closed issues and report it to Oracle's issue tracker.

**Comment by johaven** [comment]
To avoid the issue, a small warning message in the code instead of this crash would be better.
Thank you for your patience, do not forget to take a little holiday ;)

**Comment by methane** [comment]
I'm not God.  I don't show good warning for unexpected wrong output from other components.

I filed bug report: https://bugs.mysql.com/bug.php?id=86971
And I surprised no one filed it already, while I read this issue several times.

So I think no one really want's to fix it.  People just want to ask a question easily.
People feel Github easy and maintainer is free tech support.
