### ISSUE TITLE
Provide manylinux1 wheel distribution on PyPI

### ISSUE THREAD

**Issue by edmorley** [PyMySQL/mysqlclient-python#190]
Hi!

This package is already available in wheel form for Windows, however it would be great to add Linux to that list via the new manylinux1 variant:
https://www.python.org/dev/peps/pep-0513/
https://github.com/pypa/python-manylinux-demo

Many thanks :-)

**Comment by methane** [comment]
https://www.python.org/dev/peps/pep-0513/#security-implications
