### ISSUE TITLE
Not compatible with libssl1.1

### ISSUE THREAD

**Issue by huiyuan1984** [PyMySQL/mysqlclient-python#192]
I have met a problem after installing libssl1.1
```
import MySQLdb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: /usr/local/lib/python2.7/dist-packages/_mysql.so: undefined symbol: OPENSSL_add_all_algorithms_noconf
```
Reproduce steps:

- On a ubuntu 14.04 machine 
- Python 2.7.6

1. echo 'deb http://archive.mariadb.org/mariadb-10.0.29/repo/ubuntu/ trusty main' > /etc/apt/sources.list.d/mariadb.list
2. apt-get -f install --yes --allow-unauthenticated mariadb-server
3. Login as root and show default databases successfully
4. add-apt-repository ppa:ondrej/php 
5. apt-get update
6. apt-get install libssl-dev (version:1.1.0f-2~ubuntu14.04.1+deb.sury.org+1)
7. pip install mysqlclient
8. python -c "import MySQLdb"

**Comment by methane** [comment]
It's not my job.  This library doesn't use libssl directly.
It's your environment problem.

Maybe, old binary wheel is cached and used.
Remove cache directory after you updated some binary which is not ABI compatible. https://stackoverflow.com/a/31807659/3430118
