### ISSUE TITLE
get field name with value together

### ISSUE THREAD

**Issue by alihossein** [PyMySQL/mysqlclient-python#196]
Hi
I want to get field name and value, in query together.
this is my code : 
`db = MySQLdb.connect(config.database_config['host'],config.database_config['username'],config.database_config['password'],"python_test" )`

`cursor = db.cursor()`
`MySQLdb.converters.conversions`

`sql = """SELECT * FROM phone_numbers WHERE active =1 """`
`cursor.execute(sql)`

`numbers_info = cursor.fetchall()`
`db.close()`
but this is only return value of fields in form of tuple !
result : (7, '+999377869282', 1, datetime.datetime(2017, 8, 24, 0, 0))
I want the result of this : {'id':7, 'number':'+999377869282','active': 1,'date' :datetime.datetime(2017, 8, 24, 0, 0)}

**Comment by methane** [comment]
read the document, or go stackoverflow.
This is not user forum.  OSS maintainer is not free user support.
