### ISSUE TITLE
mysqlclient install problem - mac

### ISSUE THREAD

**Issue by IrisYGL** [PyMySQL/mysqlclient-python#205]
**Hi,All
I had the following problems:

 i) modify file: /usr/local/bin/mysql_config (which mysql_config)
origin:
Create options libs="-L$pkglibdir" libs="$libs -l "
modified to
Create options libs="-L$pkglibdir" libs="$libs -lmysqlclient -lssl -lcrypto"

ii)add environment veriables(brew info openssl)
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"

iii)pip3 install mysqlclient

problem details as below:
`Collecting mysqlclient
Using cached mysqlclient-1.3.12.tar.gz
Building wheels for collected packages: mysqlclient
Running setup.py bdist_wheel for mysqlclient ... error
Complete output from command /Users/yuguanglin/anaconda3/bin/python -u -c "import setuptools, tokenize;file='/private/var/folders/ml/xgv9v8gn6kl2l4yj3xmtyxnc0000gn/T/pip-build-z961_iww/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" bdist_wheel -d /var/folders/ml/xgv9v8gn6kl2l4yj3xmtyxnc0000gn/T/tmp8tr14eqmpip-wheel- --python-tag cp36:
running bdist_wheel
running build
running build_py
creating build
creating build/lib.macosx-10.9-x86_64-3.6
copying mysql_exceptions.py -> build/lib.macosx-10.9-x86_64-3.6
creating build/lib.macosx-10.9-x86_64-3.6/MySQLdb
copying MySQLdb/init.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb
copying MySQLdb/compat.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb
copying MySQLdb/connections.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb
copying MySQLdb/converters.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb
copying MySQLdb/cursors.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb
copying MySQLdb/release.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb
copying MySQLdb/times.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb
creating build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
copying MySQLdb/constants/init.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
copying MySQLdb/constants/CLIENT.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
copying MySQLdb/constants/CR.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
copying MySQLdb/constants/ER.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
copying MySQLdb/constants/FLAG.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
copying MySQLdb/constants/REFRESH.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
running build_ext
building 'mysql' extension
creating build/temp.macosx-10.9-x86_64-3.6
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/usr/local/opt/openssl/include -Dversion_info=(1,3,12,'final',0) -D__version=1.3.12 -I/usr/local/Cellar/mysql-connector-c/6.1.11/include -I/Users/yuguanglin/anaconda3/include/python3.6m -c _mysql.c -o build/temp.macosx-10.9-x86_64-3.6/_mysql.o
/usr/bin/clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-rpath,/Users/yuguanglin/anaconda3/lib -L/Users/yuguanglin/anaconda3/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-rpath,/Users/yuguanglin/anaconda3/lib -L/Users/yuguanglin/anaconda3/lib -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -arch x86_64 build/temp.macosx-10.9-x86_64-3.6/_mysql.o -L/Users/yuguanglin/anaconda3/lib -lmysqlclient -lssl -lcrypto -o build/lib.macosx-10.9-x86_64-3.6/_mysql.cpython-36m-darwin.so $ libs
clang: error: no such file or directory: '$'
clang: error: no such file or directory: 'libs'
error: command '/usr/bin/clang' failed with exit status 1

Failed building wheel for mysqlclient
Running setup.py clean for mysqlclient
Failed to build mysqlclient
Installing collected packages: mysqlclient
Running setup.py install for mysqlclient ... error
Complete output from command /Users/yuguanglin/anaconda3/bin/python -u -c "import setuptools, tokenize;file='/private/var/folders/ml/xgv9v8gn6kl2l4yj3xmtyxnc0000gn/T/pip-build-z961_iww/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /var/folders/ml/xgv9v8gn6kl2l4yj3xmtyxnc0000gn/T/pip-cgt6e4dt-record/install-record.txt --single-version-externally-managed --compile:
running install
running build
running build_py
creating build
creating build/lib.macosx-10.9-x86_64-3.6
copying mysql_exceptions.py -> build/lib.macosx-10.9-x86_64-3.6
creating build/lib.macosx-10.9-x86_64-3.6/MySQLdb
copying MySQLdb/init.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb
copying MySQLdb/compat.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb
copying MySQLdb/connections.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb
copying MySQLdb/converters.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb
copying MySQLdb/cursors.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb
copying MySQLdb/release.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb
copying MySQLdb/times.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb
creating build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
copying MySQLdb/constants/init.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
copying MySQLdb/constants/CLIENT.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
copying MySQLdb/constants/CR.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
copying MySQLdb/constants/ER.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
copying MySQLdb/constants/FLAG.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
copying MySQLdb/constants/REFRESH.py -> build/lib.macosx-10.9-x86_64-3.6/MySQLdb/constants
running build_ext
building 'mysql' extension
creating build/temp.macosx-10.9-x86_64-3.6
/usr/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/usr/local/opt/openssl/include -Dversion_info=(1,3,12,'final',0) -D__version=1.3.12 -I/usr/local/Cellar/mysql-connector-c/6.1.11/include -I/Users/yuguanglin/anaconda3/include/python3.6m -c _mysql.c -o build/temp.macosx-10.9-x86_64-3.6/_mysql.o
/usr/bin/clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-rpath,/Users/yuguanglin/anaconda3/lib -L/Users/yuguanglin/anaconda3/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-rpath,/Users/yuguanglin/anaconda3/lib -L/Users/yuguanglin/anaconda3/lib -L/usr/local/opt/openssl/lib -I/usr/local/opt/openssl/include -arch x86_64 build/temp.macosx-10.9-x86_64-3.6/_mysql.o -L/Users/yuguanglin/anaconda3/lib -lmysqlclient -lssl -lcrypto -o build/lib.macosx-10.9-x86_64-3.6/_mysql.cpython-36m-darwin.so $ libs
clang: error: no such file or directory: '$'
clang: error: no such file or directory: 'libs'
error: command '/usr/bin/clang' failed with exit status 1

----------------------------------------
Command "/Users/anaconda3/bin/python -u -c "import setuptools, tokenize;file='/private/var/folders/ml/xgv9v8gn6kl2l4yj3xmtyxnc0000gn/T/pip-build-z961_iww/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /var/folders/ml/xgv9v8gn6kl2l4yj3xmtyxnc0000gn/T/pip-cgt6e4dt-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ml/xgv9v8gn6kl2l4yj3xmtyxnc0000gn/T/pip-build-z961_iww/mysqlclient/

@methane**

**Comment by methane** [comment]
It's not issue of this project.
It's issue of your `mysql_config`.
OSS maintainers are not free tech support.  Ask on other place like Stackoverflow.
