### ISSUE TITLE
Differentiate between char type with binary collation & binary type

### ISSUE THREAD

**Issue by jgao54** [PyMySQL/mysqlclient-python#206]
I'm working on a data pipeline that relies on mysqlclient to run dynamic queries against a mysql db, and then storing the result to a different source. This requires extracting the column types of the query result from cursor description and description_flags. 

An issue occurred when I  have a resulting query contain columns with the following schema:
`foo char(16) COLLATE utf8_bin`

The default converter treats this as `FIELD_TYPE.STRING`, with a description flag of 128, indicating that it's a `BINARY`, which would be identical to the following column schema:

`bar binary(16)`

I was wondering if there is a way to differentiate between these two schemas (in PY2), since I'd want to specify in the destination db that the former is a `CHAR` type while the latter is a `BINARY` type.

A related question is that I ran the same script on both PY2/PY3, they have identical description/flags:
description ('foo', 254, 3, 48, 48, 0, 1) 		description_flags 128
description ('bar', 254, 16, 16, 16, 0, 1) 		description_flags 128

When i iterate through the actual data and print the data type in PY2, I get
foo:    type <class 'str'>
bar:    type <class 'str'>

But in PY3, I get:
foo:    type <class 'str'>
bar:   type <class 'bytes'>

I'm curious that if the data conversion is done using the field_type (both are 254 for STRING) and description flag (128), how is it determined to treat `bar` as `bytes` and `foo` as `str`.

**Comment by methane** [comment]
No way on client side.
Application should know schema.

**Comment by jgao54** [comment]
@methane  Thanks for the prompt response!

What are your thoughts on introducing a new method `_mysql_ResultObject_field_charsetnr` to expose [`charsetnr`](https://dev.mysql.com/doc/refman/5.7/en/c-api-data-structures.html) in the _mysql.c? This field enables one to distinguish BINARY from CHAR, VARBINARY from VARCHAR, and the BLOB types from the TEXT types. I believe it would be a useful attribute for the mysql client (provide the charset). I'd be happy to create a PR on it!

**Comment by methane** [comment]
I don't want to add API.  I want *reduce" APIs.
Use `charset="utf8mb4"` instead.
