### ISSUE TITLE
The install instructions do not cover Windows, and installation on Windows is a pain & fails

### ISSUE THREAD

**Issue by andy-maier** [PyMySQL/mysqlclient-python#207]
I am unable to install mysqlclient on Windows into a virtual Python 2.7 env.

As directed by the issue template text, I have created a question on StackOverflow: https://stackoverflow.com/q/47044149/1424462
It describes the details of the issues I am having.

Because the install instructions (e.g. in README.md) do not cover Windows, and because it is not obvious to me how to overcome these issues, I have opened this issue here.

Maybe we can wait for answers to my SO question, and then add install instructions for Windows to README.md.

**Comment by methane** [comment]
I recommend to upgrade Python 3.6.
Upgrading to Python 3.6 is not so easy in some case. But it's more constructive than
effort for MySQL Connector/C with Python 2.7.

Python 2.7 is very old.  It uses very old MSVC runtime and recent MySQL Connector/C
doesn't support it.  You need to use very old MySQL Connector/C to build with very old MSVC runtime.
It means you can't get recent features including 'utf8mb4', bugfixes including security fixes.

Python 2.7 is supported by Python Core Developers until 2020.
But it not means it's ecosystem is healthy until 2020.

So, if you want to use MySQL from Python, it's time to go Python 3.
