### ISSUE TITLE
Multi instance version of mariadb

### ISSUE THREAD

**Issue by viczem** [PyMySQL/mysqlclient-python#208]
I have a multi instance version of mariadb 10.1.28. When I try to connect to an another port the default 3306 is used instead. This looks like a bug, because of PyMySQL works fine with the same config.

**Comment by methane** [comment]
Complete step for reproduce?
I don't use MariaDB.  So I can't get what you saying.

**Comment by viczem** [comment]
```
# find /usr/lib/systemd/system -name 'mariadb*'
/usr/lib/systemd/system/mariadb@bootstrap.service.d
/usr/lib/systemd/system/mariadb.service
/usr/lib/systemd/system/mariadb@.service
```
create config file `/etc/mysql/my{instancename}.cnf`
start as `systemctl start mariadb@{instancename}.server`

**Comment by methane** [comment]
How to build mysqlclient?
Which libmysqclient.so is used?
Minimum application code to reproduce?

**Comment by viczem** [comment]
1. `pip install mysqlclient`
2. `libmariadbclient 10.1.28`
3. According to the config file above the `general-log-file=/tmp/tmpfs.log`. If to set this option in the `my.cnf` (3306 port) the log file will stores separated in another directory you set. Finally you will have two log files for 3306 and 3308 ports respectively.
```
from MySQLdb import connect
connect(host='localhost', port=3308, user='root', password='password')
```
And now if to see the logs files `Connect   root@localhost as anonymous on` in 3306, but 3308 expected.

**Comment by methane** [comment]
Use '127.0.0.1' instead of 'localhost'.  Otherwise, libmysqlclient (including libmariadbclient)
connect to DB via Unix socket, not TCP.
