### ISSUE TITLE
I can not input emoji like 😄

### ISSUE THREAD

**Issue by zfl420** [PyMySQL/mysqlclient-python#211]
Hier is my code
```
#coding=utf-8
import MySQLdb


#connect() 方法用于创建数据库的连接，里面可以指定参数：用户名，密码，主机等信息。
#这只是连接到了数据库，要想操作数据库需要创建游标。
conn= MySQLdb.connect(
        host ='localhost',
        port = 3306,
        user ='root',
        passwd ='nihao52cons',
        db ='TESTDB',
        )



#通过获取到的数据库连接conn下的cursor()方法来创建游标。
cur = conn.cursor()

#一次插入多条记录
sqli="insert into aaad values(%s,%s,%s,%s,%s,%s,%s,%s,%s)"
cur.execute(sqli,('3','Huhu','2 year 1 class','7','7','7','7','7','99999😄9'))

cur.close()
conn.commit()
conn.close()
```

![20171123151142037668348.png](http://orw0hbikt.bkt.clouddn.com/20171123151142037668348.png)

**Comment by shangdahao** [comment]
utf8 编码无法保存emoji，需要 utf8mb4，可以这样转换编码

`ALTER DATABASE dbname CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;`

**Comment by methane** [comment]
Here is not user forum.  Go elsewhere.

**Comment by akx** [comment]
For what it's worth, though, this is likely caused by your MySQL table not being in the `utf8mb4` encoding. Misleading as it is, the `utf8` encoding actually can not encode the full UTF-8 range.
