### ISSUE TITLE
Support MySQL 5.7x JSON columns

### ISSUE THREAD

**Issue by foresmac** [PyMySQL/mysqlclient-python#213]
Looking through the code, I don't see any converters for MySQL [JSON columns](https://dev.mysql.com/doc/refman/5.7/en/json.html). It looks as easy as adding a line [here](https://github.com/PyMySQL/mysqlclient-python/blob/master/MySQLdb/converters.py#L95) and adding a `json.loads`-type function in the converters, but that also sounds like famous last words. I'll see what I can get working without explicit JSON column support, and see what it would take to add support in if possible.

**Comment by methane** [comment]
* It is backward incompatible.
* When inserting or updating, you must use JSON string.  So return JSON string on SELECT seems OK
