### ISSUE TITLE
Cursors leak on exception in python 3.3

### ISSUE THREAD

**Issue by saaj** [PyMySQL/mysqlclient-python#22]
Python 2.7, 3.4 and pypy2 2.4 (if the same GC API makes sense of it) are fine.

```
import gc
import MySQLdb

#gc.set_debug(gc.DEBUG_UNCOLLECTABLE)

def test():
  conn = MySQLdb.connect(user = 'guest')
  try:
    conn.cursor().execute('foo bar') 
  except:
    pass

if __name__ == '__main__':
  test()
  gc.collect()
  if gc.garbage:
    print(gc.garbage)
    print(gc.get_referrers(gc.garbage[0]))
  else:
    print('OK')
```

On 3.3 output is:
```
[<MySQLdb.cursors.Cursor object at 0x7f90a162cd90>]
[[<MySQLdb.cursors.Cursor object at 0x7f90a162cd90>], <frame object at 0x19d7b70>, <frame object at 0x192ce80>, <frame object at 0x19231a0>]
```

I don't have an idea how the cursor and the frames have managed to produce a reference cycle, neither how [new exception semantics](https://www.python.org/dev/peps/pep-3110/#semantic-changes) come into play, but it definitely has something to do with presence of `__del__` in cursor. Though PyMySQL from the Cheese Shop which still has `__del__` (removed in #287) is fine.

**Comment by methane** [comment]
Cursor should be `close()`ed when exception occurred.

**Comment by saaj** [comment]
Yes, explicitly closing the cursor helps. I've found that the cycle is in `cursor.messages`, and `cursor.close` calls `cursor.nextset` which purges them. Even though warnings are also stored in `cursor.messages` they don't make the cursor leak.

In general when all other supported Python versions and PyMySQL don't have this issue it makes sense to keep the behaviour consistent. Buffered cursors don't have any resources then need explicit closing (as far as I know) and since the base cursor implements `__del__`, reference cycles shouldn't occur in any expected flow.

**Comment by saaj** [comment]
So far so good, thank you :-)
