### ISSUE TITLE
Commands out of sync error

### ISSUE THREAD

**Issue by sharifzadesina** [PyMySQL/mysqlclient-python#222]
Hi

Run this SQL command using `mysqlclient`:

```sql
CREATE TABLE IF NOT EXISTS `test`
(
    `id` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY
)
ENGINE=InnoDB;
``` 

for the first call it will run properly, but from the second call, it will rise `Commands out of sync; you can't run this command now` error.

I run it like this:

```python
db = MySQLdb.connect([...])
db.cursor().execute(command)
```
NOTE: calling with `cursor.close()`, `db.commit()` or etc, also have the same result.

OK, now try this command:

```sql
SELECT 1; -- this line will solve the error!

CREATE TABLE IF NOT EXISTS `test`
(
    `id` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY
)
ENGINE=InnoDB;
``` 

As you see the problem solved!
I've tested this also on other drivers like `mysqljs/mysql`, this only happens on your driver.
It seems it is cause we use `IF NOT EXISTS` clause and MySQL from second call cause of existence of the table, doesn't do anything and `mysqlclient` doesn't fetch any result so MySQL rises this error.

**Comment by methane** [comment]
This project is just a wrapper over libmysqlclient.  This doesn't implement protocol directly.
So it's unlikely issue of this project.

At least, you need to report precise server and client version, and options used for `connect()`.

**Comment by methane** [comment]
And what version of mysqlclient-python do you use?
I can't reproduce it with latest version.
But #101 may fixed it in last year.

**Comment by sharifzadesina** [comment]
@methane I am using last version from pip, mysqlclient 1.3.12
MySQL version: 5.7.19
Connection:
```python
MySQLdb.connect(
     cursorclass=MySQLdb.cursors.DictCursor,
     host="localhost",
     user="[...]",
     passwd="[...]",
     db="[...]"
 )
```

**Comment by methane** [comment]
I used MySQL 5.7.20 (same libmysqlclient version) and I can't reproduce.
Could you upload complete code to reproduce to gist?

**Comment by methane** [comment]
```
$ python
Python 3.6.4 (default, Jan  6 2018, 11:51:59)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import MySQLdb
>>> sql = """
... CREATE TABLE IF NOT EXISTS `test`
... (
...     `id` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY
... )
... ENGINE=InnoDB;
... """
>>> con = MySQLdb.connect(user='root', db='test')
>>> cur = con.cursor(MySQLdb.cursors.DictCursor)
>>> cur.execute(sql)
0
>>> cur.execute(sql)
__main__:1: Warning: (1050, "Table 'test' already exists")
0
>>> cur.execute(sql)
0
>>> cur.execute(sql)
0
>>> cur.execute(sql)
0
>>> cur.execute("SELECT 1,2,3")
1
>>> cur.fetchone()
{'1': 1, '2': 2, '3': 3}
>>> MySQLdb.__version__
'1.3.12'
```

```
$ otool -L _mysql.cpython-36m-darwin.so
_mysql.cpython-36m-darwin.so:
	/usr/local/opt/mysql/lib/libmysqlclient.20.dylib (compatibility version 20.0.0, current version 20.0.0)
	/usr/lib/libssl.35.dylib (compatibility version 36.0.0, current version 36.0.0)
	/usr/lib/libcrypto.35.dylib (compatibility version 36.0.0, current version 36.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```

At least, your issue is not issue of this project.
If you can reproduce, report it on bugs.mysql.com.
