### ISSUE TITLE
Type of escape_string's return value, str or unicode? in Python 3

### ISSUE THREAD

**Issue by menduo** [PyMySQL/mysqlclient-python#224]
Hi,  about the type of  `escape_string`'s return value:

`mysqlclient` returns `bytes`, `pymysql` will return `str`. 

Another side, MySQLdb1 returns `str` in Python 2 and `unicode` in Python 3(see https://github.com/farcepest/MySQLdb1/blob/master/_mysql.c#L1112)

The question is: 

Which one is  more appropriate? In my case(Python 3 with `mysqlclient`, many none ascii characters ), I convert the `bytes` to `str`.

Any suggestions? or is it a bug of `mysqlclient`?

Version info:
- mysqlclient: 1.3.12
- pymysql: 0.8.0

Thanks.

**Comment by methane** [comment]
It is not a bug, but an implementation detail.
Not using it is best.  It is not in DB-API 2.0.
