### ISSUE TITLE
namedtuple support?

### ISSUE THREAD

**Issue by ko-han** [PyMySQL/mysqlclient-python#227]
Sqlite3 provides a way for the user to define "row factories". These row factories take the cursor and the tuple row and can return whatever type of object it wants. for example:
```
import sqlite3
import collections

LanguageRecord = collections.namedtuple('LanguageRecord', 'id name creation_date')
def namedtuple_factory(cursor, row):
    return LanguageRecord(*row)

con = sqlite3.connect(":memory:")
con.row_factory = namedtuple_factory
cur = con.cursor()
cur.execute("select 1,2,3")
print(cur.fetchone())
```
mysqlclinet seems provide a cursorclass options, but can't find any document. and it didn't support namedtuple.
Please give some advice to  define a new cursorclass.

**Comment by methane** [comment]
It's possible to customize cursor, but I don't like it.
`map` is much simple.

```py
cursor.execute("select 1,2,3")
records = map(LanguageRecord, cursor)
```
