### ISSUE TITLE
escape_string() broken with Python 2.x

### ISSUE THREAD

**Issue by jmuchemb** [PyMySQL/mysqlclient-python#23]
$ python -c 'import MySQLdb; print(MySQLdb.escape_string(b"foo"))'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    TypeError: must be impossible<bad format char>, not str
    $ python3 -c 'import MySQLdb; print(MySQLdb.escape_string(b"foo"))'
    b'foo'

Tested on Debian with version 1.3.4-1 (packaged in experimental), MariaDB 10.0.16-1 and Python 2.7.9-1
I also tried 1.3.5 but it's not better.

**Comment by methane** [comment]
Good catch!
