### ISSUE TITLE
Should set MYSQL_OPT_PROTOCOL option

### ISSUE THREAD

**Issue by axot** [PyMySQL/mysqlclient-python#233]
Same problem as describe in https://sourceforge.net/p/mysql-python/patches/60

Example code:

```
MySQLdb.connect(host=''localhost, port=3306)
```

I got the follow result.

> ('MySQLdb.Error: ', OperationalError(2002, "Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)"))

**Comment by methane** [comment]
It's consistent with MySQL tools:

```
$ mysql -hlocalhost -P3306
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
```

**Comment by methane** [comment]
You should use `127.0.0.1` or `::1`.  It's well known pitfall of MySQL.
