### ISSUE TITLE
Can't pass field name as a parameter to execute.

### ISSUE THREAD

**Issue by mndhkr** [PyMySQL/mysqlclient-python#234]
Hi,
I was trying to pass a field name as a parameter to the execute method,
as: c.execute("UPDATE " + table + " SET " + fields + " WHERE %s = %s;", (id_name, id_value)).

I got no errors, but the record didn't get updated on the database.

Is this the desired behavior?

Thank you.

**Comment by methane** [comment]
It's intended behaviour, and here is not Q&A site.
Go stackoverflow.
