### ISSUE TITLE
pip3.6 install mysqlclient fails on centos7

### ISSUE THREAD

**Issue by itsvks** [PyMySQL/mysqlclient-python#237]
Loaded plugins: fastestmirror
  Loading mirror speeds from cached hostfile
   * base: del-mirrors.extreme-ix.org
   * epel: del-mirrors.extreme-ix.org
   * extras: del-mirrors.extreme-ix.org
   * ius: hkg.mirror.rackspace.com
   * updates: del-mirrors.extreme-ix.org
  Package python36u-pip-9.0.1-1.ius.centos7.noarch already installed and latest version
  Nothing to do
  (mysite) [vagrant@localhost ~]$ sudo yum -y install python36u-devel
  Loaded plugins: fastestmirror
  Loading mirror speeds from cached hostfile
   * base: del-mirrors.extreme-ix.org
   * epel: del-mirrors.extreme-ix.org
   * extras: del-mirrors.extreme-ix.org
   * ius: hkg.mirror.rackspace.com
   * updates: del-mirrors.extreme-ix.org
  Package python36u-devel-3.6.5-1.ius.centos7.x86_64 already installed and latest version
  Nothing to do
  (mysite) [vagrant@localhost ~]$ pip3.6 install mysqlclient
  Collecting mysqlclient
    Using cached https://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz
  Building wheels for collected packages: mysqlclient
    Running setup.py bdist_wheel for mysqlclient ... error
    Complete output from command /home/vagrant/venv/mysite/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vnu2o_3f/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-wqio7j16 --python-tag cp36:
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    copying _mysql_exceptions.py -> build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/MySQLdb
    copying MySQLdb/__init__.py -> build/lib.linux-x86_64-3.6/MySQLdb
    copying MySQLdb/compat.py -> build/lib.linux-x86_64-3.6/MySQLdb
    copying MySQLdb/connections.py -> build/lib.linux-x86_64-3.6/MySQLdb
    copying MySQLdb/converters.py -> build/lib.linux-x86_64-3.6/MySQLdb
    copying MySQLdb/cursors.py -> build/lib.linux-x86_64-3.6/MySQLdb
    copying MySQLdb/release.py -> build/lib.linux-x86_64-3.6/MySQLdb
    copying MySQLdb/times.py -> build/lib.linux-x86_64-3.6/MySQLdb
    creating build/lib.linux-x86_64-3.6/MySQLdb/constants
    copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
    copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
    copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
    copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
    copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
    copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
    copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
    running build_ext
    building '_mysql' extension
    creating build/temp.linux-x86_64-3.6
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Dversion_info=(1,3,12,'final',0) -D__version__=1.3.12 -I/usr/include/mysql -I/usr/include/python3.6m -c _mysql.c -o build/temp.linux-x86_64-3.6/_mysql.o -m64
    _mysql.c: In function ‘_mysql_ConnectionObject_ping’:
    _mysql.c:1894:3: error: unknown type name ‘my_bool’
       my_bool recon = reconnect;
       ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
    Failed building wheel for mysqlclient
    Running setup.py clean for mysqlclient
  Failed to build mysqlclient
  Installing collected packages: mysqlclient
    Running setup.py install for mysqlclient ... error
      Complete output from command /home/vagrant/venv/mysite/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vnu2o_3f/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4shgu0qx/install-record.txt --single-version-externally-managed --compile --install-headers /home/vagrant/venv/mysite/include/site/python3.6/mysqlclient:
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.6
      copying _mysql_exceptions.py -> build/lib.linux-x86_64-3.6
      creating build/lib.linux-x86_64-3.6/MySQLdb
      copying MySQLdb/__init__.py -> build/lib.linux-x86_64-3.6/MySQLdb
      copying MySQLdb/compat.py -> build/lib.linux-x86_64-3.6/MySQLdb
      copying MySQLdb/connections.py -> build/lib.linux-x86_64-3.6/MySQLdb
      copying MySQLdb/converters.py -> build/lib.linux-x86_64-3.6/MySQLdb
      copying MySQLdb/cursors.py -> build/lib.linux-x86_64-3.6/MySQLdb
      copying MySQLdb/release.py -> build/lib.linux-x86_64-3.6/MySQLdb
      copying MySQLdb/times.py -> build/lib.linux-x86_64-3.6/MySQLdb
      creating build/lib.linux-x86_64-3.6/MySQLdb/constants
      copying MySQLdb/constants/__init__.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
      copying MySQLdb/constants/CLIENT.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
      copying MySQLdb/constants/CR.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
      copying MySQLdb/constants/ER.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
      copying MySQLdb/constants/FIELD_TYPE.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
      copying MySQLdb/constants/FLAG.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
      copying MySQLdb/constants/REFRESH.py -> build/lib.linux-x86_64-3.6/MySQLdb/constants
      running build_ext
      building '_mysql' extension
      creating build/temp.linux-x86_64-3.6
      gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Dversion_info=(1,3,12,'final',0) -D__version__=1.3.12 -I/usr/include/mysql -I/usr/include/python3.6m -c _mysql.c -o build/temp.linux-x86_64-3.6/_mysql.o -m64
      _mysql.c: In function ‘_mysql_ConnectionObject_ping’:
      _mysql.c:1894:3: error: unknown type name ‘my_bool’
         my_bool recon = reconnect;
         ^
      error: command 'gcc' failed with exit status 1
      
      ----------------------------------------
  Command "/home/vagrant/venv/mysite/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vnu2o_3f/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-4shgu0qx/install-record.txt --single-version-externally-managed --compile --install-headers /home/vagrant/venv/mysite/include/site/python3.6/mysqlclient" failed with error code 1 in /tmp/pip-install-vnu2o_3f/mysqlclient/

**Comment by methane** [comment]
It's repeatedly reported, and fixed already in master.
And you don't report even you're using MySQL 8.

**Comment by magestree** [comment]
well... It looks quite impossible to install mysqlclient on CentOS 7
