### ISSUE TITLE
MySQL 8.0 support on Windows

### ISSUE THREAD

**Issue by methane** [PyMySQL/mysqlclient-python#238]
`mysqlclient.lib` uses OpenSSL.
We should use ssleay32.dll and libeay32.dll in `<MySQL 8 install dir>/bin`.

How can I create Windows binary wheel?  Copy these dll files,,, to where?

---

mysql-connector-python wheel installs `libeay32.dll`, `libmysql.dll` and `ssleay32.dll` under
`site-packages`.
We put `_mysql.<tag>.pyd` into `site-packages`.  If we bundle these dlls, mysqlclient conflicts
against mysql-connector-python.

If user installed both of mysqlclient and mysql-connector-python, and uninstall one, dlls are removed.

Maybe, we need to move `_mysql.pyd` into `MySQLdb` before next release?

**Comment by AlexVilla** [comment]
Any news about it?

**Comment by methane** [comment]
No.  Use MySQL Connector/Python instead.
