### ISSUE TITLE
I have tried Everything please help me install mysqlclient

### ISSUE THREAD

**Issue by vsag96** [PyMySQL/mysqlclient-python#247]
The Error:
running install
running bdist_egg
running egg_info
writing mysqlclient.egg-info/PKG-INFO
writing dependency_links to mysqlclient.egg-info/dependency_links.txt
writing top-level names to mysqlclient.egg-info/top_level.txt
reading manifest file 'mysqlclient.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'mysqlclient.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying MySQLdb/release.py -> build/lib.linux-x86_64-3.6/MySQLdb
running build_ext
building '_mysql' extension

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Dversion_info=(1,3,12,'final',0) -D__version__=1.3.12 -I/usr/include/mysql -I/usr/include/python3.6m -c _mysql.c -o build/temp.linux-x86_64-3.6/_mysql.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-Bsymbolic-functions -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/_mysql.o -lmysqlclient -lpthread -lm -lrt -lssl -lcrypto -ldl -o build/lib.linux-x86_64-3.6/_mysql.cpython-36m-x86_64-linux-gnu.so

/usr/bin/x86_64-linux-gnu-ld: cannot find -lssl
/usr/bin/x86_64-linux-gnu-ld: cannot find -lcrypto
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by vsag96** [comment]
Okay To give you an idea here's everything I've done.

I have got this error saying mysql_config not found? Then I've downloaded the source and changed the .cfg file to the path that contains the mysql_config File.

I have all the dependencies installed.

python3-dev, sql headers.

Please what does this mean?

**Comment by methane** [comment]
"cannot find -lssl" and "cannot find -lcrypto" means linker can't find OpenSSL libraries.
Every linux C developer must be able to answer this question.
Don't use issue tracker for asking such a easy question.

https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.uoo6bjv13

**Comment by vsag96** [comment]
You lot,need to be less hostile towards people which part of that error says that I have to install Openssl libraries and only god knows what "Every Linux C developer" means. I have read every stackoverflow,askUbuntu post before posting the issue. This was my last resort.

**Comment by methane** [comment]
> You lot,need to be less hostile towards people

Have you read my article?  
There are only one active maintainer, and there are thousands of users.
And writing English message is harder than writing C or English to me.
And answering to such easy question is not pleasant task to me.

Please note that OSS maintainers are not paid user support.
Bothering OSS maintainer may leads "burn-out" and project will not be maintained.

>  only god knows what "Every Linux C developer" means.

Only god?  Every C programmer knows what "linker" is and read the error message.

>  I have read every stackoverflow,askUbuntu post before posting the issue.

If so, you must write link to the posts you couldn't find answer, at least.

> This was my last resort.

When I Google  "cannot find -lssl", Google shows me [this Stackoverflow question].
Google will be your friend.
