### ISSUE TITLE
NULL C exception causes segfault in python

### ISSUE THREAD

**Issue by olaure** [PyMySQL/mysqlclient-python#248]
It happens that when i tried connecting to a server refusing the connection, my python interpreter crashes when accessing the subsequent OperationalError arguments.
```
import MySQLdb
try:
    client = MySQLdb.connect('127.0.0.4')
except Exception as err:
    print(err)
    print(err.args[1])
```
This crashes after displaying the error as `(1130, <NULL>)`.

After investigating, it appears there is a case at the initialisation of the connection where the error raised can have a NULL argument, [in this part of the C code](https://github.com/PyMySQL/mysqlclient-python/blob/92cd53289376dbd1eff90a94b2810c4641205d5f/_mysql.c#L304).

I didn't have the time to investigate further what should be passed as argument to the error instanciation, but it breaks python quite hard.

**Comment by methane** [comment]
> After investigating, it appears there is a case at the initialisation of the connection where the error raised can have a NULL argument, in this part of the C code.

In this case, `_mysql_server_init_done` should be zero and such tuple shouldn't be created.
See https://github.com/PyMySQL/mysqlclient-python/blob/92cd53289376dbd1eff90a94b2810c4641205d5f/_mysql.c#L110

Need more information to reproduce your error.

**Comment by methane** [comment]
BTW, you can google "1130 MySQL".
