### ISSUE TITLE
caching_sha2_password

### ISSUE THREAD

**Issue by OrangeDog** [PyMySQL/mysqlclient-python#252]
This package doesn't seem to support the new default authentication method.

```
  File "venv\lib\site-packages\MySQLdb\__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "venv\lib\site-packages\MySQLdb\connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2059, "Authentication plugin 'caching_sha2_password' cannot be loaded: The specified module could not be found.\r\n")
```

I'm using MySQL 8.0.11 and mysqlclient 1.3.12 on Windows, via the prebuilt wheel.

**Comment by methane** [comment]
I don't provide windows wheel with new libmysqlclient because it's difficult to provide,
and conflicts with mysql-connectors-python.

**Comment by OrangeDog** [comment]
So it should work if built locally then?
