### ISSUE TITLE
 Mac: pip install mysqlclient. Errors: Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-nyzzrlh_/mysqlclient/

### ISSUE THREAD

**Issue by mikechen66** [PyMySQL/mysqlclient-python#259]
**IF YOU HAVE SOME TROUBLE, IT'S MAY NOT ISSUE OF THIS PROJECT. GO STACKOVERFLOW!!!**

If you failed to build, go Stackoverflow.
If you failed to install, go Stackoverflow.
If you failed to connect to database, go Stackoverflow.

FYI, MySQL Connector/C 6.1.10 has bug. see https://github.com/PyMySQL/mysqlclient-python/issues/169#issuecomment-299778504

Only when If you're sure it's PyMySQL's issue, report the complete steps to reproduce, from creating database.

I don't have time to investigate your issue from an incomplete code snippet.

See also: https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde

**Comment by mikechen66** [comment]
For the issue of mysqlclient installation failed in macOS, it seems to have a chained problems. While fix one issue, another issue jump out of the box. Hope that it will be debugged. Please see the digged problems at the Github weblink. 

https://github.com/PyMySQL/mysqlclient-python/issues/169

Original Issue: 
"python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-nyzzrlh_/mysqlclient/ #259

**Comment by methane** [comment]
This seems not issue report, but just a spam.
