### ISSUE TITLE
Problem building from source against MariaDB 10.2.11

### ISSUE THREAD

**Issue by edmondac** [PyMySQL/mysqlclient-python#261]
I am building mysqlclient 1.3.13 from source against Python 3.6.3 and MariaDB 10.2.11.

It fails to build with an error about libNone.a.

I tracked this down to `client` not being set properly in `setup_posix.py`

Here's a patch which fixes it. If you'd prefer this as a PR then I'm happy to make one, but I wanted to check that I wasn't doing anything silly first...
```
--- setup_posix.py.orig 2018-06-27 12:17:09.000000000 +0100
+++ setup_posix.py      2018-08-29 15:15:21.941166016 +0100
@@ -75,13 +75,18 @@
 
     # properly handle mysql client libraries that are not called libmysqlclient
     client = None
-    CLIENT_LIST = ['mysqlclient', 'mysqlclient_r', 'mysqld',
+    CLIENT_LIST = ['mysqlclient', 'mysqlclient_r', 'mysqld', 'mariadb',
                    'perconaserverclient', 'perconaserverclient_r']
     for c in CLIENT_LIST:
         if c in libraries:
             client = c
             break
 
+    if client == 'mariadb':
+        client = 'mariadbclient'
+    if client is None:
+        raise ValueError("Couldn't identify mysql client library")
+
     if static:
         extra_objects.append(os.path.join(library_dirs[0], 'lib%s.a' % client))
         if client in libraries:

```

**Comment by methane** [comment]
Did you use `--static` option?
Does MariaDB client library support static linking?  Is there any document about it?

**Comment by edmondac** [comment]
Yes - using static. The library is `mariadbclient.a`

This does seem to work - at least it can connect happily to our database.

**Comment by methane** [comment]
OK, please send a PR.
