### ISSUE TITLE
No binary distribution for 1.3.13 on Windows

### ISSUE THREAD

**Issue by beruic** [PyMySQL/mysqlclient-python#262]
I upgraded our project to 1.3.13 recently. Now I get complaints from everyone trying to run on Windows, because the compile of mysqlclient fails.

I assume it is a mistake that there no binary distribution for Windows for this version, like there is for the previous ones.

**Comment by methane** [comment]
https://github.com/PyMySQL/mysqlclient-python/issues/252#issuecomment-402694245
