### ISSUE TITLE
Signal sent while query is in progress will freeze process.

### ISSUE THREAD

**Issue by vladmunteanu** [PyMySQL/mysqlclient-python#279]
First, my respects and congratulations for keeping this project alive!
I apologize in advance if this issue is actually related to the underlying C library.

My colleague @octava25 and I have identified and reproduced an old and hard-to-track issue with our production servers:
Randomly, after receiving a signal used to reload configuration files, our processes would block, forcing us to kill that interpreter process and restart it.

We have further identified this problem as coming from the MySQLdb package. 
In order to reproduce the bug, one has to:

1. In <Shell#1>, run the following code:
```
import MySQLdb
import signal

db_host = ""
db_user = ""
db_passwd = ""
db_name = ""

def sig_handler(signum, frame):
    print("In sig handler")


signal.signal(signal.SIGCONT, sig_handler)


def main():
    print("start")
    connection = MySQLdb.connect(host=db_host, user=db_user, passwd=db_passwd, db=db_name)
    connection.cursor().execute("SELECT SLEEP(15)")
    print("end")


if __name__ == "__main__":
    main()
```

2. While the above code is executing, open <Shell#2> and send `SIGCONT` to the Python process started in <Shell#1>. We have tested `SIGHUP` and `SIGUSR1` with the same results.
3. Notice that the process started in <Shell#1> will never finish.

**Weirdly, the above behavior can not be reproduced if a signal handler isn't added.**

**Comment by methane** [comment]
I can reproduce it on Ubuntu 18.04.
After playing with gdb several hours, I found it's YaSSL bug.

I found exiting issue reported.
https://bugs.mysql.com/bug.php?id=88428

Nothing I can do about it.

**Comment by vladmunteanu** [comment]
Interesting, I'll try compiling libmysqlclient with openssl to give that a try.

Nonetheless, I think the README should state something about this, since this library is used intensely by python services that may rely on signals. Happy to submit a PR with this if you see it appropriate.

**Comment by methane** [comment]
Do you mean this README should include all important bugs of libmysqlclient and libmariadbclient?  I can not maintain!

Please send such proposal to MySQL team.
Ruby and Rust and C++ application may use signals too.
