### ISSUE TITLE
In python 3, authentication plugin cannot be loaded

### ISSUE THREAD

**Issue by piyush4793** [PyMySQL/mysqlclient-python#288]
django.db.utils.OperationalError: (2059, "Authentication plugin 'caching_sha2_password' cannot be loaded: The specified module could not be found.\r\n")

I am getting this error when using mysqlclient in my django project.
I think msqlclient doesnot support caching_sha2_password encryption on passwords and that's why failing to work with MySQL 8.0 

Any help regarding this issue will be appreciated.

**Comment by methane** [comment]
**[You must not ask a question on issue tracker](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.hdf6lpk11)**
