### ISSUE TITLE
with mariadb-connector-c mysql_clear_password plugin failing due to bad path

### ISSUE THREAD

**Issue by sooslaca** [PyMySQL/mysqlclient-python#289]
hi developers,

When try to connect to a db with shared plugins like mysql_clear_password.so I get
`_mysql_exceptions.OperationalError: (2006, 'Plugin mysql_clear_password could not be loaded: Error loading shared library lib/mariadb/plugin/mysql_clear_password.so: No such file or directory')`

It might/might not be an issue with mysqlclient, but normal `mysql` utility works well so I assume underlying libs are ok.

OS is Alpine 3.8 on docker.

STEPS TO REPRODUCE:
```
docker run -it python:alpine3.8 /bin/sh
apk update
apk add alpine-sdk mariadb-connector-c mariadb-connector-c-dev
pip install mysqlclient

vi /x
------PASTE THE BELOW----
#!/usr/bin/env python

import _mysql

db=_mysql.connect(db="mydb", host="remote.example.com", user="user", passwd="password")

------END PASTE ----
chmod 755 /x
/x
```
If all goes well you get empty output. If it fails (like for me) you get:
```
Traceback (most recent call last):
  File "./x", line 5, in <module>
    db=_mysql.connect(db="mydb", host="remote.example.com", user="user", passwd="password") _mysql_exceptions.OperationalError: (2059, 'Plugin mysql_clear_password could not be loaded: Error loading shared library lib/mariadb/plugin/mysql_clear_password.so: No such file or directory')
```
the lib exists at
```
@a63e69f065a7:/usr$ ls -la /usr/lib/mariadb/plugin/mysql_clear_password.so
-rwxr-xr-x    1 root     root          5888 Jun 12 13:24 /usr/lib/mariadb/plugin/mysql_clear_password.so
```

As it seems from the error message it tries to load from `lib/mariadb/plugin/mysql_clear_password.so`
This looked a relative path for me so the interesting finding is that if you cd to /usr before run the script it works.

```
cd /usr
@a63e69f065a7:/usr$ /x
@a63e69f065a7:/usr$
``` 
(empty output means it's ok)

Do you have any idea what could set the path wrong and how to fix it?

Thanks for the help in advance

**Comment by methane** [comment]
I don't know.  I have no idea.
Please ask to MariaDB, not me.

**Comment by sooslaca** [comment]
I hear you.
Would you mind adding option after mysql_init() in [_mysql.c](https://github.com/PyMySQL/mysqlclient-python/blob/master/_mysql.c#L589)?

`mysql_options(&(self->connection), MYSQL_PLUGIN_DIR, "/usr/lib/mariadb/plugin"); `

That's fixing the issue.

For reference I opened https://jira.mariadb.org/projects/CONC/issues/CONC-376?filter=allopenissues

**Comment by methane** [comment]
Why don't you use config file?

```~/.my.cnf
# ~/.my.cnf or other effective config files.
[client]
plugin_dir = /usr/lib/mariadb/plugin
```

**Comment by sooslaca** [comment]
Thanks for the idea, tried, negative results

```
/ # cat /etc/my.cnf
[client]
plugin_dir = /usr/lib/mariadb/plugin
/ # chmod 755 /etc/my.cnf
/ # /x
Traceback (most recent call last):
  File "/x", line 5, in <module>
    db=_mysql.connect(db="demonhost_postfix", host="mariadb.services.dh", user="demonhost_postfix", passwd="6Fu2TmKuXMyDNzHCfANf")
_mysql_exceptions.OperationalError: (2059, 'Plugin mysql_clear_password could not be loaded: Error loading shared library lib/mariadb/plugin/mysql_clear_password.so: No such file or directory')
/ # cat ~/my.cnf
[client]
plugin_dir = /usr/lib/mariadb/plugin
/ # chmod 755 ~/my.cnf
/ # /x
Traceback (most recent call last):
  File "/x", line 5, in <module>
    db=_mysql.connect(db="demonhost_postfix", host="mariadb.services.dh", user="demonhost_postfix", passwd="6Fu2TmKuXMyDNzHCfANf")
_mysql_exceptions.OperationalError: (2059, 'Plugin mysql_clear_password could not be loaded: Error loading shared library lib/mariadb/plugin/mysql_clear_password.so: No such file or directory')
```

**Comment by methane** [comment]
How about "MARIADB_PLUGIN_DIR" environment variable?

**Comment by sooslaca** [comment]
awesome @methane !!!! That worked :)

```
/ # export MARIADB_PLUGIN_DIR=/usr/lib/mariadb/plugin
/ # /x
/ #
```

Let's close this one then. Thank you
