### ISSUE TITLE
Suggestions: Provide wheels for ubuntu and MacOS

### ISSUE THREAD

**Issue by ebertti** [PyMySQL/mysqlclient-python#299]
Hi, just a suggestion.

You can provide a wheels for ubuntu, centos and others OS, just using a travis-ci our appveyor

Using binaries to compile on docker is too annoying.

Like psycopg does.

**Comment by methane** [comment]
https://github.com/PyMySQL/mysqlclient-python/search?q=wheel&type=Issues
