### ISSUE TITLE
Test failures after upgrading Django app to mysqlclient 1.3.14

### ISSUE THREAD

**Issue by edmorley** [PyMySQL/mysqlclient-python#303]
Hi 

### STR:
1. Have a Django 1.11 app whose tests make use of [CaptureQueriesContext](https://github.com/django/django/blob/1.11.17/django/test/utils.py#L621-L654), such as:
    - https://github.com/mozilla/treeherder/blob/d36bb8ab7644d3afe4b21e2b283c77e51aca1a15/tests/model/test_bugscache.py#L151-L179
2. Upgrade the `mysqlclient` used by that app from 1.3.13 to 1.3.14, eg:
    - mozilla/treeherder/pull/4342
3. Run test suite (either locally or on Travis)

### Expected:
No test failures after upgrading, since:
- it was a minor release
- there was no mention of removing `_last_executed` in the changelog

### Actual:
Test failures, eg:

```
        with CaptureQueriesContext(connection) as context:
            Bugscache.search(search_term)
    
            search_query = get_search_query(context.captured_queries[0]['sql'])
>           assert search_query
E           AssertionError: assert ''
```
(https://travis-ci.org/mozilla/treeherder/jobs/463284994#L605)

Whilst Django's handling has been updated for Django 2.1+, this leaves Django 1.11 (LTS) and Django 2.0 incompatible with latest mysqlclient.

If restoring `_last_executed` ends up being wontfix, please can the changelog be updated to mention the removal (and if possible a reference to say Django <2.1 users should not update)?

Many thanks :-)

Refs:
- https://github.com/PyMySQL/mysqlclient-python/pull/283#issuecomment-444562762
- https://code.djangoproject.com/ticket/30013
- django/django/pull/10726
- django/django/pull/10727

**Comment by methane** [comment]
> ### Expected:
> No test failures after upgrading, since:
> 
> * it was a minor release
> * there was no mention of removing `_last_executed` in the changelog

When using private member, both are expected.

**Comment by edmorley** [comment]
> When using private member, both are expected.

Yeah is fair :-) Thank you for the changelog update.
