### ISSUE TITLE
SSL connection error: SSL_CTX_set_tmp_dh failed

### ISSUE THREAD

**Issue by Xrampino** [PyMySQL/mysqlclient-python#318]
Disclaimer: I looked a lot around, tried many things before asking.

I am on macOS and since the update of OpenSSL (I suspect), I cannot connect using `mysqlclient`.
I tried upgrading `openssl`, reinstalling `mysql-connector-c` (I have no compilation issue, I looked at the linked issue), ..

I have this error (I use sqlalchemy) : `sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2006, 'SSL connection error: SSL_CTX_set_tmp_dh failed') (Background on this error at: http://sqlalche.me/e/e3q8)`

Also, I tried to use `pymysql` and it does work.

**Comment by methane** [comment]
Why don't you post your code for connecting?

Anyway, this error is server error, not client error.
Your MySQL server is not set up for SSL (e.g. No valid key and cert), although ssl is enabled.

**Comment by jalexvig** [comment]
Running into same issue.

@methane If MySQL server is not correctly configured, then why does `pymysql` work?

**Comment by methane** [comment]
Why? Why I know it, without reproducible example? You don't report even only options for connect() function.

Maybe it because you don't use SSL. But I don't know. It's your issue, not mine. Don't bother me. Maintainer is volunteer.  Maintainer is not free tech support.
You should use some forum to get support from community. Don't bother maintainer.

**Comment by Instrumedley** [comment]
wow...why so salty @methane ? The guy asked a valid question

**Comment by Instrumedley** [comment]
@jalexvig . I ran into the same problem. I added an extra parameter to the connect function :
ssl_disabled='True' and it solved for me
For a full list of arguments that can be used when applying connect function, check here:
https://dev.mysql.com/doc/connector-python/en/connector-python-connectargs.html

**Comment by methane** [comment]
> wow...why so salty @methane ? The guy asked a valid question

It may be a valid question if this is a user forum.  But this is a issue tracker, not user forum.
I don't want get dozen notice mail for non-issues.

Read this article: https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde

**Comment by methane** [comment]
For the record, this trouble was asked on Stackoverflow and it is answered.
https://stackoverflow.com/a/53387095/3430118

As I said [the article]( https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde), when you get trouble, you should ask support on community unless you are sure about it's an issue of a specific project.
