### ISSUE TITLE
1.13.14 Windows wheel cannot verify CA SSL certificate

### ISSUE THREAD

**Issue by vsalvino** [PyMySQL/mysqlclient-python#320]
Using MariaDB 10.2 enforcing SSL (supports TLS 1.2), hosted by Azure Database for MariaDB.

1.13.13 can connect fine on Windows.
1.13.14 connects fine when installing from source.
However the 1.13.14 Windows wheel gives the following connection error when trying to connect over SSL:

**2006, 'SSL connection error: Certificate signature check failed'**
```
  File "C:\Users\VinceSalvino\Envs\test\lib\site-packages\MySQLdb\connections.py", line 208, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2006, 'SSL connection error: Certificate signature check failed')
```
In the connection string, I am specifying ssl-ca which is a valid path to a valid CA certificate. For reference, I am using this with Django 2.1 and Python 3.6.

I've done as much reading as I can find about underlying changes in different mysql/mariadb versions. I suspect the issue might related to use of yassl vs openssl in the official mysql/mariadb client, but I do not know enough about it.

Can you tell me what the build environment looks like when you published the Windows wheels to pypi?

**Comment by vsalvino** [comment]
For reference, I have also filed a bug with Azure - the issue seems to be related to the version of MySQL used to build the wheel, not the mysqlclient code itself. However the issue still affects the resulting wheel.

https://github.com/MicrosoftDocs/azure-docs/issues/21793

**Comment by methane** [comment]
https://github.com/MariaDB/mariadb-connector-c/blob/3ffa60dbea57c69926f3cfce286e9f650e3c0047/libmariadb/secure/schannel.c#L287-L383

**Comment by vsalvino** [comment]
Interesting, I think this further confirms the issue is rooted in mariadb. Thanks!

**Comment by methane** [comment]
I'm not sure it's rooted in mariadb.  Your error comes from here.
https://github.com/MariaDB/mariadb-connector-c/blob/3ffa60dbea57c69926f3cfce286e9f650e3c0047/libmariadb/secure/ma_schannel.c#L848-L860

`CertVerifySubjectCertificateContext` failed to verify your CA and cert sent from your DB.
You can use Wireshark to get cert your DB server sent, and verify it manually.

**Comment by vsalvino** [comment]
Thanks so much for your detailed help. It appears that schannel does not verify the certificate, but openssl does verify it. Interestingly enough, if I omit the `ssl-ca` parameter and just use `ssl` without specifying a ca, both versions will connect correctly (I'm assuming that the verified CA certificate must already exist in the OS certificate store).

You can close this issue here, and follow the discussion in my other issue on azure-docs repo. All signs point to this being Microsoft's problem.

On a separate note, I *really* appreciate that a Windows wheel is now available on pypi! Can't thank you enough for providing that.
