### ISSUE TITLE
mysql 8 has no my_config.h, build fails

### ISSUE THREAD

**Issue by gear4s** [PyMySQL/mysqlclient-python#321]
_mysql.c:29:23: fatal error: my_config.h: No such file or directory
     #include "my_config.h"
                           ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

![image](https://user-images.githubusercontent.com/832900/51252594-e80ce180-19a4-11e9-859c-2e352f7ed8fb.png)

**Comment by OdinGitDat** [comment]
I still get this error when running `pip install mysql-python`. Why is this issue closed?

**Comment by methane** [comment]
Because `mysql-python` is not this project.

**Comment by OdinGitDat** [comment]
Sorry, arrived here through google.
