### ISSUE TITLE
Crash of cursor.execute() when passing mapping as args in 1.4.0. 

### ISSUE THREAD

**Issue by felixxm** [PyMySQL/mysqlclient-python#323]
In the Django's test suite we encounter issues with `mysqliclient==1.4.0`. `cursor.execute()` crashes when passing mapping in args, e.g.
```python
cursor.execute(
    'SELECT * FROM raw_query_author WHERE first_name = %(first)s',
    {'first': 'Bob'},
)
```
Stacktrace:
```
MySQLdb/cursors.py", line 188, in execute
    query = query % args
KeyError: b'first'
```

It is probably related with 5e8eeac47f511ca63d6b40dcc3a47190d96a0c0d.

See [test failure](https://djangoci.com/view/PR%20Builders/job/pull-requests-bionic/database=mysql,label=bionic-pr,python=python3.6/3424/testReport/junit/raw_query.tests/RawQueryTests/test_pyformat_params/).

**Comment by andreymal** [comment]
I have similar error with `list` args

```
  File "lib/python3.4/site-packages/pony/orm/dbproviders/mysql.py", line 304, in table_exists
    cursor.execute(sql, [ db_name, table_name ])
  File "lib/python3.4/site-packages/MySQLdb/cursors.py", line 188, in execute
    query = query % args
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'
```

**Comment by felixxm** [comment]
Encoding `keys` fixed issue for me:
```diff
diff --git a/MySQLdb/cursors.py b/MySQLdb/cursors.py
index b8c0d88..e612f1a 100644
--- a/MySQLdb/cursors.py
+++ b/MySQLdb/cursors.py
@@ -181,7 +181,7 @@ class BaseCursor(object):
 
         if args is not None:
             if isinstance(args, dict):
-                args = dict((key, db.literal(item)) for key, item in args.items())
+                args = {key.encode(db.encoding): db.literal(item) for key, item in args.items()}
             else:
                 args = tuple(map(db.literal, args))
             try:
```

**Comment by andreymal** [comment]
(side note: why HISTORY.rst does not contain info about the drop of Python 3.4 support? It also breaks semver)

**Comment by methane** [comment]
> (side note: why HISTORY.rst does not contain info about the drop of Python 3.4 support?

Just missed.

> It also breaks semver)

I'm not follow semver strictly.  Especially, many projects drop old Pyhton support without increasing major version.  Django 2.1 dropped Python 3.4 support too.

**Comment by felixxm** [comment]
@methane Many thanks for the new release :champagne: :tada:
