### ISSUE TITLE
Experiencing AttributeError: __exit__ since mysqlclient 1.4.0

### ISSUE THREAD

**Issue by Fokko** [PyMySQL/mysqlclient-python#325]
We're experiencing error's since we've moved to 1.4.x. For example:
```
======================================================================
64) ERROR: test_mysql_hook_test_bulk_dump (tests.operators.test_operators.MySqlTest)
----------------------------------------------------------------------
   Traceback (most recent call last):
    tests/operators/test_operators.py line 52 in tearDown
      with MySqlHook().get_conn() as conn:
   AttributeError: __exit__
```
https://travis-ci.org/apache/airflow/jobs/481712513

Which uses a `MySQLdb.connect(**conn_config)`, which returns a connection: https://github.com/PyMySQL/mysqlclient-python/blob/master/MySQLdb/connections.py

Of which the interface has been changed: https://github.com/PyMySQL/mysqlclient-python/commit/c64915b1e5c705f4fb10e86db5dcfed0b58552cc#diff-1ae3b1bf2e25b3800993d7b9742c2b97

Why is this changed, and is this something that can be reverted? Personally, I'm a big fan of using a context. And otherwise, we'll have to refactor Apache Airflow.

I don't have time to investigate your issue from an incomplete code snippet.

See also: https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde

**Comment by methane** [comment]
https://github.com/PyMySQL/PyMySQL/issues/735

**Comment by methane** [comment]
FYI, your code expects `__exit__` close the connection.  But it didn't.
It means current Airflow code has connection leak.

I will add `__exit__` which close the connection in 2.0.
