### ISSUE TITLE
ImportError: this is MySQLdb version (1, 4, 2, 'final', 0), but _mysql is version (1, 4, 1, 'final', 0)

### ISSUE THREAD

**Issue by craigholm** [PyMySQL/mysqlclient-python#329]
After installing the 1.4.2 Windows (Python 3.7) wheel from PyPI, attempting to import MySQLdb fails with this stack trace:

```python
>>> import MySQLdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Temp\tmpenv\lib\site-packages\MySQLdb\__init__.py", line 22, in <module>
    (version_info, _mysql.version_info))
ImportError: this is MySQLdb version (1, 4, 2, 'final', 0), but _mysql is version (1, 4, 1, 'final', 0)
```

It seems that the wheel's _mysql.cp37-win_amd64.pyd file is the same one included with 1.4.1.

https://files.pythonhosted.org/packages/e5/77/1ce5ccfe9e5e5cc24d254bf5b23454c18bcb266c0d9d86f829ae90ad3d06/mysqlclient-1.4.2-cp37-cp37m-win_amd64.whl

**Comment by methane** [comment]
Thanks.  I removed Windows wheels from PyPI.
I don't use Windows regularly, so there is no estimate time to next release.

**Comment by methane** [comment]
I've uploaded `1.4.2.post1` windows wheels.
