### ISSUE TITLE
There's 1.4.2.post1 on PyPI which seems to be MIA

### ISSUE THREAD

**Issue by atodorov** [PyMySQL/mysqlclient-python#331]
Hello folks I have a bot service which opened a PR (see https://github.com/kiwitcms/Kiwi/pull/794) to upgrade to 1.4.2.post1 (from PyPI) but I don't find this on the commit log nor in changelog.

Was this version pushed by accident to PyPI? If not what are the changes in it?

**Comment by methane** [comment]
See [post release](https://www.python.org/dev/peps/pep-0440/#post-releases)
"Some projects use post-releases to address minor errors in a final release that do not affect the distributed software (for example, correcting an error in the release notes)."

So post release must not have changelog.  If it has changelog, it must increment micro version.

In this case, I failed to build binary wheels for Windows on 1.4.2.  (See #329)
But PyPI doesn't support overwriting files.  So I need to use post release to upload them.

**Comment by atodorov** [comment]
For the record this breaks all sorts of automation tooling which depends on the package version. Next time when you bump version please upload all packages on PyPI, not only the ones for Windows.

**Comment by methane** [comment]
This is my first "post" release.  And lack of "sdist" package is experimental.
I can add "sdist" to 1.4.2.post1, but I want to understand what is the problem.

I confirmed `pip install mysqlclient` works on macOS, Windows, and Linux after
I released 1.4.2.post1.  1.4.2 is installed on macOS and Linux without any problem.

What is your problem, concretely?

**Comment by atodorov** [comment]
See this PR https://github.com/kiwitcms/Kiwi/pull/794 and the failing job behind it https://travis-ci.org/kiwitcms/Kiwi/jobs/492155308, line 755 in the output:

```
Collecting mysqlclient==1.4.2.post1 (from -r requirements/mariadb.txt (line 2))
  Could not find a version that satisfies the requirement mysqlclient==1.4.2.post1 (from -r requirements/mariadb.txt (line 2)) (from versions: 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10, 1.3.11rc1, 1.3.11, 1.3.12, 1.3.13, 1.3.14, 1.4.0rc1, 1.4.0rc2, 1.4.0rc3, 1.4.0, 1.4.1, 1.4.2)
No matching distribution found for mysqlclient==1.4.2.post1 (from -r requirements/mariadb.txt (line 2))
```

**Comment by methane** [comment]
I don't understand why it is problem.  There are no reason to "pip install mysqlclient==1.4.2.post1" in your project, there are?

**Comment by atodorov** [comment]
Why wouldn't I want to have `1.4.2.post1` in my project? It is the latest version available and we try to keep all dependencies always at their latest version.

So in whatever way you packaged `1.4.2.post1` is breaking the ability to always install the latest version. 

> In this case, I failed to build binary wheels for Windows on 1.4.2

And you did so with `1.4.2.post1` however it is missing the sdist tarball so the Travis job above fails.

The issue is a publishing problem on your side: regardless of the version number always push all files to PyPI so that people who want to stay at the latest published version can do so regardless of why they may want to use that version. (In my case it is a robot service which automatically tries to upgrade to the latest version when it sees something new has been published on PyPI).

**Comment by methane** [comment]
> Why wouldn't I want to have `1.4.2.post1` in my project? It is the latest version available and we try to keep all dependencies always at their latest version.

Because "1.4.2.post1" is same to "1.4.2" semantically.  No bug fix.  No features added.  No need to upgrade.


> And you did so with `1.4.2.post1` however it is missing the sdist tarball so the Travis job above fails.

It's just a behavior of the bot.  `pip install -U mysqlclient` installs 1.4.2 as latest available version.

> The issue is a publishing problem on your side: regardless of the version number always push all files to PyPI so that people who want to stay at the latest published version

No.  It's impossible.  I can't release all binary wheels on every versions.  If it is required, I abandon this project.

But, of course, I can release sdist always.  In this time, lack of sdist is just a trial to avoid forcing
many people to upgrade mysqlclient without any benefit.

**Comment by DerekCrosson** [comment]
For anyone who has the same problem on Ubuntu 18.04 with Python 3.7, here's the solution:
```sudo apt-get install python3.6-dev libmysqlclient-dev```

**Comment by prasad624** [comment]
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
