### ISSUE TITLE
cursor.executemany doesn't work when functions are used

### ISSUE THREAD

**Issue by vmendiratta** [PyMySQL/mysqlclient-python#334]
Thanks for maintaining and supporting such a crucial library.

I ran into a scenario where it wasn't very obvious why executemany's performance was not up to the mark. It seems the regex RE_INSERT_VALUES doesn't support queries where mysql functions are being called in the VALUES clause.

Usecase to support queries of the form:

INSERT INTO testdb.test (type, some_field, status, some_char_field) VALUES (%s, hex(%s), %s, md5(%s));

MySQL supports this query pattern and it isn't very helpful when mysqlclient-python silently falls back to cursor.execute and performance drops.
A 'warning' level log here will go a long way to help developers unearth reasons for those performance hits.

I also tried to come up with a regex to support this query pattern. Looking for comments/feedback if it's missing anything.

```python
RE_INSERT_VALUES = re.compile(
    r"\s*((?:INSERT|REPLACE)\b.+\bVALUES?\s*)" +
    r"(\(\s*(?:([a-zA-Z0-9]+?[(])?%s([)])?|([a-zA-Z0-9]+?[(])?%\(.+\)s([)])?)\s*(?:,\s*(?:([a-zA-Z0-9]+?[(])?%s([)])?|([a-zA-Z0-9]+?[(])?%\(.+\)s([)])?)\s*)*\))" +
    r"(\s*(?:ON DUPLICATE.*)?);?\s*\Z",
    re.IGNORECASE | re.DOTALL)
```

Thanks.

**Comment by methane** [comment]
I won't implement real parser.  I don't want to maintain more complicated regex.  I don't want to allow more false-positive.
So you need to build query manually.

And since executemany may called automatically by ORM, I don't want to show warning too.

**Comment by mufid99salt** [comment]
Hello, 

I would really like to use executemany() but I need to use the mysql function UNHEX on one of my arguments and this causes the regex to not match. How would you suggest I solve this problem? Thank you!

**Comment by vmendiratta** [comment]
Build a wheel for yourself after changing the regex and use that :)
