### ISSUE TITLE
Add support for binary, varbinary types

### ISSUE THREAD

**Issue by RosterIn** [PyMySQL/mysqlclient-python#335]
I have a table defined as follow:

CREATE TABLE `my_table` (
  `id` bigint(10) unsigned NOT NULL AUTO_INCREMENT,
 `config_id` binary(8) NOT NULL,
  `my_ip` varbinary(16) NOT NULL,
  PRIMARY KEY (`id`)
) 

According to
https://github.com/PyMySQL/mysqlclient-python/blob/master/MySQLdb/constants/FIELD_TYPE.py

These types are not supported.

These are valid MySQL types:
https://dev.mysql.com/doc/refman/5.7/en/binary-varbinary.html

**Comment by methane** [comment]
Your assumption is wrong.
Try before report issue.

**Comment by RosterIn** [comment]
@methane if you please.. this issue was opened since Airflow repo thinks since these types don't appear in the file they are not supported. Please see their concern here:
https://github.com/apache/airflow/pull/4802

I understand your point but if I won't get your clearance that they are wrong and the library support these types my PR won't be approved.

**Comment by methane** [comment]
field type is not column type.
