### ISSUE TITLE
Returned Type from Query is always string 

### ISSUE THREAD

**Issue by upMKuhn** [PyMySQL/mysqlclient-python#338]
Hi, 
I am currently investigating a Bug I encountered on the Django project. I have raised it, but we would like to know if it is possible to fix it on the mysqlclient side. 

**The problem arises on the given table:**
```
id char(32) COLLATE utf8mb4_unicode_ci NOT NULL,
created_on datetime(6) NOT NULL,
expiry_date datetime(6) DEFAULT NULL
```

**And you use the following query** 
```
SELECT
    `advertisement_project`.`created_on`,
MIN(CASE
        WHEN
            (`buyout_buyout`.`is_archived` = 0
                AND `buyout_buyout`.`is_deleted` = 0)
        THEN
            `buyout_buyout`.`expiry_date`
        ELSE NULL
    END) AS `minExpiryDate`
FROM MyTable
GROUP BY `id`
```

Mysql Client returns the following row: 
[datetime(2016,1,1...), '2016-01-01 00:00:00'] 

The problem is that this custom column(minExpiryDate) is returned of type string. Our question is:

> I also wonder if it could be possible to let mysqlclient know what the expected type is for a specific cursor instead though. We have this information in the compiler (through .output_field) so if we can provide per-cursor converter hints I assume it would be even more efficient because it would be performed in C. Another option is figuring out if mysqlclient can somehow figure out how to introspect such return value on it's own (e.g. maybe MySQL returns a different field type in this case).

Django Bug: https://code.djangoproject.com/ticket/30224
mysqlclient: version 1.4.2

Thanks,
Martin

**Comment by methane** [comment]
It is possible to fix the problem in your application side; fix your data and stop using invalid date time.
Old days, MySQL accepted such a silly datetime.  It is forbidden by default recent days.

Python datetime doesn't accept such broken value.  So I can't return datetime value.

**Comment by methane** [comment]
Ah, I'm sorry.  I misunderstood your problem.

```
MIN(CASE
        WHEN
            (`buyout_buyout`.`is_archived` = 0
                AND `buyout_buyout`.`is_deleted` = 0)
        THEN
            `buyout_buyout`.`expiry_date`
        ELSE NULL
    END)
```

I can't understand this part.  I'm not expert of MySQL.  I'm expert of only MySQL protocol.
But I suspect this part creates string value.  You should read MySQL manual carefully to
understand what type of value is returned.

And you may be able to use CAST to convert type from string to datetime.

**Comment by upMKuhn** [comment]
Hi @methane,

Ok so you are saying that the mysql server sends the response with an attached annotation "the type is string" for each value and the client simply honours the server's response types.

I boiled it down to the `MIN` function. This one seems to convert my data type into a string. 

> - c.execute(""" SELECT  MIN(**CAST**('2018-01-01 00:00:00' AS **datetime**)); """)
> - 1
> -  c.fetchall()[0][0]
> - **'**2018-01-01 00:00:00**'**


> - c.execute(""" SELECT  MIN(**TIMESTAMP**('2018-01-01 00:00:00')); """)
> - 1
>  - c.fetchall()[0][0]
> - **'**2018-01-01 00:00:00**'**


Therefore the following is either a bug on the mysql server. Or something mysql seems to have plenty of _desired unintuitive "features"_ :expressionless:.  

What do you think I should do now? 
Raise a bug on the MYSQL or is there something you can do about it :) ?

Thanks, 
Martin

**Comment by methane** [comment]
> What do you think I should do now?
> Raise a bug on the MYSQL or is there something you can do about it :) ?

There is nothing I can do.  I don't know even what is MIN() and MAX() spec.
I suspect it takes only numerical type or string, and other types are converted into string.
But I'm not sure.  I'm not MySQL expert.

You can use bugs.mysql.com or https://lefred.be/mysql-community-on-slack/
