### ISSUE TITLE
Version 1.4.X and again KOI8-R encoding

### ISSUE THREAD

**Issue by foger** [PyMySQL/mysqlclient-python#340]
Hi.

In 1.3.X versions I had an issue #257 and solved it simply adding 
```python
        if charset == "utf8mb4":
            py_charset = "utf8"
        elif charset == "latin1":
            py_charset = 'koi8-r'
        else:
            py_charset = charset
```

(my database charset = latin1, but data inserted in koi8-r).

Then 
```python
con = mdb.connect('localhost', 'user', 'passwd', 'billing');
cur = con.cursor()
cur.execute("SELECT fio FROM user WHERE id = %s", (36888,))
fio = cur.fetchone()
print(fio)
```

And I get normal data in KOI8-R

But when I updated mysqlclient to 1.4.X my "fix" stopped working. What changed from 1.3.X to 1.4.0 about encodings? My `py_charset = 'koi8-r'` is now ignored

Now I should additionally decode or encode/decode data:

```python
# above code
... 

# if use_unicode = False:
fio[0].decode('koi8-r')
# if use_unicode = True
fio[0].encode('latin1').decode('koi8-r')
```

but before I simply made the query and received data in KOI8-R  from mysql
Where should I look in your library to fix this again and get data without following decoding and encoding?

**Comment by methane** [comment]
It was unofficial workaround.  It is not supported way.  Additionally, I meant adding this

```
elif encoding == "koi8r":
    py_encoding = "koi8_r"
```

You're doing completely unsupported hack.

Now mysqlclient supports `charset="koi8r"` directly:

https://github.com/PyMySQL/mysqlclient-python/blob/1a67ae2cc2da1a2bf511cf70b20dcd5fca5ba7fe/MySQLdb/_mysql.c#L219-L221

On the other hand, there are no support about setting totally different encoding
to connection encoding and python charset.  I don't anything about what can be
happened on such cases.  I won't support such configuration.
