### ISSUE TITLE
python3 use cursor.execute(sql, param) get error

### ISSUE THREAD

**Issue by Igamegum** [PyMySQL/mysqlclient-python#342]
when I use cursor.execute(sql, param) , I got the error 
`File "/home/sql_work/lib/lib/python3.4/site-packages/MySQLdb/cursors.py", line 193, in execute
    query = query % args
 TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple' 
`
sql is str, param is a tuple
It seems that cause by the sentense 
`if isinstance(query, unicode):
    query = query.encode(db.encoding)     
`

**Comment by methane** [comment]
Python 3.4 is not supported.
