### ISSUE TITLE
Fails to import: symbol __gxx_personality_v0: referenced symbol not found

### ISSUE THREAD

**Issue by Gillingham** [PyMySQL/mysqlclient-python#35]
Looks like this bug got imported from MySQLdb. There's an original report and patch located http://sourceforge.net/p/mysql-python/bugs/334/

**Comment by methane** [comment]
I don't like the patch. libmysqlclient may and may not use libstdc++.
It's bug of mysql_config. I recommend you to add it to your mysql_config, not mysqlclient-python.
