### ISSUE TITLE
Connection constructor not honoring column type -> custom conversion function (for JSON and other types)

### ISSUE THREAD

**Issue by arvindsun** [PyMySQL/mysqlclient-python#354]
Hello - firstly, thank you so much for all your work in maintaining this client. I have been using various versions of this for over 10 years!

I have found a potential issue with Python3 and the new JSON datatype in MySQL > 5.7 ( I am using 8.0).

I wanted to add a converter to go from JSON -> Python dicts seamlessly by specifying a conv= option in the constructor and for the reads, we seem to be not honoring any of the passed in decoders.
This [`if use_unicode:` block](https://github.com/PyMySQL/mysqlclient-python/blob/master/MySQLdb/connections.py#L199) basically sets the JSON decoder to `unicode` always.

I worked around it by doing `conn.converter[MySQLdb.constants.FIELD_TYPE.JSON] = json_to_dict` after the constructor is called, but would be nice to honor the passed in conv object overrides after the use_unicode block.

**Comment by methane** [comment]
Please don't expect convenient converter in low end level layer.
ORM is your friend.
