### ISSUE TITLE
Solution to the MacOS problem

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [PyMySQL/mysqlclient-python#356]
Took me a while to understand what the README meant when it said I should edit `mysql_config`. It means to edit the actual executable.

For future reference, this one-liner should fix it:
```
sudo sed -i '' 's/libs="$libs -l"/libs="$libs -lmysqlclient -lssl -lcrypto"/' $(which mysql_config)
```

**Comment by methane** [comment]
Please don't use issue tracker as wiki.
I maintain several OSSes.  I receive dozen notification every week which is not need to notice to maintainer.
