### ISSUE TITLE
Why Update is doesn't work? 

### ISSUE THREAD

**Issue by Nadya24** [PyMySQL/mysqlclient-python#361]
**IF YOU HAVE SOME TROUBLE, IT'S MAY NOT ISSUE OF THIS PROJECT. GO STACKOVERFLOW!!!**

If you failed to build, go Stackoverflow.
If you failed to install, go Stackoverflow.
If you failed to connect to database, go Stackoverflow.

FYI, MySQL Connector/C 6.1.10 has bug. see https://github.com/PyMySQL/mysqlclient-python/issues/169#issuecomment-299778504

Only when If you're sure it's PyMySQL's issue, report the complete steps to reproduce, from creating database.

I don't have time to investigate your issue from an incomplete code snippet.

See also: https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde

**Comment by methane** [comment]
> Only when If you're sure it's PyMySQL's issue, report the complete steps to reproduce, from creating database.

**Comment by Nadya24** [comment]
But how use update?

**Comment by methane** [comment]
This is not an user support forum, and OSS maintainers are not free tech support or free teacher.
Please use other Python or MySQL community.
