### ISSUE TITLE
Trying install mysqlclient for OSX High Sierra 

### ISSUE THREAD

**Issue by dushansilva** [PyMySQL/mysqlclient-python#363]
When trying to install mysqlclient i get the following error 

    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6t/c8trfmm943b1h681q7tb4gm40000gp/T/pip-install-b3uqbb8i/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/private/var/folders/6t/c8trfmm943b1h681q7tb4gm40000gp/T/pip-install-b3uqbb8i/mysqlclient/setup_posix.py", line 53, in get_config
        libraries = [dequote(i[2:]) for i in libs if i.startswith('-l')]
      File "/private/var/folders/6t/c8trfmm943b1h681q7tb4gm40000gp/T/pip-install-b3uqbb8i/mysqlclient/setup_posix.py", line 53, in <listcomp>
        libraries = [dequote(i[2:]) for i in libs if i.startswith('-l')]
      File "/private/var/folders/6t/c8trfmm943b1h681q7tb4gm40000gp/T/pip-install-b3uqbb8i/mysqlclient/setup_posix.py", line 12, in dequote
        raise Exception("Wrong MySQL configuration: maybe https://bugs.mysql.com/bug.php?id=86971 ?")
    Exception: Wrong MySQL configuration: maybe https://bugs.mysql.com/bug.php?id=86971 ?
    ----------------------------------------

However after following through other issues such as https://github.com/PyMySQL/mysqlclient-python/issues/169 that most users who try to install this have mysql installed and issue is occurring due to this.

Currently I have not install mysql in my local machine, I am running mysql inside a docker container. Therefore problem my problem is, **Is there away to install this package without having mysql installed locally?**

 This would be a concern if i am only planning to connect to a remote mysql server without  having to setup a mysql instance locally.

**Comment by methane** [comment]
MySQL stop shipping new MySQL Connector/C independent with MySQL.
And old MySQL Connector/C is having https://bugs.mysql.com/bug.php?id=86971 .

What you can do is:

* Use MariaDB Connector/C
* Install MySQL even if you don't use server
* Install old MySQL Connector/C and fix the issue manually

This is bug of MySQL, not this project.
Please go  https://bugs.mysql.com/bug.php?id=86971 as I wrote in exception message.

**Comment by dushansilva** [comment]
I think that link does not help me as it is referring to the usr/local/bin/mysql_config which only exists if i installed mysql locally.

**Comment by methane** [comment]
There is `mysql_config` when you installed "MySQL Connector/C".
It is key part of this library.  Without it, you can not compile this project.

**Comment by dushansilva** [comment]
managed to fix it by getting the mysql config to usr/local/bin and following these steps https://github.com/PyMySQL/mysqlclient-python/issues/169#issuecomment-306821834

thanks for the help.
