### ISSUE TITLE
GRANT ALL not working

### ISSUE THREAD

**Issue by LennyLip** [PyMySQL/mysqlclient-python#364]
MySQL 8

Following command DROP and CREATE USER is OK. GRANT command does not work (+ no any errors).

```
db_user_sql = "DROP USER IF EXISTS {0}@'{2}';" \
                  "CREATE USER '{0}'@'{2}' IDENTIFIED WITH mysql_native_password BY '{3}';" \
                  "GRANT ALL PRIVILEGES ON {1}.* TO `{0}`@`{2}`;" \
        .format(database_user_name, database_name, MY_SQL_HOST, db_user_password)
```
(connected as root,  GRANT to another user)

I tried params, backticks, quotes, etc, no success.

The same command in MySql Workbench works fine:

```
GRANT ALL PRIVILEGES ON answer_2.* TO `answer_user_2`@`localhost`;
```

**Comment by methane** [comment]
It seems very likely to your fault, because driver doesn't know anything about query.
But you don't provide enough information to reproduce your problem.  And I'm not free user support.
Please use MySQL or Python community, or commercial user support.
