### ISSUE TITLE
Hardcoded client variable in setup_windows.py

### ISSUE THREAD

**Issue by lshaf** [PyMySQL/mysqlclient-python#365]
Is there any reason to doing so?
Because currently I'm using Windows 10 with MySQL Connector C/6.1 installed and there's no `mariadb` folder on there.

![image](https://user-images.githubusercontent.com/4636265/59831064-31ee5f00-936b-11e9-9403-24ad72e5fa1f.png)

Even I did install mariadb connector c, there's no `mariadb` folder inside `include` here is screenshot for mariadb connector

![image](https://user-images.githubusercontent.com/4636265/59831030-1c793500-936b-11e9-8657-6efd3414fc6b.png)

I keep failing install this lib from pip but after I clone and do setup manually after change client to `mysqld` it's success.

Please tell me if I did something wrong there.

note:
mariadb connector c: https://mariadb.com/kb/en/library/mariadb-connector-c-3010-release-notes/
mysql connector c: https://downloads.mysql.com/archives/c-c/

**Comment by methane** [comment]
> Is there any reason to doing so?

There are many possible configurations on Windows.  I can not support all of them.

> I keep failing install this lib from pip

I provide some binary wheels.  https://pypi.org/project/mysqlclient/#files
It is intended to be used for most users.

>  I clone and do setup manually after change client to mysqld it's success.

It is intended flow to customize mysqlclient for your environment.
You can not just `pip install`, because I can not support all environments of million users.

**Comment by methane** [comment]
Uh, note that MySQL Connector/C is very old.  That's one reason of why I used mariadb to build wheels.
Of course, you can use it at your own risk, by editing `setup.cfg` and `setup_windows.py` manually.

**Comment by lshaf** [comment]
I see, Thanks for answer dude. Good work then :).
