### ISSUE TITLE
Build fails on Debian buster

### ISSUE THREAD

**Issue by Flupsy** [PyMySQL/mysqlclient-python#366]
Debian buster's libmariadbclient-dev has renamed `/usr/bin/mysql_config` to `/usr/bin/mariadb_config` which breaks the build of this package.

It builds cleanly if I set `mysql_config = /usr/bin/mariadb_config` in site.cfg but this makes life difficult for virtualenvs.

**Comment by methane** [comment]
You can install `libmariadb-dev-compat`.

**Comment by Flupsy** [comment]
Yep, that works!  Sent you a PR with a small addition to the README.
