### ISSUE TITLE
MySQLdb.NULL is undefined

### ISSUE THREAD

**Issue by ckclark** [PyMySQL/mysqlclient-python#368]
## Expected Behavior
No exception is raised.

## Current Behavior
An exception is raised:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'NULL'
```

## Possible Solution
Removed `"NULL"` from `__all__` of `__init__.py`

## Steps to Reproduce
1. `from MySQLdb import *`

## Context (Environment)
It seems that `"NULL"` symbol is removed from `MySQLdb/_mysql.c` in 819688b6

**Comment by methane** [comment]
You can use just "NULL" instead.
