### ISSUE TITLE
Build of 1.4.2.post1 fails against MariaDB 10.4 on RHEL 7

### ISSUE THREAD

**Issue by MiddleFork** [PyMySQL/mysqlclient-python#371]
version: 1.4.2.post1

Unable to build off-the-shelf against MariaDB 10.4 on RHEL7:  
workaround:  symlink the missing library file name to the installed library 
possible fix:  point to the correct file name.   

> running build_ext
>     building 'MySQLdb._mysql' extension
>     creating build/temp.linux-x86_64-3.7
>     creating build/temp.linux-x86_64-3.7/MySQLdb
>     gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Dversion_info=(1,4,2,'post',1) -D__version__=1.4.2.post1 -I/usr/include/mysql -I/usr/include/mysql/mysql -I/var/www/data/django/project_ghost/venv/include -I/usr/local/include/python3.7m -c MySQLdb/_mysql.c -o build/temp.linux-x86_64-3.7/MySQLdb/_mysql.o
>  gcc -pthread -shared build/temp.linux-x86_64-3.7/MySQLdb/_mysql.o -L/usr/lib64/ -lmariadb -lz -ldl -lm -lpthread -lssl -lcrypto -o build/lib.linux-x86_64-3.7/MySQLdb/_mysql.cpython-37m-x86_64-linux-gnu.so
> 
>     **/bin/ld: cannot find -lmariadb**
> 
>     collect2: error: ld returned 1 exit status
> 
>     error: command 'gcc' failed with exit status 1
> 
>  
> 
>     ----------------------------------------
> 
> Command "/var/www/data/django/project_ghost/venv/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-fvfympg4/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-d5vm_wqx/install-record.txt --single-version-externally-managed --compile --install-headers /var/www/data/django/project_ghost/venv/include/site/python3.7/mysqlclient" failed with error code 1 in /tmp/pip-install-fvfympg4/mysqlclient/
> 

The correct file name on RHEL 7 is /usr/lib64/libmariadbd.a  (with the extra 'd' character)

This symlink allowed the build and install to successfully complete:
ln -s /usr/lib64/libmariadbd.a /usr/lib64/libmariadb.a

**Comment by methane** [comment]
It's your environment issue.

**Comment by MiddleFork** [comment]
I believe your are correct. For the record I did not have the MariaDB-compat package installed.

Thank you

**Comment by ntorga** [comment]
Interesting, just to report in case anyone find this topic on Google, I did have MariaDB-compat package installed and I was running MariaDB 10.3 on CentOS 7, this issue also happened. The symlink workaround was the solution, thanks @MiddleFork.

**Comment by ntorga** [comment]
In case anyone faces the same issue, try installing MariaDB-shared package.
