### ISSUE TITLE
use_unicode respects FLAG_BINARY in 1.4.0

### ISSUE THREAD

**Issue by benjaminp** [PyMySQL/mysqlclient-python#376]
It appears that 3bea8cd8dd89c1d078a6ff2a36ef5804429f398f made `use_unicode` start not converting fields to Unicode that are returned with `BINARY_FLAG`. [Specifically](https://github.com/PyMySQL/mysqlclient-python/commit/3bea8cd8dd89c1d078a6ff2a36ef5804429f398f#diff-1ae3b1bf2e25b3800993d7b9742c2b97R187), `_bytes_or_str` can return bytes whereas `_string_decode` never could. Was this behavior change intentional? 3bea8cd8dd89c1d078a6ff2a36ef5804429f398f looks like it was intended to be pure optimization.

**Comment by methane** [comment]
It was not only pure optimization, but also bugfix.

BINARY_FLAG represents "binary attribute", which is not relating to binary / string separation.
Strings can have the "binary attribute".

To distinguish binary / string, we need to check only `charsetnr == 63`.

See https://dev.mysql.com/doc/refman/8.0/en/c-api-data-structures.html

**Comment by benjaminp** [comment]
If `BINARY_FLAG` is not related to binary/string separation, why does `_bytes_or_str` decide what type to return based on it?

**Comment by methane** [comment]
MySQL-python abuse the flag.  It overwrite `flag&BINARY_FLAG` bit by `charsetnr == 63`.

**Comment by tumb1er** [comment]
@methane I have a question.
Near every query now returns `bytes` instead of `str` (see [here](https://github.com/tumb1er/django_sphinxsearch/pull/19)). 
Can I fire any flag or connection argument to get my string values back?

**Comment by methane** [comment]
@tumb1er it's different issue. Please provide reproduce example. (Note that I'm not Sphinx user.  Don't assume I can set up a Sphinx instance)

**Comment by tumb1er** [comment]
@methane assuming sphinxsearch returns all strings with binary flag, there should be a way to decode bytes as it was prior to 1.4.3. 
To reproduce, you should think about a way of reverting "fix" for that old MySQL-python bug. 
In normal mode, "binary" string from db is returned as bytes.
I need a way to return "binary" string from db as str.
Is there any configurable flag/callback?

**Comment by methane** [comment]
> assuming sphinxsearch returns all strings with binary flag,

If so, it's Sphinxsearch's issue.  BINARY_FLAG represents bin collation, not for distinguish string / binary.

**Comment by tumb1er** [comment]
That means, I'll never could use mysqlclient to connect to sphinxsearch mysql protocol. That's sad :(

**Comment by methane** [comment]
Never? Why not report issue to Sphinx?
And you can pin 1.4.2 too.

**Comment by methane** [comment]
Uh, this change is committed before 1.4.0.
1.4.3 doesn't change this.  If 1.4.2 worked fine, it's totally different issue.

**Comment by tumb1er** [comment]
>  If 1.4.2 worked fine, it's totally different issue.
This changes a lot. I'll open another issue.
