### ISSUE TITLE
escape_sequence still in the docs

### ISSUE THREAD

**Issue by aladagemre** [PyMySQL/mysqlclient-python#380]
I see that your docs still mention about https://mysqlclient.readthedocs.io/MySQLdb.html#MySQLdb.escape_sequence

and escape_dict. 

But in reality your code after 1.4.0 doesn't have this method. If I'm not mistaken, you may want to update it. Only esca

I assume we have to use "from pymysql import escape_sequence" to compensate this change.

**Comment by methane** [comment]
Fixed via 6c67620bc65728ff269dbb7550fc88b18073a74d
