### ISSUE TITLE
Setup doen't work with Windows 10. I have installed mysql connector/C 8.0.17. This doesn't help.

### ISSUE THREAD

**Issue by bchip50** [PyMySQL/mysqlclient-python#384]
**IF YOU HAVE SOME TROUBLE, IT'S MAY NOT ISSUE OF THIS PROJECT. GO STACKOVERFLOW!!!**

If you failed to build, go Stackoverflow.
If you failed to install, go Stackoverflow.
If you failed to connect to database, go Stackoverflow.

FYI, MySQL Connector/C 6.1.10 has bug. see https://github.com/PyMySQL/mysqlclient-python/issues/169#issuecomment-299778504

Only when If you're sure it's PyMySQL's issue, report the complete steps to reproduce, from creating database.

I don't have time to investigate your issue from an incomplete code snippet.

See also: https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde

**Comment by bchip50** [comment]
pip didn't not install. Says it needs cl.exe on Windows 10. MySQL Connector/C 8.0.17 installed ok.

**Comment by methane** [comment]
READ THE README

**Comment by bchip50** [comment]
I read it first. Didn't help. I'll switch over to Postgres and see if it will work for me.

**Comment by methane** [comment]
https://github.com/PyMySQL/mysqlclient-python#install-from-pypi

<img width="919" alt="スクリーンショット 2019-08-14 11 19 59" src="https://user-images.githubusercontent.com/199592/62990111-aafac600-be85-11e9-9cf6-92b7335bfa39.png">
