### ISSUE TITLE
Proble to install with de oficial Orable lib

### ISSUE THREAD

**Issue by fjbardelli** [PyMySQL/mysqlclient-python#385]
It is possible to install it by having, installed the official Oracle version 8.0.17 connector, read the error documentation, but failed to execute the necessary commands for its installation.
The installation I am doing in Ubuntu 18.04LTS

Thanks

**Comment by fjbardelli** [comment]
Run sudo apt-get install python3.7-dev   command, and the error change to 

pip install mysqlclient --no-cache-dir
Collecting mysqlclient
  Downloading https://files.pythonhosted.org/packages/4d/38/c5f8bac9c50f3042c8f05615f84206f77f03db79781db841898fde1bb284/mysqlclient-1.4.4.tar.gz (86kB)
     |████████████████████████████████| 92kB 1.4MB/s 
    ERROR: Command errored out with exit status 1:
     command: /home/fernando/.virtualenvs/Academics/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mtoxkay_/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mtoxkay_/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-mtoxkay_/mysqlclient/
    Complete output (12 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mtoxkay_/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-mtoxkay_/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-mtoxkay_/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by methane** [comment]
Oracle doesn't release MySQL Connector/C 8.0.17.  It is Connector/C++ 8.0.17.
libmysqlclient is bundled with MySQL server package, not with Connector/C++.

So you need to install "Server" to build a "client".

**Comment by fjbardelli** [comment]
thanks
