### ISSUE TITLE
Binary wheel for Python 3.8 for Windows

### ISSUE THREAD

**Issue by AndreyMZ** [PyMySQL/mysqlclient-python#392]
## Problem description
There is no binary wheel for CPython 3.8 for Windows on PyPI: <https://pypi.org/project/mysqlclient/#files>.

## Steps to reproduce
1. Install [Python](https://www.python.org/downloads/windows/) 3.8.
2. Run:
~~~
py -3.8 -m pip install mysqlclient --only-binary=mysqlclient 
~~~
### Actual result
~~~
C:\Users\user\Desktop>py -3.8 -m pip install mysqlclient --only-binary=mysqlclient
ERROR: Could not find a version that satisfies the requirement mysqlclient (from versions: none)
ERROR: No matching distribution found for mysqlclient
~~~
### Expected result
No errors.

**Comment by methane** [comment]
I released v1.4.5 with Python 3.8 Windows amd64 wheel.
