### ISSUE TITLE
Multiple calls to `callproc` causes error if `nextset` isn't called.

### ISSUE THREAD

**Issue by liamhospiq** [PyMySQL/mysqlclient-python#418]
**Note:** If you wanted, I would be happy to (attempt to) contribute a fix for this.

### Describe the bug

Calling `callproc` twice without calling `nextset` in between causes error, even when `fetchall` is used. Seen after upgrading from 1.3.5 => 1.4.6 (also seen on 1.3.13).

### To Reproduce

**Schema**

Doesn't matter, just create a proc like:

```
create procedure foo() select 1;
```

**Code**

```py
from django.db import connection
c = connection.cursor()
c.callproc('foo')
c.fetchall()
c.callproc('foo')
```

This will raise `MySQLdb._exceptions.ProgrammingError: (2014, "Commands out of sync; you can't run this command now")`

### Environment

**MySQL Server**

- Server OS (e.g. Windows 10, Ubuntu 20.04): macOS 10.12.6
- Server Version (e.g. MariaDB 10.3.16): mysql  Ver 14.14 Distrib 5.7.25, for osx10.12 (x86_64) using  EditLine wrapper

**MySQL Client**

- OS (e.g. Windows 10, Ubuntu 20.04): macOS 10.12.6

- Python (e.g. Homebrew Python 3.7.5): Python 3.7.4

- Connector/C (e.g. Homebrew mysql-client 8.0.18): `pip install mysqlclient==1.4.6` (same behavior on 1.3.13)

### Additional context

I often call multiple procedures using this method and it needing to update every wrapper function to call `nextset` is a hassle. This is also causes issues for future development as it's not an easy issue to debug if you aren't already aware of it.

For example, we write Python functions to wrap all our procedures. If a dev were to call two of these within a request and `nextset` was missing from one, it would be very difficult for them to figure out what was wrong. In my opinion this makes `callproc` unsafe and we would have to patch it ourselves if it's not fixed here.

I did eventually find a note in the [docs](https://mysqlclient.readthedocs.io/user_guide.html#cursor-objects) about this but to me this seems like a regression and unexpected behavior.

Thank you!

**Comment by liamhospiq** [comment]
Closing for now because the problem is more general than I initially realized. This happens after calling a stored procedure by any method (e.g. `execute` or `callproc`)  and executing another query. `execute` always calls `nextset` so it avoids this problem, but other ways of calling queries like `callproc` or (Django) `Model.save` will also cause the error... :(

**Comment by methane** [comment]
> but other ways of calling queries like `callproc` or (Django) `Model.save` will also cause the error... :(

Doesn't `Model.save` calls `execute`?  How it execute queries??

**Comment by liamhospiq** [comment]
I will take another look at that. I'm still digging into this on my own so I wanted to close it until I have more info.
