### ISSUE TITLE
You cannot use the sqlalchemy and mysqlclient libraries to connect to another TCP-based mysql server.

### ISSUE THREAD

**Issue by search5** [PyMySQL/mysqlclient-python#419]
In sqlalchmey, like engine = create_engine ('mysql: // user: passwd @ localhost: 3320 / database', connect_args = {"host": "localhost", "port": 3320}, convert_unicode = True, echo = False) The command fails to connect to an external database that connects only through TCP. Compared to the mysqlclient library, mysql-connector-python provided by mysql.com succeeds in tcp connection.

### To Reproduce

Install the mysql database you want to connect to on a host other than your local host and configure it so that you can connect via TCP.

Then configure the file using https://flask.palletsprojects.com/en/1.1.x/patterns/sqlalchemy/ and the db uri listed in the body list, and verify the DB connection using code similar to the following:

```sql
from models import User
j = User.query.limit(10)
tuple(j)
```

### Environment

**MySQL Server**

- Server OS: Ubuntu 18.04
- MySQL Version: 5.5.5-10.4.11-MariaDB-1:10.4.11+maria~bionic

**MySQL Client**

- Client OS: Ubuntu 18.04
- Python: Python 3.6.6(compile version)
- Connector/C: (apt install )8.0.17-1ubuntu18.04
- Client ORM: SQLAlchemy 1.3.12

**Comment by methane** [comment]
We use the sqlalchemy and mysqlclient libraries to connect to TCP-based mysql servers.

**Comment by methane** [comment]
I closed this issue because "You cannot" doesn't make sense at all, and this is a very famous MySQL behavior, not a bug of this library.  The same behavior happens with the "mysql" cli too.
I always say "OSS maintainer is not free tech support.  Go user community like Slack or Stackoverflow" when people ask me to help to troubleshoot *their* problem.

But I noticed you are not a native English speaker like me, so I assume you just misused "You" instead of "I".  I want to be kind to Korean because some Japanese and Korean hate each other.

OK, now I am one-time free tech support for you.
The issue you encountered is very famous MySQL behavior.
You can not connect to MySQL via TCP when "mysql -h localhost" because MySQL assume you want to use unix socket when host is the "localhost".  You should use "mysql -h 127.0.0" or "mysql -h localhost --protocol tcp".

See https://dev.mysql.com/doc/refman/8.0/en/connecting.html for reference.

> If the host is not specified or is localhost, a connection to the local host occurs:
> 
> * On Windows, the client connects using a shared-memory connection, if the server was started with the shared_memory system variable enabled to support shared-memory connections.
>
> * On Unix, MySQL programs treat the host name localhost specially, in a way that is likely different from what you expect compared to other network-based programs: the client connects using a Unix socket file. The --socket option or the MYSQL_UNIX_PORT environment variable may be used to specify the socket name.

**Comment by search5** [comment]
Thank you for understanding that I am not good at English and not good at it.

Thank you for your one-time technical good support.

However, the environment I tested was on a MySQL server on docker, and the client programs to connect to were on local servers.

In the test environment, it was difficult to create another server, so I created a database container with Docker and tried to connect to it.

I also talked about mysql cli, so I know that if you don't give tcp as protocol option and value when you use mysql cli, you use unix socket instead of tcp.

@methane. Please check  again. If you're having trouble verifying it, we can make a video for you.

**Comment by methane** [comment]
What should I check?  What should I verify?  I know you can not connect to MySQL via TCP when you specified "localhost" and it is not a bug as I already explained.  Try "127.0.0.1".

**Comment by search5** [comment]
@methane. Put your mysql server and your Python program on different servers and test them. This is because Python programs connecting to the mysql server are not always on the same server.

**Comment by methane** [comment]
> Put your mysql server and your Python program on different servers and test them.

Why do you think I didn't do it?
I and many others do it with thousands of servers.

**Comment by search5** [comment]
I don't think I didn't. In my environment, I used 127.0.0.1 as the connection host, but I used a Docker container to specify a random port instead of the default port.

As a developer I would also like to thank you for building and distributing these nice libraries. Nevertheless, can you mistake mysql's famous behavior error and not, and check it request?

I am really sorry. If the same issue does not occur after various tests, you can configure the environment separately and send it as a video.

Can you please reconfirm the result shown in the video?

**Comment by methane** [comment]
> I don't think you have tested it by connecting to another server. In my environment, I used 127.0.0.1 as the connection host, but I used a Docker container to specify a random port instead of the default port.

That's the environment I test this library with many different MySQL (and MariaDB) server versions.

> Nevertheless, can you mistake mysql's famous behavior error and not, and check it request?

I can not get what do you mean.

> I am really sorry. If the same issue does not occur after various tests, you can configure the environment separately and send it as a video.
> 
> Can you please reconfirm the result shown in the video?

I don't want to do it.  I can not get totally what do you mean after my answer.

Do you think this very famous (2M downloads / month) can not to connect to MySQL server via TCP?
Have you really tested with `host="127.0.0.1"`?
What you should show is not video, but the simple reproducible code and the command line how do you start MySQL on Docker.

**Comment by evahteev** [comment]
@methane @search5 was fighting with the same behavior recently:
SQLAlchemy==1.3.13
mysqlclient==1.4.6

if connection created like:
connection = create_engine('mysql+mysqldb://user:pass@localhost:3306/db', pool_recycle=3600, pool_size=10, echo_pool=True)
mysqlclient is trying to connect using unix socket, causing:
OperationalError(2002, "Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)")
and unix socket is not there as mysql is actually running in docker exposing 3306 to the host. And that's not what you expect, as you assume specifying host and port in connection string will force tcp protocol.

Same time changing the connection string to:
connection = create_engine('mysql+mysqldb://user:pass@127.0.0.1:3306/db', pool_recycle=3600, pool_size=10, echo_pool=True)
works perfectly as mysqlclient is using tcp protocol now and not trying to connect thru the socket.
