### ISSUE TITLE
not able to install mysqlclient

### ISSUE THREAD

**Issue by mtrazakhan** [PyMySQL/mysqlclient-python#421]
![mysqlclienterror](https://user-images.githubusercontent.com/59005220/71657394-acaa2500-2d65-11ea-9d43-2fe640fe5f13.png)

**Comment by mddicicco** [comment]
I am having the same issue but on ARM processor
![image](https://user-images.githubusercontent.com/53273624/71682313-e7579180-2d54-11ea-8881-e8f80abee83a.png)

**Comment by mddicicco** [comment]
Fix is to install OpenSSL:
```
sudo update
sudo apt-get install openssl
```

**Comment by tacianosilva** [comment]
@mddicicco I had already installed openssl. So I installed the following libs:

`sudo apt install libssl-dev libffi-dev`

**Comment by mtrazakhan** [comment]
Thanks02.01.2020, 23:21, "mddicicco" <notifications@github.com>:Fix is to install OpenSSL:
sudo update
sudo apt-get install openssl

**Comment by EBII** [comment]
Same issue for solved on ubuntu  by add libssl-dev 
i think is due to different container and install of mariadb already depends libssl 
sudo apt install libssl-dev 
just need to update Readme on Pypi

**Comment by helderco** [comment]
I use homebrew and mariadb, to fix this I had openssl only as a keg, so we need to tell the compiler where it is:

```bash
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
```

**Comment by methane** [comment]
While `mysql_config` shows `-lssl -lz`, mysqlclient doesn't need them unless it is statically linked to libmysqlclient.

I removed `-lssl` in master branch already so no need to install libssl-dev, and no need to set LDFLAGS for homebrew.
