### ISSUE TITLE
Request: Rename class name from MySQLdb to mysqlclient

### ISSUE THREAD

**Issue by ikwyl6** [PyMySQL/mysqlclient-python#426]
### Describe the request

Generally when importing most packages in python, the import name is similar or the same as the pkg name. This has come up in one situation when I use ```pipreqs``` to create a ```requirements.txt``` file. When ```pipreqs``` is run, it cannot find mysqlclient pkg because it uses the import name in the python file to search for the package:
```
$ pipreqs . --print --debug
DEBUG: Found packages: {'MySQLdb'}
DEBUG: Found imports: MySQLdb
DEBUG: Getting packages information from Local/PyPI
DEBUG: Starting new HTTPS connection (1): pypi.python.org:443
DEBUG: https://pypi.python.org:443 "GET /pypi/MySQLdb/json HTTP/1.1" 301 122
DEBUG: Starting new HTTPS connection (1): pypi.org:443
DEBUG: https://pypi.org:443 "GET /pypi/MySQLdb/json HTTP/1.1" 404 152
DEBUG: Package MySQLdb does not exist or network problems
INFO: Successfully output requirements
```
### To Reproduce

run ```pipreqs .``` in the directory of package using mysqlclient/MySQLdb.

### Environment
```
$ pipreqs --version
0.4.10
```
- OS: xubuntu 16.10
- Python version: 3.8.1 
- mysqlclient version: 1.4.6

### Additional context
This is a request not abug report..

**Comment by methane** [comment]
It is big breaking change.  I don't want to do it.
