### ISSUE TITLE
installer must check prerequisites before installing

### ISSUE THREAD

**Issue by lsloan** [PyMySQL/mysqlclient-python#429]
### Describe bug

When running the installer, if prerequisites like the Python and MySQL development headers and libraries are not already installed, the installer fails with cryptic messages that are unclear to some users.

### To Reproduce

**Shell**

```sh
pip install mysqlclient
```

### Environment

**MySQL Client**

- OS (e.g. Windows 10, Ubuntu 20.04): Any

- Python (e.g. Homebrew Python 3.7.5): Any

- Connector/C (e.g. Homebrew mysql-client 8.0.18): Any

### Additional context

I've seen other installers perform checks to ensure the prerequisites are installed before running the compiler.  If prerequisites aren't available, then the installer gives clear, plain-English messages stating what needs to be installed before this installer can continue.  That avoids confusion caused by cryptic messages from the compiler.

**Comment by methane** [comment]
User can manually configure their system (e.g. C_INCLUDE_PATH, etc.) and the installer can not know compile will success or not without really compile.
