### ISSUE TITLE
Doesn't build on Windows

### ISSUE THREAD

**Issue by sparkyb** [PyMySQL/mysqlclient-python#432]
### Describe the bug

When I attempt to build on Windows (either `pip install mysqlclient` in a virtualenv or by cloning this Git repo and running `python setup.py bdist_wheel`), I get the following error:

`MySQLdb/_mysql.c(29): fatal error C1083: Cannot open include file: 'mysql.h': No such file or directory`

I have both the MySQL Connector/C 6.1.11 (from the archive) and MariaDB Connector/C 3.1.8 installed. However the paths in `site.cfg` and `setup_windows.py` are contradictory and so it finds neither. If I edit `setup_windows.py` and change `client` to `mysqlclient`, it builds correctly. With `client` set to `mariadbclient` I was also able to get it to work, but I had to change `connector` in `site.cfg` to `C:\Program Files (x86)\MariaDB\MariaDB Connector C` and remove `"mariadb"` from the end of the `library_dirs` and `include_dirs`. I would think that if the `connector` path is set to MySQL Connector/C 6.1, then the `client` should be set to `mysqlclient` so that it at least might build for someone who has the correct packages installed.

I realize building on Windows is hard, but the advice "Building mysqlclient on Windows is very hard. But there are some binary wheels you can install easily." is unhelpful if there aren't wheels for your platform and there's no information at all about how to build your own wheel. Specifically, there are no 32-bit (x86) wheels, only x64 wheels, on PyPI and I'm running the x86 version of Python 3.7. I was able to find [unofficial wheels](https://www.lfd.uci.edu/~gohlke/pythonlibs/#mysqlclient), but I would rather not reference that in my requirements file. Having official x86 wheels on PyPI would be the best resolution. But also, it would be nice if there were at least a chance it could build if I had the right packages installed, and at least some documentation of what to install. Is there some connector that could be installed to make it build as-is, or are those paths designed for a custom layout on the machine where the official wheels are built?

Since it does seem to build with multiple connectors, It would be nice if it could search for a suitable connector installed out of the few known to work options and use the first available. Before I go and do the work, would you accept a pull request where I attempt to do this?

### Environment

**MySQL Server**

- Server OS: Windows 10
- Server Version: MySQL 5.7.30

**MySQL Client**

- OS: Windows 10

- Python: CPython 3.7.3 x86

**Comment by methane** [comment]
It is impossible to build the library automatically because users' environments are varied.  You should pay your effort to build the library.  I don't want to support everyone.  I'm not free tech support.

But I can give you some hint.  If you want to use mariadb client and static link it, you can follow my workflow.

* Memo I wrote when I build v1.4.0: https://github.com/PyMySQL/mysqlclient-python/wiki/Windows-v1.4.0
* Current workflow: https://github.com/PyMySQL/mysqlclient-build/blob/master/.github/workflows/windows.yaml

**Comment by alexbprofit** [comment]
**Solution for mysql**
Install mysql server, then go to the include directory for mysql server, then copy folder mysql and header files into folder, example 
```C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include```
then comment in setup_windows.py into mysqlclent directory line ``` client = 'mariadbclient' ``` and uncomment previous line, then copy the
file mysqlclient.lib which stored in mysql server lib directory into 
```C:\Program Files (x86)\Windows Kits\10\Lib\10.0.16299.0\ucrt\x64.``` 
this solution worked for me.
![image](https://user-images.githubusercontent.com/57172679/113504127-be691200-953e-11eb-92a5-f529fab2f39e.png)
