### ISSUE TITLE
error: ssl_mode not supported by client library

### ISSUE THREAD

**Issue by thorstenkampe** [PyMySQL/mysqlclient-python#439]
### Describe the bug

I get an error trying to specify `ssl_mode`

### To Reproduce

```py
from MySQLdb import _mysql
_mysql.connect(user='root', passwd='password', ssl_mode='REQUIRED')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MySQLdb._exceptions.NotSupportedError: MySQL client library does not support ssl_mode specification
```

### Environment

**MySQL Client**

- OS: Windows 10

- Python: Python 3.8.3 (vanilla install via Scoop)

- Connector/C (e.g. Homebrew mysql-client 8.0.18): mysqlclient 2.0.1 (installed via `pip`)
```
>>> get_client_info()
'10.4.3'
```

**Comment by methane** [comment]
Windows wheel uses MariaDB Connector/C because MySQL Connector/C doesn't support static link.
And MariaDB Connector/C doesn't have ssl_mode option.

**Comment by thorstenkampe** [comment]
Installing via `pip` is the standard way to install `mysqlclient` on all platforms. I think it would make sense to update the documentation and mention that the Windows wheel does not support the `ssl_mode` option.
