### ISSUE TITLE
Incompatibility with django logging of queries.

### ISSUE THREAD

**Issue by daillouf** [PyMySQL/mysqlclient-python#441]
Hello, 

I have noticed in version 2.0.1 that I had the same problem of queries logged as «None» in Django,  as in https://stackoverflow.com/questions/54574499/django-logging-django-db-backends-returns-0-000-none-args-none-message

I fixed the logging problem by downgrading mysqlclient as well. I had the 1.4.6 before

I'm using pip 20.1.1

django is 1.11.6 ( i know, old )

And this is on python docker image with the tag ` python:3.5`

which I know is old

I don't have much more detail for now. Thanks a lot to all of you contributors. 
I can help for the review later on if it happens.

**Comment by methane** [comment]
Replied in SO.

**Comment by daillouf** [comment]
thank you methane, I just tried django 1.11.29 the latest patch, and it didn't fix it. maybe the bugfix didn't make it to the 1.11 branch

**Comment by daillouf** [comment]
Are you closing because 
«it's a major upgrade, we don't care if we break retro-compatibility» ?

**Comment by methane** [comment]
See https://github.com/PyMySQL/mysqlclient-python/blob/master/HISTORY.rst#whats-new-in-200

<img width="757" alt="スクリーンショット 2020-08-04 10 54 20" src="https://user-images.githubusercontent.com/199592/89244301-17477a00-d641-11ea-9e7f-e57733bdc6a9.png">

**Comment by daillouf** [comment]
Oh okay no problem, thank you methane. I'll update my SO post to include this. 

Have a good day and be safe
