### ISSUE TITLE
Bug in python 3.6 version, Byteconversion

### ISSUE THREAD

**Issue by Kamhamea** [PyMySQL/mysqlclient-python#444]
`MySQLdb/__init__.py`

Line 122-123

```
def Binary(x):
     return bytes(x, encoding='utf-8')
```

With "return bytes(x)" an exception is created

Bye

**Comment by Kamhamea** [comment]
Sorry return bytes(x, encoding='utf8')

**Comment by domielias** [comment]
@Kamhamea Hi, do you have a example of how to implement this? I'm reading the documentation but i don't get it. If you can give me you telegram or discord?

**Comment by Kamhamea** [comment]
This line is just a remnant of Py2 code that nobody noticed yet. It has to be translated into Py3. [See here.](https://stackoverflow.com/questions/29751751/string-to-bytes-in-both-python-2-and-3/29751882#29751882) 

This function is only called if you want to store a string in a [BinaryField](https://www.geeksforgeeks.org/binaryfield-django-models/) in django which rarely happens.

**Comment by Kamhamea** [comment]
Sorry I just noticed that the file namis not correctly displayed in my first notice. It is about [this file](https://github.com/PyMySQL/mysqlclient-python/blob/master/MySQLdb/__init__.py) line 123.

**Comment by methane** [comment]
> This function is only called if you want to store a string in a [BinaryField](https://www.geeksforgeeks.org/binaryfield-django-models/) in django which rarely happens.

You can not store text in binary field. You need to convert text into binary with `txt.encode()`.
