### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [PyMySQL/mysqlclient-python#445]
**Summary**
Installing mysqlclient-python on aarch64 via pip using command "pip3 install mysqlclient" tries to build wheel from source code.

**Problem description**
mysqlclient-python doesn't have wheel for aarch64 on PyPI repository. So, while installing mysqlclient-python via pip on aarch64, pip builds wheel for same resulting in it takes more time to install mysqlclient-python. Making wheel available for aarch64 will benefit aarch64 users by minimizing mysqlclient-python installation time.

**Expected Output**
Pip should be able to download mysqlclient-python wheel from PyPI repository rather than building it from source code.

@mysqlclient-python-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make mysqlclient-python wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by methane** [comment]
https://github.com/PyMySQL/mysqlclient-python/issues/74#issuecomment-698217473
