### ISSUE TITLE
Installation is never smooth

### ISSUE THREAD

**Issue by timluther** [PyMySQL/mysqlclient-python#446]
Hi, 
  Each time I need to install this package, it's always a bit of a chore. It never seems to install smoothly and I'm not sure why this is. Are the developers aware of issues of various platforms that mean the normal, expected way of installed a python package (i.e.
sudo python3 -m pip install mysqlclient) just doesn't work? Can you possibly look into this in order to create a smooth and painless installation?

**Comment by methane** [comment]
See https://github.com/PyMySQL/mysqlclient-python/issues/74#issuecomment-698217473
