### ISSUE TITLE
Installing within venv on windows

### ISSUE THREAD

**Issue by mddicicco** [PyMySQL/mysqlclient-python#447]
I don't have logs currently to attach to this but I will replicate the issue later and attach them.

This occurred on python 3.8.5 and 3.8.6 amd64 on win32.
When attempting to install mysqlclient-2.0.1 under a venv it gives the "mysql.h" not found error. The path it is seaching for "mysql.h" is "Program Files (x86)/MySQL/MySQL Connector C 6.1/includes/mariadb".  Trying to install .whl files gives "Wheel not supported on this platform" error. 

This error does not occur if installing to the base interpreter, just venv's.

**Comment by methane** [comment]
I don't support building issue, because they are environment specific.
If you can not use wheel, you should manage to build by yourself.
