### ISSUE TITLE
DateTime_or_None returns datetime.date in some scenarios

### ISSUE THREAD

**Issue by brsc2909** [PyMySQL/mysqlclient-python#451]
I'm raising this as a bug as I think this is not the expected behavior or what should be expected. From the name i would expect it to return either a `datetime.datetime` type or `None` however if a date column is passed to it it returns a `datetime.date` type

To replicate:
```python
from MySQLdb.converters import DateTime_or_None

if __name__ == '__main__':
    date_str_1 = '2020-02-13'
    date_str_2 = '2020-02-13 01:01:01'

    date_return = DateTime_or_None(date_str_1)
    print(type(date_return))
    date_return = DateTime_or_None(date_str_2)
    print(type(date_return))
```

The offending code in this case is obvious. 
```python

def DateTime_or_None(s):
    try:
        if len(s) < 11:
            return Date_or_None(s)
.
.
.
```

**Comment by methane** [comment]
Please don't use it. It is intended to be used in converter. So what user expects is not matter.
