### ISSUE TITLE
DROP PROCEDURE IF EXISTS produces ProgrammingError instead of Warning

### ISSUE THREAD

**Issue by Regner** [PyMySQL/mysqlclient-python#48]
Maybe this is more of a question than an actual issue, sorry about that.

I am attempting to solve this issue: https://github.com/evetrivia/thanatos/issues/15

Which errors out when running the following SQL: https://github.com/evetrivia/thanatos/tree/master/thanatos/database/procs

The MySQL documentation says that the IF EXISTS clause is an extension and that it will throw an error. OK fine. Everything online seems to say it should throw a Warning exception though, not a ProgramingError.

Reference:
* https://stackoverflow.com/questions/4143686/python-and-mysqldb-using-drop-table-if-exists-seems-to-throw-exception
* https://stackoverflow.com/questions/20080153/mysql-if-exists-command-causes-an-error-when-used-in-python

Is there a reason why this causes a ProgrammingError instead of a Warning? What is the best way to handle it?

**Comment by methane** [comment]
> Which errors out when running the following SQL: https://github.com/evetrivia/thanatos/tree/master/thanatos/database/procs

I can see some sql files.  Which one?

**Comment by methane** [comment]
You can customize Cursor class.

```
import MySQLdb.cursors
MySQLdb.cursors.BaseCursor._defer_warnings = True
```

**Comment by methane** [comment]
@Regner Could you try #57 ?

**Comment by Regner** [comment]
Sorry, been really busy. Will try and check it out this weekend.
