### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by femtotrader** [PyMySQL/mysqlclient-python#50]
Hello,

I'm using Mac OS X 10.10 Anaconda 3

    $ pip install mysqlclient
    Collecting mysqlclient
      Using cached mysqlclient-1.3.6.tar.gz
    Installing collected packages: mysqlclient
      Running setup.py install for mysqlclient
    Successfully installed mysqlclient-1.3.6
    pc:blaze scls$ ipython
    Python 3.4.3 |Anaconda 2.3.0 (x86_64)| (default, Mar  6 2015, 12:07:41)
    Type "copyright", "credits" or "license" for more information.

    IPython 3.2.1 -- An enhanced Interactive Python.
    Anaconda is brought to you by Continuum Analytics.
    Please check out: http://continuum.io/thanks and https://anaconda.org
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

    In [1]: import MySQLdb
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-2-dd22983d5391> in <module>()
    ----> 1 import MySQLdb

    //anaconda/lib/python3.4/site-packages/MySQLdb/__init__.py in <module>()
         17 from MySQLdb.release import __version__, version_info, __author__
         18
    ---> 19 import _mysql
         20
         21 if version_info != _mysql.version_info:

    ImportError: dlopen(//anaconda/lib/python3.4/site-packages/_mysql.so, 2): Library not loaded: libmysqlclient.18.dylib
      Referenced from: //anaconda/lib/python3.4/site-packages/_mysql.so
      Reason: image not found

Kind regards

**Comment by methane** [comment]
You may have libmysqlclient installed and use it while building.
But you may not use libmysqlclient for dynamic linking.

There are some ways to dynamic link to libmysqlclient.
Easiest one is add symlink to `/usr/local/lib`.For example:

```console
cd /usr/local/lib
ln -s /path/to/you/install/mysql/lib/libmysqlclient.18.dylib
```

You can see more info from [man page of dyld](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/dyld.1.html)
