### ISSUE TITLE
New release to fix regression?

### ISSUE THREAD

**Issue by timgraham** [PyMySQL/mysqlclient-python#52]
Hi, for the Django test suite we are currently pinned to an older version of mysqlclient due to a regression when using a cursor as a context manager (fixed by 641a2eb5a0db13f7d901a5fb221c623ebbd1ced9, I think). Would it be possible to get a new release soon? Thanks!

**Comment by adamchainz** [comment]
+1 We'd like a PyPI release for the date perf improvements from #43

**Comment by brianmay** [comment]
Also looks like we need a new release to fix #24.

**Comment by brianmay** [comment]
My mistake, looks like #24 got into 1.3.6; had thought that 1.3.4 was the latest release.

**Comment by methane** [comment]
I've pushed 1.3.7 to PyPI.
