### ISSUE TITLE
Not working with python 3.5

### ISSUE THREAD

**Issue by piyushspss** [PyMySQL/mysqlclient-python#54]
This is the error I get when I try installing mysqlclient. I am using Windows and python 3.5.

```
Installing 'mysqlclient'
Collecting mysqlclient
  Using cached mysqlclient-1.3.6.tar.gz
Installing collected packages: mysqlclient
  Running setup.py install for mysqlclient
    Complete output from command "c:\users\buccaneer\documents\visual studio            2013\Projects\del1\del1\envrm\Scripts\python.exe" -c "import setuptools, tokenize;__file__='C:\\Users\\BUCCAN~1\\AppData\\Local\\Temp\\pip-build-wuhkxhu3\\mysqlclient\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\BUCCAN~1\AppData\Local\Temp\pip-3jbluuk2-record\install-record.txt --single-version-externally-managed --compile --install-headers "c:\users\buccaneer\documents\visual studio 2013\Projects\del1\del1\envrm\include\site\python3.5\mysqlclient":
running install
running build
running build_py
creating build
creating build\lib.win32-3.5
copying _mysql_exceptions.py -> build\lib.win32-3.5
creating build\lib.win32-3.5\MySQLdb
copying MySQLdb\__init__.py -> build\lib.win32-3.5\MySQLdb
copying MySQLdb\compat.py -> build\lib.win32-3.5\MySQLdb
copying MySQLdb\converters.py -> build\lib.win32-3.5\MySQLdb
copying MySQLdb\connections.py -> build\lib.win32-3.5\MySQLdb
copying MySQLdb\cursors.py -> build\lib.win32-3.5\MySQLdb
copying MySQLdb\release.py -> build\lib.win32-3.5\MySQLdb
copying MySQLdb\times.py -> build\lib.win32-3.5\MySQLdb
creating build\lib.win32-3.5\MySQLdb\constants
copying MySQLdb\constants\__init__.py -> build\lib.win32-3.5\MySQLdb\constants
copying MySQLdb\constants\CR.py -> build\lib.win32-3.5\MySQLdb\constants
copying MySQLdb\constants\FIELD_TYPE.py -> build\lib.win32-3.5\MySQLdb\constants
copying MySQLdb\constants\ER.py -> build\lib.win32-3.5\MySQLdb\constants
copying MySQLdb\constants\FLAG.py -> build\lib.win32-3.5\MySQLdb\constants
copying MySQLdb\constants\REFRESH.py -> build\lib.win32-3.5\MySQLdb\constants
copying MySQLdb\constants\CLIENT.py -> build\lib.win32-3.5\MySQLdb\constants
running build_ext
building '_mysql' extension
error: Unable to find vcvarsall.bat
```

**Comment by leohipp** [comment]
The reported problem with vcvarsall.bat missing goes away if you install Visual Studio 14.0 with Python Tools for Visual Studio, which is an option under Programming Languages selection.

However, thereafter another problem pops up reelated to missing 'my_config.h':
    building '_mysql' extension
    creating build\temp.win32-3.5
    creating build\temp.win32-3.5\Release
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Dversion_info=(1,3,6,'final',1) -D__version__=1.3.6 "-IC:\Program Files (x86)\MySQL\MySQL Connector C 6.1\include" "-Ic:\apps\python 3.5\include" "-Ic:\apps\python 3.5\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\WindowsKits\NETFXSDK\4.6\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" /Tc_mysql.c /Fobuild\temp.win32-3.5\Release\_mysql.obj /Zl
    _mysql.c
    _mysql.c(29): fatal error C1083: Cannot open include file: 'my_config.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

**Comment by methane** [comment]
Building MySQL-python on Windows is hard.  You should build from source instead of pip install since you need to edit setup.cfg file.

To make pip installable, I built binary wheels for Windows.
But I haven't built wheel for Python 3.5 yet.  I hope I can build it in near future.

**Comment by leohipp** [comment]
Adding to my own post: my_config.h becomes available after installing MySQL with development option. But even then the building process fails because it looks for the file from C:\Program Files (x86)\MySQL\MySQL Connector C 6.1\include although it becomes installed into C:\Program Files\MySQL\MySQL Connector.C 6.1\include.

Perhaps I'll wait until mysqlclient‑1.3.6‑cp35‑none‑win32.whl becomes available at http://www.lfd.uci.edu/~gohlke/pythonlibs/#mysqlclient...

**Comment by methane** [comment]
[MySQL Connector/C](https://dev.mysql.com/downloads/connector/c/) doesn't support VS 2015 yet.

**Comment by boolbag** [comment]
Hi guys, same problem here. 
Has anyone found out if uninstalling Python tools from VS2015 makes the problem disappear?
Or do we just have to wait for the 3.5 package?

For me Python in VS is nice-to-have but not have-to-have.

**Comment by methane** [comment]
I can't build extension module for Python 3.5 for now.
I hope new MySQL Connector/C supports VS 2015...

**Comment by vanflymen** [comment]
Anyone figured this out yet? I'm using Windows 10, VS 2015, Python 3.5 64bit.

**Comment by methane** [comment]
ref: http://bugs.mysql.com/bug.php?id=78282

This bug should be fixed for building Python's mysqlclient on Python 3.5

**Comment by vanflymen** [comment]
methane, can you explain how? I'm still having difficulty. I'm not using pip rather compiling the project using `python setup.py install` after modifying `site.cfg` to point to the correct location of MySQL Connector.

**Comment by methane** [comment]
Python 3.5 uses VS2015.
But current MySQL can't compile under VS2015.
So I can't build mysqlclient-python for Python 3.5 without VCRT mismatch.

Since I'm not Windows expert, I can't build dual-VCRT library.
And I don't want to support it if I can build it.

**Comment by boolbag** [comment]
Like methane, error with VS2015 while trying to install via PyCharm:

```error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2```

**Comment by etsalah** [comment]
It doesn't work for python3.5 on ubuntu 15.04 too. Hand to edit /usr/bin/pip3 so that !#/usr/bin/python3.5 was now !#/usr/bin/python3 before it was able to install

**Comment by GlobalHelp** [comment]
Up ! Nobody has answer???

**Comment by methane** [comment]
This is a issue of MySQL.
I can't do anything until they make a new release.

**Comment by jokey2k** [comment]
You can just link against the version shipped with mysql, I did it for py3.5/win64, linked against mysqlclient from mysql 5.7.10 http://pyside.markus-ullmann.de/mysqlclient-win/mysqlclient-1.3.7-cp35-none-win_amd64.whl

**Comment by ntung** [comment]
Thanks @jokey2k . It works for me. Your suggestion saved me much of lost time.
I am using Windows 7 and Python 3.5 installed via Anaconda.

**Comment by Moodjbow** [comment]
@jokey2k: strangely enough pip install <your-link> exits with error "...is not a supported wheel on this platform". I have win7 x64 and python 3.5, but when I run python.exe it is a *32 process. Can this be a reason and when yes, where can I find a 32-bit wheel.
In general all three mysql clients advertised by django are NOT compatible with python 3.5. Great! It was nowhere written, and now I am stuck in a middle of a data migration project. Feels like screaming...

**Comment by ngreeney** [comment]
Thanks @jokey2k! That was just what I have been looking for!

**Comment by jokey2k** [comment]
You're welcome :-)

**Comment by PhilippePlagnol** [comment]
Thanks @jokey2k ! 
is it also possible to have mysqlclient-1.3.7-cp35-none-win32.whl ?

**Comment by crgkhn** [comment]
Thanks @jokey2k it works for me.

**Comment by cgohlke** [comment]
I put 32 and 64-bit wheels for Python 3.5 at <http://www.lfd.uci.edu/~gohlke/pythonlibs/#mysqlclient>. These are linked to the multi-threaded DLL runtime (/MD) versions of mysqlclient 5.7.11 for VC14.

**Comment by adanilins** [comment]
Than You so mutch!!!

**Comment by jptomo** [comment]
FYI:

MySQL 5.6.29 was released [Changes in MySQL 5.6.29 (2016-02-05)](https://dev.mysql.com/doc/relnotes/mysql/5.6/en/news-5-6-29.html)

and from above, it seem to have been resolved VS2015 problem.

**Comment by methane** [comment]
I'm waiting new release of MySQL Connector/C

**Comment by PhilippePlagnol** [comment]
thank you so much !!!

**Comment by boolbag** [comment]
Works a charm via pip install.
Wondering if anyone knows a way to install the wheel in a virtualenv in PyCharm?
Otherwise no worries, I'll just make it available to the whole of 3.5.

**Comment by akbarpn136** [comment]
Thanks @jokey2k. It works for me. I am using Windows 7 64bit and Python 3.5 installed via Anaconda.

**Comment by ryanhalabi** [comment]
Can someone explain @jokey2k 's solution step by step?  Thanks.

**Comment by methane** [comment]
@ryanhalabi 

1. Install MySQL **server** (amd64) with client library.
2. Build mysqlclient-python (amd64) with it
3. Uninstall MySQL server.
4. Install MySQL **server** (x86) with client library.
5. Build mysqlclient-python (x86) with it
6. Uninstall MySQL server

I know it, but I don't want to do it...
Why MySQL developer don't release MySQL Connector/C for such a long time?
It's very annoying.

**Comment by Ihure** [comment]
Thanks @jokey2k the solution worked for me. windows 10, 64 bit system and python 3.5

**Comment by TalatCikikci** [comment]
thanks @cgohlke ; +100 internets to you :+1:

**Comment by kryogenic** [comment]
thank you @cgohlke for linking to the 32-bit .whl :D

**Comment by kreuzberger** [comment]
If you get the error with vcvarsall.bat you could also try to set these environment variables:
set DISTUTILS_USE_SDK=1
set MSSdk=1
set PY_VCRUNTIME_REDIST="No Thanks"
this works for msvc2013

for later msvc you must set PY_VCRUNTIME_REDIST to a correct path.

This is general the case if you compile modules.

the missing include is fixed after extracting mysql with include directory and setting the INCLUDE environment variable for cl correctly. (also linker variable for sure)

I got it only worky by setting the code page to normal windows code page ("chcp 1252"). Normally i must set it to 65001 cause some modules require this to work.

**Comment by methane** [comment]
@kreuzberger Do you mean use msvc2013 (VC13) to build Python 3.5 (based on VC14 runtime) extension module?  Is it really safe?

**Comment by kreuzberger** [comment]
no, sorry for the misunderstanding. I compile python myself with vs2013 to. mixing is no good idea.

**Comment by methane** [comment]
Hmmm.
Why Oracle doesn't release MySQL Connector/C for VC14 for such a long time....
Very annoying...

**Comment by carloliwanag** [comment]
Hi @jokey2k. I am new to django, can you please create the instruction on how to use the whl file you have provided? thanks!

**Comment by methane** [comment]
I've managed to build by myself and uploaded binary wheel for CPython 3.5 amd64.
(Building all on Windows from source was not a fun task...)

Anyone try this?

https://github.com/PyMySQL/mysqlclient-python/releases/download/1.3.7/mysqlclient-1.3.7-cp35-cp35m-win_amd64.whl

**Comment by methane** [comment]
I succeeded to build MySQL clientlib in MySQL 5.7.15 in this weekend.
I'll release next bugfix version with Python 3.5 Win64 binary wheel.

**Comment by ningquec** [comment]
@methane . I tried your binary wheel but it did't work.
ERROR: mysqlclient-1.3.7-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.

**Comment by methane** [comment]
@ningquec Do you use CPython 3.5 Win64?

**Comment by ningquec** [comment]
Yes, i install it in virtual env. but it worked while not venv.

**Comment by methane** [comment]
`pip install -U pip setuptools wheel` before `pip install mysqlclient-1.3.7-cp35-cp35m-win_amd64.whl`?

**Comment by jameskandau** [comment]
i did it this way.Downloaded the mysqlclient.ie mysqlclient-1.3.4-cp34-none-win_amd64.whl
saved it in my downloads. Open your work folder and activate your virtualenv. then run this commad.
pip install C:/users/your/user/to/where/mysqlclient/is and thats it.
If using django then config your cridentials in settings file.Happy wheeling

**Comment by methane** [comment]
I've managed to build binary wheel for Python 3.5 and 2.7

https://github.com/PyMySQL/mysqlclient-python/releases/tag/1.3.8

Anyone try these wheel?

**Comment by oliverqg** [comment]
@jameskandau your suggestion worked for me.  I installed mysqlclient-1.3.7-cp35-none-win_amd64.whl and stopped getting the error.  I'm using Win10, Python 3.5, Django 1.9.6. So far so good.  Thanks!

**Comment by jameskandau** [comment]
Great if it worked for you. Happy coding

**Comment by Steven-N** [comment]
Thank you so much @cgohlke you saved me. I've spent an embarrassing amount of hours today getting this working.

**Comment by Borkason** [comment]
> I've managed to build binary wheel for Python 3.5 and 2.7
> https://github.com/PyMySQL/mysqlclient-python/releases/tag/1.3.8
> Anyone try these wheel?

Python 3.5.2 64-Bit crashes with that binary. Probably noteworthy that I am running MariaDB.


> Faulting application name: python.exe, Version: 3.5.1150.1013, time stamp: 0x576f0390
> Faulting module name: python35.dll, Version: 3.5.1150.1013, time stamp: 0x576f037c
> Exception code: 0xc0000005
> Fault offset: 0x00000000000e631c

**Comment by methane** [comment]
Thanks.

I gave up about building mysqlclient.lib by myself.
I'll wait until Oracle releases new MySQL Connector/C.

**Comment by pyy** [comment]
Hello @methane , I build mysqlclient.lib under VS2015 and use this file to build mysqlclient-python 1.3.9 successfully.  I aslo put my steps in the wiki part: https://github.com/PyMySQL/mysqlclient-python/wiki/Building-mysqlclient.lib-on-Windows-with-VS2015

May I ask are these steps wrong? Are there big hidden bugs?  Why do you give up building mysqlclient.lib by yourself? Thank you.

**Comment by methane** [comment]
> May I ask are these steps wrong?

I cannot. I don't know right step.

> Are there big hidden bugs?

I don't know.  I don't use Windows. I can't find hidden bugs by myself.

> Why do you give up building mysqlclient.lib by yourself?

Since I don't use Windows.  I'm not Windows expert.  I have a lot of other things to use my time.

**Comment by methane** [comment]
Please ask to Oracle, not me.

**Comment by emepe** [comment]
I was having the same issue and it was resolved after I updated pip to latest version (pip 9.0.1) and then it worked with the wheel file available at http://www.lfd.uci.edu/~gohlke/pythonlibs/#mysqlclient

**Comment by clustersnake** [comment]
Thank you very much @emepe. I'm using python 3.5.2 and just downloaded and installed mysqlclient without problems

**Comment by edvbb** [comment]
@clustersnake I use the same version of python
please, tell me what wheel did you install?

**Comment by clustersnake** [comment]
[image: Inline image 1]
because I had installed the 32bits version of python 3.5... Now I moved to
3.6 but django runserver breaks 7 out of 10 times I run it :-(

**Comment by kinsleykajiva** [comment]
well this worked for me:

    pip install mysqlclient

this is for python 3.x in windows 7 x64

**Comment by fengshuo211** [comment]
I am using pycharm virtual env and experiencing this problem. 
After I upgrade my pip to `9.0.1` and then `pip install mysqlclient`, everything works fine. Thanks @kinsleykajiva

**Comment by SeppPenner** [comment]
For me, not even installing the latest version **MySQL Installer 8.0.13** did work.

I'm getting:

```cmd
Collecting mysqlclient
  Using cached https://files.pythonhosted.org/packages/ec/fd/83329b9d3e14f7344d1cb31f128e6dbba70c5975c9e57896815dbb1988ad/mysqlclient-1.3.13.tar.gz
Building wheels for collected packages: mysqlclient
  Running setup.py bdist_wheel for mysqlclient: started
  Running setup.py bdist_wheel for mysqlclient: finished with status 'error'
  Complete output from command "c:\program files (x86)\python\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\tim\\AppData\\Local\\Temp\\pip-install-7ub252fz\\mysqlclient\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\tim\AppData\Local\Temp\pip-wheel-rc2q0_1s --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.7
  copying _mysql_exceptions.py -> build\lib.win32-3.7
  creating build\lib.win32-3.7\MySQLdb
  copying MySQLdb\__init__.py -> build\lib.win32-3.7\MySQLdb
  copying MySQLdb\compat.py -> build\lib.win32-3.7\MySQLdb
  copying MySQLdb\connections.py -> build\lib.win32-3.7\MySQLdb
  copying MySQLdb\converters.py -> build\lib.win32-3.7\MySQLdb
  copying MySQLdb\cursors.py -> build\lib.win32-3.7\MySQLdb
  copying MySQLdb\release.py -> build\lib.win32-3.7\MySQLdb
  copying MySQLdb\times.py -> build\lib.win32-3.7\MySQLdb
  creating build\lib.win32-3.7\MySQLdb\constants
  copying MySQLdb\constants\__init__.py -> build\lib.win32-3.7\MySQLdb\constants
  copying MySQLdb\constants\CLIENT.py -> build\lib.win32-3.7\MySQLdb\constants
  copying MySQLdb\constants\CR.py -> build\lib.win32-3.7\MySQLdb\constants
  copying MySQLdb\constants\ER.py -> build\lib.win32-3.7\MySQLdb\constants
  copying MySQLdb\constants\FIELD_TYPE.py -> build\lib.win32-3.7\MySQLdb\constants
  copying MySQLdb\constants\FLAG.py -> build\lib.win32-3.7\MySQLdb\constants
  copying MySQLdb\constants\REFRESH.py -> build\lib.win32-3.7\MySQLdb\constants
  running build_ext
  building '_mysql' extension
  creating build\temp.win32-3.7
  creating build\temp.win32-3.7\Release
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Dversion_info=(1,3,13,'final',0) -D__version__=1.3.13 "-IC:\Program Files (x86)\MySQL\MySQL Connector C 6.1\include" "-Ic:\program files (x86)\python\include" "-Ic:\program files (x86)\python\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tc_mysql.c /Fobuild\temp.win32-3.7\Release\_mysql.obj /Zl
  _mysql.c
  _mysql.c(29): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "mysql.h": No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
  
  ----------------------------------------
  Running setup.py clean for mysqlclient
Failed to build mysqlclient
Installing collected packages: mysqlclient
  Found existing installation: mysqlclient 1.3.12
    Uninstalling mysqlclient-1.3.12:
      Successfully uninstalled mysqlclient-1.3.12
  Running setup.py install for mysqlclient: started
    Running setup.py install for mysqlclient: finished with status 'error'
    Complete output from command "c:\program files (x86)\python\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\tim\\AppData\\Local\\Temp\\pip-install-7ub252fz\\mysqlclient\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\tim\AppData\Local\Temp\pip-record-nibnj0lm\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    copying _mysql_exceptions.py -> build\lib.win32-3.7
    creating build\lib.win32-3.7\MySQLdb
    copying MySQLdb\__init__.py -> build\lib.win32-3.7\MySQLdb
    copying MySQLdb\compat.py -> build\lib.win32-3.7\MySQLdb
    copying MySQLdb\connections.py -> build\lib.win32-3.7\MySQLdb
    copying MySQLdb\converters.py -> build\lib.win32-3.7\MySQLdb
    copying MySQLdb\cursors.py -> build\lib.win32-3.7\MySQLdb
    copying MySQLdb\release.py -> build\lib.win32-3.7\MySQLdb
    copying MySQLdb\times.py -> build\lib.win32-3.7\MySQLdb
    creating build\lib.win32-3.7\MySQLdb\constants
    copying MySQLdb\constants\__init__.py -> build\lib.win32-3.7\MySQLdb\constants
    copying MySQLdb\constants\CLIENT.py -> build\lib.win32-3.7\MySQLdb\constants
    copying MySQLdb\constants\CR.py -> build\lib.win32-3.7\MySQLdb\constants
    copying MySQLdb\constants\ER.py -> build\lib.win32-3.7\MySQLdb\constants
    copying MySQLdb\constants\FIELD_TYPE.py -> build\lib.win32-3.7\MySQLdb\constants
    copying MySQLdb\constants\FLAG.py -> build\lib.win32-3.7\MySQLdb\constants
    copying MySQLdb\constants\REFRESH.py -> build\lib.win32-3.7\MySQLdb\constants
    running build_ext
    building '_mysql' extension
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Dversion_info=(1,3,13,'final',0) -D__version__=1.3.13 "-IC:\Program Files (x86)\MySQL\MySQL Connector C 6.1\include" "-Ic:\program files (x86)\python\include" "-Ic:\program files (x86)\python\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /Tc_mysql.c /Fobuild\temp.win32-3.7\Release\_mysql.obj /Zl
    _mysql.c
    _mysql.c(29): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "mysql.h": No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    
    ----------------------------------------
  Rolling back uninstall of mysqlclient
```

My pip version is `pip 18.1 from c:\program files (x86)\python\lib\site-packages\pip (python 3.7)`

**Comment by all3f0r1** [comment]
@SeppPenner have you tried with this version of mysqlclient: https://pyside.markus-ullmann.de/mysqlclient-win/mysqlclient-1.3.7-cp35-none-win_amd64.whl? To install a whl, just pip install [url], worked for me.

**Comment by SeppPenner** [comment]
@all3f0r1 Well, it worked for me somehow but I do not know what I changed exactly. (Running simply ```pip install mysqlclient```).

Maybe I updated pip like @sefeng211 told to do...

**Comment by ranierande** [comment]
> This is the error I get when I try installing mysqlclient. I am using Windows and python 3.5.
> 
> ```
> Installing 'mysqlclient'
> Collecting mysqlclient
>   Using cached mysqlclient-1.3.6.tar.gz
> Installing collected packages: mysqlclient
>   Running setup.py install for mysqlclient
>     Complete output from command "c:\users\buccaneer\documents\visual studio            2013\Projects\del1\del1\envrm\Scripts\python.exe" -c "import setuptools, tokenize;__file__='C:\\Users\\BUCCAN~1\\AppData\\Local\\Temp\\pip-build-wuhkxhu3\\mysqlclient\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\BUCCAN~1\AppData\Local\Temp\pip-3jbluuk2-record\install-record.txt --single-version-externally-managed --compile --install-headers "c:\users\buccaneer\documents\visual studio 2013\Projects\del1\del1\envrm\include\site\python3.5\mysqlclient":
> running install
> running build
> running build_py
> creating build
> creating build\lib.win32-3.5
> copying _mysql_exceptions.py -> build\lib.win32-3.5
> creating build\lib.win32-3.5\MySQLdb
> copying MySQLdb\__init__.py -> build\lib.win32-3.5\MySQLdb
> copying MySQLdb\compat.py -> build\lib.win32-3.5\MySQLdb
> copying MySQLdb\converters.py -> build\lib.win32-3.5\MySQLdb
> copying MySQLdb\connections.py -> build\lib.win32-3.5\MySQLdb
> copying MySQLdb\cursors.py -> build\lib.win32-3.5\MySQLdb
> copying MySQLdb\release.py -> build\lib.win32-3.5\MySQLdb
> copying MySQLdb\times.py -> build\lib.win32-3.5\MySQLdb
> creating build\lib.win32-3.5\MySQLdb\constants
> copying MySQLdb\constants\__init__.py -> build\lib.win32-3.5\MySQLdb\constants
> copying MySQLdb\constants\CR.py -> build\lib.win32-3.5\MySQLdb\constants
> copying MySQLdb\constants\FIELD_TYPE.py -> build\lib.win32-3.5\MySQLdb\constants
> copying MySQLdb\constants\ER.py -> build\lib.win32-3.5\MySQLdb\constants
> copying MySQLdb\constants\FLAG.py -> build\lib.win32-3.5\MySQLdb\constants
> copying MySQLdb\constants\REFRESH.py -> build\lib.win32-3.5\MySQLdb\constants
> copying MySQLdb\constants\CLIENT.py -> build\lib.win32-3.5\MySQLdb\constants
> running build_ext
> building '_mysql' extension
> error: Unable to find vcvarsall.bat
> ```

how

**Comment by ranierande** [comment]
how you solve this error?

**Comment by ankitjaadoo** [comment]
I am using python 3.8.5, django 2.2.2 in red hat linux environment and unable to run the command python manage.py runserver. getting the following error - 

File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
ModuleNotFoundError: No module named 'MySQLdb'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/utils/autoreload.py", line 77, in raise_last_exception
    raise _exception[1]
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/db/models/base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/db/models/base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/db/models/options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/db/utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ec2-user/local/venvs/tellybugvenv/lib64/python3.8/site-packages/django/db/backends/mysql/base.py", line 17, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
Did you install mysqlclient?


Please help.
