### ISSUE TITLE
async write to connection

### ISSUE THREAD

**Issue by jettify** [PyMySQL/mysqlclient-python#55]
I as far as I can see only read from connection is async? What about write operation? For instance we have very slow network, so internal buffer cleared very slowly, connection will be blocked? Is is possible to yield control back to loop in such situation?

**Comment by methane** [comment]
No. libmysqlclient doesn't support async operation.
But you can use thread.  Thread may be better than you think.
https://gist.github.com/methane/2185380

**Comment by jettify** [comment]
Thanks!
