### ISSUE TITLE
Why mysqlclient does not use __slots__?

### ISSUE THREAD

**Issue by MackYoel** [PyMySQL/mysqlclient-python#59]
use
 ```
class Foo:
    __slots__ = ('this', 'that', 'etc')
```
 helps to reduce memory consumption and increases performance, so, Why dont use it?

**Comment by methane** [comment]
It good for massively allocated small objects.
But there are no such objects in this project.

FYI, PyMySQL use the technique (https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L213-L218) since PyMySQL parses MySQL protocol in Python.
