### ISSUE TITLE
Why does not work delimiter statement in query?

### ISSUE THREAD

**Issue by MackYoel** [PyMySQL/mysqlclient-python#64]
I just want to create a stored procedure through of MySQLdb, but I get an Syntaxerror when I try it.
I tried with
<pre>
cursor.execute("DELIMITER //")
</pre>
and the same error occurs.
May be a stupid  question, but, can someone explain why this happens?

<pre>
...
...
cursor.execute("""
    DELIMITER //
    CREATE PROCEDURE test()
    BEGIN
        SELECT 1 FROM DUAL;
    END//
    DELIMITER ;
""")
</pre>

**Comment by methane** [comment]
Since it is a feature of mysql cli.
It's not a SQL nor server feature.

**Comment by MackYoel** [comment]
and how management tools work? i.e. workbench, SQLdeveloper. etc

**Comment by methane** [comment]
I don't know. I haven't used it.

What is your problem? Have you tried this?
```
cur.execute("""CREATE PROCEDURE test()
    BEGIN
         SELECT 1 FROM DUAL;
    END""")
```

**Comment by MackYoel** [comment]
I've not tried without delimiter statement, but what you say it works. 
I guess to redefine delimiter is not necessary when a query is executed like a string.
I've tried creating a script that execute a .sql file, just for dont use a management tool.
Thank you for your answers. I'm sorry for my poor english

**Comment by methane** [comment]
mysql client implements original commands including `help` and `delimiter`.
(ref: https://github.com/mysql/mysql-server/blob/5.7/client/mysql.cc#L4656)

I suppose tools such as MySQL workbench executes mysql cli tool to run .sql scripts.

BTW, don't post a question to Gtihub issue.  OSS product maintainer is not your servant.
Why should I research about function I don't use?

Stackoverflow is better place to ask a question.
