### ISSUE TITLE
Mysqlclient stopped working when Mysql was upgraded to 5.7.9

### ISSUE THREAD

**Issue by MackYoel** [PyMySQL/mysqlclient-python#66]
Maybe this can not be considered a issue, sorry about it

Mysqlclient worked with Mysql Server 5.5 in Ubuntu 14.04, but recently I upgraded to Mysql Community server 5.7.9 and now when I try import it I get:
<pre>
ImportError: libmysqlclient.so.18: cannot open shared object file: No such file or directory
</pre>
Well, after the upgrade, libmysqclient.so.20 exists rather than libmysqclient.so.18 so I tried to modify LD_LIBRARY_PATH to add the new path to libmysqclient.so.20 i.e. [http://stackoverflow.com/questions/511011/how-can-i-tell-python-which-version-of-libmysqlclient-so-to-use](http://stackoverflow.com/questions/511011/how-can-i-tell-python-which-version-of-libmysqlclient-so-to-use)

The problem persists with the same message, so I tried to reinstall mysqlclient from source code and I get the following:
<pre>
running install
running bdist_egg
running egg_info
writing mysqlclient.egg-info/PKG-INFO
writing top-level names to mysqlclient.egg-info/top_level.txt
writing dependency_links to mysqlclient.egg-info/dependency_links.txt
reading manifest file 'mysqlclient.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'mysqlclient.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying MySQLdb/release.py -> build/lib.linux-x86_64-3.4/MySQLdb
running build_ext
building '_mysql' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Dversion_info=(1,3,7,'final',1) -D__version__=1.3.7 -I/usr/include/mysql -I/usr/include/python3.4m -I/home/yoelzalas/tornado/include/python3.4m -c _mysql.c -o build/temp.linux-x86_64-3.4/_mysql.o -fabi-version=2 -fno-omit-frame-pointer
In file included from /usr/include/mysql/mysql.h:64:0,
                 from _mysql.c:30:
/usr/include/mysql/mysql/client_plugin.h:97:3: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   MYSQL_CLIENT_PLUGIN_HEADER
   ^
In file included from /usr/include/mysql/mysql.h:64:0,
                 from _mysql.c:30:
/usr/include/mysql/mysql/client_plugin.h:107:3: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   MYSQL_CLIENT_PLUGIN_HEADER
   ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/_mysql.o -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -ldl -o build/lib.linux-x86_64-3.4/_mysql.cpython-34m.so
/usr/bin/ld: no se puede encontrar -lz
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
</pre>
Is this a incompatibility of mysql version?

**Comment by methane** [comment]
```
/usr/bin/ld: no se puede encontrar -lz
```

Have you installed zlib1g-dev package?

**Comment by MackYoel** [comment]
I guess during the mysql upgrade it was deleting some libraries. After that sudo apt-get install zlib1g-dev the installing works but with two warnings:

<pre>
running install
running bdist_egg
running egg_info
writing dependency_links to mysqlclient.egg-info/dependency_links.txt
writing mysqlclient.egg-info/PKG-INFO
writing top-level names to mysqlclient.egg-info/top_level.txt
reading manifest file 'mysqlclient.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'mysqlclient.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying MySQLdb/release.py -> build/lib.linux-x86_64-3.4/MySQLdb
running build_ext
building '_mysql' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -Dversion_info=(1,3,7,'final',1) -D__version__=1.3.7 -I/usr/include/mysql -I/usr/include/python3.4m -I/home/yoelzalas/tornado/include/python3.4m -c _mysql.c -o build/temp.linux-x86_64-3.4/_mysql.o -fabi-version=2 -fno-omit-frame-pointer
In file included from /usr/include/mysql/mysql.h:64:0,
                 from _mysql.c:30:
/usr/include/mysql/mysql/client_plugin.h:97:3: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   MYSQL_CLIENT_PLUGIN_HEADER
   ^
In file included from /usr/include/mysql/mysql.h:64:0,
                 from _mysql.c:30:
/usr/include/mysql/mysql/client_plugin.h:107:3: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
   MYSQL_CLIENT_PLUGIN_HEADER
   ^
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/_mysql.o -L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -ldl -o build/lib.linux-x86_64-3.4/_mysql.cpython-34m.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.4/_mysql.cpython-34m.so -> build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.4/_mysql_exceptions.py -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/MySQLdb
copying build/lib.linux-x86_64-3.4/MySQLdb/converters.py -> build/bdist.linux-x86_64/egg/MySQLdb
copying build/lib.linux-x86_64-3.4/MySQLdb/release.py -> build/bdist.linux-x86_64/egg/MySQLdb
copying build/lib.linux-x86_64-3.4/MySQLdb/connections.py -> build/bdist.linux-x86_64/egg/MySQLdb
copying build/lib.linux-x86_64-3.4/MySQLdb/compat.py -> build/bdist.linux-x86_64/egg/MySQLdb
copying build/lib.linux-x86_64-3.4/MySQLdb/cursors.py -> build/bdist.linux-x86_64/egg/MySQLdb
creating build/bdist.linux-x86_64/egg/MySQLdb/constants
copying build/lib.linux-x86_64-3.4/MySQLdb/constants/ER.py -> build/bdist.linux-x86_64/egg/MySQLdb/constants
copying build/lib.linux-x86_64-3.4/MySQLdb/constants/REFRESH.py -> build/bdist.linux-x86_64/egg/MySQLdb/constants
copying build/lib.linux-x86_64-3.4/MySQLdb/constants/FIELD_TYPE.py -> build/bdist.linux-x86_64/egg/MySQLdb/constants
copying build/lib.linux-x86_64-3.4/MySQLdb/constants/FLAG.py -> build/bdist.linux-x86_64/egg/MySQLdb/constants
copying build/lib.linux-x86_64-3.4/MySQLdb/constants/CR.py -> build/bdist.linux-x86_64/egg/MySQLdb/constants
copying build/lib.linux-x86_64-3.4/MySQLdb/constants/CLIENT.py -> build/bdist.linux-x86_64/egg/MySQLdb/constants
copying build/lib.linux-x86_64-3.4/MySQLdb/constants/__init__.py -> build/bdist.linux-x86_64/egg/MySQLdb/constants
copying build/lib.linux-x86_64-3.4/MySQLdb/times.py -> build/bdist.linux-x86_64/egg/MySQLdb
copying build/lib.linux-x86_64-3.4/MySQLdb/__init__.py -> build/bdist.linux-x86_64/egg/MySQLdb
byte-compiling build/bdist.linux-x86_64/egg/_mysql_exceptions.py to _mysql_exceptions.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/MySQLdb/converters.py to converters.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/MySQLdb/release.py to release.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/MySQLdb/connections.py to connections.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/MySQLdb/compat.py to compat.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/MySQLdb/cursors.py to cursors.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/MySQLdb/constants/ER.py to ER.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/MySQLdb/constants/REFRESH.py to REFRESH.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/MySQLdb/constants/FIELD_TYPE.py to FIELD_TYPE.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/MySQLdb/constants/FLAG.py to FLAG.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/MySQLdb/constants/CR.py to CR.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/MySQLdb/constants/CLIENT.py to CLIENT.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/MySQLdb/constants/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/MySQLdb/times.py to times.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/MySQLdb/__init__.py to __init__.cpython-34.pyc
creating stub loader for _mysql.cpython-34m.so
byte-compiling build/bdist.linux-x86_64/egg/_mysql.py to _mysql.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying mysqlclient.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mysqlclient.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mysqlclient.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying mysqlclient.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__._mysql.cpython-34: module references __file__
creating dist
creating 'dist/mysqlclient-1.3.7-py3.4-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing mysqlclient-1.3.7-py3.4-linux-x86_64.egg
creating /home/yoelzalas/tornado/lib/python3.4/site-packages/mysqlclient-1.3.7-py3.4-linux-x86_64.egg
Extracting mysqlclient-1.3.7-py3.4-linux-x86_64.egg to /home/yoelzalas/tornado/lib/python3.4/site-packages
Adding mysqlclient 1.3.7 to easy-install.pth file

Installed /home/yoelzalas/tornado/lib/python3.4/site-packages/mysqlclient-1.3.7-py3.4-linux-x86_64.egg
Processing dependencies for mysqlclient==1.3.7
Finished processing dependencies for mysqlclient==1.3.7
</pre>

However, import and connection works.
I feel I am indebted to the repository, thank you for your excellent work as maintainer
