### ISSUE TITLE
Are there any license issues to include libmysqlclient-dev or mysql-devel directly?

### ISSUE THREAD

**Issue by est** [PyMySQL/mysqlclient-python#67]
Hi,

After some tired hours of installing mysql driver, an Idea pop into my head, is it possible to pip install mysqlcient-python without  root to install libmysqlclient-dev or mysql-devel system package?

Can't we just include these libs into our distribution so it's compile and go, without any dependencies?

**Comment by methane** [comment]
Building MySQL Connector/C (aka, libmysqlclient) is harder than installing it from binary distributions.
You can install libmysqlclient from http://dev.mysql.com/downloads/connector/c/

**Comment by est** [comment]
@methane Is it possible to ship all required binary deps along with this package? Like in wheel format? A single pip-install to work on all distros.

**Comment by methane** [comment]
It might be very hard.  I don't know it's possible or not.

**Comment by est** [comment]
So I investigated and  read [this](http://python-packaging-user-guide.readthedocs.org/en/latest/distributing/#platform-wheels)

> PyPI currently only allows uploads of platform wheels for Windows and OS X, **NOT linux. **

This is sad.
