### ISSUE TITLE
Warning handling broken with multi-statements

### ISSUE THREAD

**Issue by adamchainz** [PyMySQL/mysqlclient-python#70]
If you use `connection.set_server_option(MYSQL_OPTION_MULTI_STATEMENTS_ON)` and then send a pair of queries which both cause warnings, MySQLdb breaks when checking for the warnings.

```
In [1]: import MySQLdb

In [2]: conn = MySQLdb.connect(db='test')

In [3]: conn.set_server_option(0)  # multi statements on
Out[3]: 0

In [4]: cur = conn.cursor()

In [5]: cur.execute("drop table if exists atest; drop table if exists atest;")
---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
<ipython-input-5-62f3396e70c7> in <module>()
----> 1 cur.execute("drop table if exists atest; drop table if exists atest;")

/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.pyc in execute(self, query, args)
    174             self.errorhandler(self, exc, value)
    175         self._executed = query
--> 176         if not self._defer_warnings: self._warning_check()
    177         return r
    178 

/usr/local/lib/python2.7/site-packages/MySQLdb/cursors.pyc in _warning_check(self)
     83         from warnings import warn
     84         if self._warnings:
---> 85             warnings = self._get_db().show_warnings()
     86             if warnings:
     87                 # This is done in two loops in case

/usr/local/lib/python2.7/site-packages/MySQLdb/connections.pyc in show_warnings(self)
    315         is an earlier version, an empty sequence is returned."""
    316         if self._server_version < (4,1): return ()
--> 317         self.query("SHOW WARNINGS")
    318         r = self.store_result()
    319         warnings = r.fetch_row(0)

ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
```

**Comment by adamchainz** [comment]
Okay my bad, I've read the manual more thoroughly : http://dev.mysql.com/doc/refman/5.7/en/mysql-set-server-option.html .

First, it's not required to enable multiple statements afaict, since MySQLdb always turns on `CLIENT_MULTI_STATEMENTS`.

Secondly, it requires more than just setting the server option to get right in the MySQL C library - one needs to always loop `mysql_next_result` so it's not really the same.

**Comment by everilae** [comment]
While the fix works for multi statement queries that return result sets, it resurfaces easily with sequential DDL statements:

    In [13]: # Using the `conn` from the original example

    In [14]: cur.execute("""DROP TABLE IF EXISTS blah;
        ...: 
        ...: CREATE TABLE blah AS
        ...: SELECT * 
        ...: FROM blahblah2;
        ...: """)
    ---------------------------------------------------------------------------
    ProgrammingError                          Traceback (most recent call last)
    <ipython-input-14-7c57f6fd8a0f> in <module>()
          4 SELECT *
          5 FROM blahblah2;
    ----> 6 """)
    
    ~/SO/lib/python3.6/site-packages/MySQLdb/cursors.py in execute(self, query, args)
        251         self._executed = query
        252         if not self._defer_warnings:
    --> 253             self._warning_check()
        254         return res
        255 
    
    ~/SO/lib/python3.6/site-packages/MySQLdb/cursors.py in _warning_check(self)
        146                 return
        147 
    --> 148             warnings = db.show_warnings()
        149             if warnings:
        150                 # This is done in two loops in case
    
    ~/SO/lib/python3.6/site-packages/MySQLdb/connections.py in show_warnings(self)
        379         is an earlier version, an empty sequence is returned."""
        380         if self._server_version < (4,1): return ()
    --> 381         self.query("SHOW WARNINGS")
        382         r = self.store_result()
        383         warnings = r.fetch_row(0)
    
    ~/SO/lib/python3.6/site-packages/MySQLdb/connections.py in query(self, query)
        275             self.read_query_result()
        276         else:
    --> 277             _mysql.connection.query(self, query)
        278 
        279     def __enter__(self):
    
    ProgrammingError: (2014, "Commands out of sync; you can't run this command now")
    
It's easy to prove that it is the result set handling, since adding for example a dummy `SELECT 1` in between the DDL statements makes the 2014 go away (and the real error is shown).
