### ISSUE TITLE
mysqlclient and _mysql mismatch 

### ISSUE THREAD

**Issue by abelgvidal** [PyMySQL/mysqlclient-python#73]
Upgrading debian broke my mysqlclient in two apps (Flask and Django). It was working like a charm before.

    ImportError: this is MySQLdb version (1, 3, 7, 'final', 1), but _mysql is version (1, 2, 3, 'final', 0)`

I have tried installing from repo but still does not work. 

How can I install mysqlclient for matching this _mysql version?

    lsb_release -a
    No LSB modules are available.
    Distributor ID:	Debian 
    Description:	Debian GNU/Linux 8.3 (jessie)
    Release:	8.3
    Codename:	jessie

    mysql  Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (x86_64) using readline 6.3

**Comment by methane** [comment]
Do you use virtualenv?
It's best way to separate your app's environment from system Python.
