### ISSUE TITLE
Support MySQL 5.7 on OS X

### ISSUE THREAD

**Issue by billmccord** [PyMySQL/mysqlclient-python#79]
Installing this package seems to hard-code a reference to libmysqlclient.18.dylib in the _mysql.so, but MySQL 5.7 uses libmysqlclient.20.dylib. If I use the MySQL-python package it correctly resolves to libmysqlclient.20.dylib so I'm using that as a workaround for now.

**Comment by methane** [comment]
mysqlclient-python doesn't hard code any library version or library path.
It uses `mysql_config` from PATH.  Execute mysql_config to check your environment.  For example, in my environment:

```
$ mysql_config 
Usage: /usr/bin/mysql_config [OPTIONS]
Options:
        --cflags         [-I/usr/include/mysql -fabi-version=2 -fno-omit-frame-pointer]
        --cxxflags       [-I/usr/include/mysql -fabi-version=2 -fno-omit-frame-pointer]
        --include        [-I/usr/include/mysql]
        --libs           [-L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -ldl]
        --libs_r         [-L/usr/lib/x86_64-linux-gnu -lmysqlclient -lpthread -lz -lm -lrt -ldl]
        --plugindir      [/usr/lib/mysql/plugin]
        --socket         [/var/run/mysqld/mysqld.sock]
        --port           [0]
        --version        [5.7.12]
        --libmysqld-libs [-L/usr/lib/x86_64-linux-gnu -lmysqld -lpthread -lz -lm -lrt -lcrypt -ldl -laio -lnuma]
        --variable=VAR   VAR is one of:
                pkgincludedir [/usr/include/mysql]
                pkglibdir     [/usr/lib/x86_64-linux-gnu]
                plugindir     [/usr/lib/mysql/plugin]
```

BTW, I'm not free support for you.
Additionally, reading and writing English is harder than reading Python to me.

Please ask a question like "How can I use mysqlclient-python with MySQL 5.7?" on StackOverflow or ML before filing issue when you don't have any evidence it is issue of this library and you don't want to read Python code.

**Comment by billmccord** [comment]
Whoa! I didn't mean to imply that you were free tech support. I really appreciate you creating this project and was only trying to help report an issue and a workaround for others that might encounter it.

I did go through the code and try to figure out where something might be hardcoded. I couldn't find anything, but I thought it might have been my misunderstanding of how you were reading the configuration. I completely uninstalled MySQL 5.6 from my system, upgraded everything to MySQL 5.7, and when I used mysql_config I only see references to MySQL 5.7:
```
$ mysql_config
Usage: /usr/local/bin/mysql_config [OPTIONS]
Options:
        --cflags         [-I/usr/local/Cellar/mysql/5.7.12/include/mysql -fno-omit-frame-pointer]
        --cxxflags       [-I/usr/local/Cellar/mysql/5.7.12/include/mysql -fno-omit-frame-pointer]
        --include        [-I/usr/local/Cellar/mysql/5.7.12/include/mysql]
        --libs           [-L/usr/local/Cellar/mysql/5.7.12/lib -lmysqlclient -lssl -lcrypto]
        --libs_r         [-L/usr/local/Cellar/mysql/5.7.12/lib -lmysqlclient -lssl -lcrypto]
        --plugindir      [/usr/local/Cellar/mysql/5.7.12/lib/plugin]
        --socket         [/tmp/mysql.sock]
        --port           [0]
        --version        [5.7.12]
        --libmysqld-libs [-L/usr/local/Cellar/mysql/5.7.12/lib -lmysqld -lssl -lcrypto]
        --variable=VAR   VAR is one of:
                pkgincludedir [/usr/local/Cellar/mysql/5.7.12/include/mysql]
                pkglibdir     [/usr/local/Cellar/mysql/5.7.12/lib]
                plugindir     [/usr/local/Cellar/mysql/5.7.12/lib/plugin]
```

And if I check the lib folder:
```
$ ls -al /usr/local/Cellar/mysql/5.7.12/lib
total 83984
drwxr-xr-x   9 bill  admin       306 Mar 29 02:20 .
drwxr-xr-x  13 bill  admin       442 May  9 14:30 ..
-r--r--r--   1 bill  admin   3781088 May  9 14:30 libmysqlclient.20.dylib
-r--r--r--   1 bill  admin   4284984 Mar 29 02:20 libmysqlclient.a
lrwxr-xr-x   1 bill  admin        23 Mar 29 02:20 libmysqlclient.dylib -> libmysqlclient.20.dylib
-r--r--r--   1 bill  admin  34909216 Mar 29 02:20 libmysqld.a
-r--r--r--   1 bill  admin      9608 Mar 29 02:20 libmysqlservices.a
drwxr-xr-x   3 bill  admin       102 May  9 14:30 pkgconfig
drwxr-xr-x  45 bill  admin      1530 Mar 29 02:20 plugin
```

Since the [MySQLdb1](https://github.com/farcepest/MySQLdb1) project that this is forked from works fine, I figured it was probably a regression so I should report it.

Sorry for the misunderstanding!

**Comment by methane** [comment]
Doesn't pip cache wheel built with old MySQL?

Try this:
```
$ find  ~/.cache/pip/wheels/ | grep mysql
```

If you found whl, remove it and retry pip install.

**Comment by billmccord** [comment]
Yes, you are correct! I didn't realize that the cached wheel would affect the configuration since the _mysql.so was removed when I uninstalled. That fixed it, thank you!
