### ISSUE TITLE
Add "_binary" prefix when converting binary data

### ISSUE THREAD

**Issue by mmsub** [PyMySQL/mysqlclient-python#81]
Since 5.6.27, mysql server produces a warning if string literals cannot
be interpreted in a given character set (See bug  #20238729 at MySQL)
It seems like the "_binary" prefix is the best way to prevent MySQL server from treating a binary data as utf-8 (or other connection charset) characters.
Already done at [PyMySQL] (https://github.com/PyMySQL/PyMySQL/commit/c139119e65168237fb0a061007e8b0b5b96859a2)

**Comment by vtermanis** [comment]
This is in progress - see #106

**Comment by methane** [comment]
#106 is merged
