### ISSUE TITLE
Error pip install MySQL-python  [ i am using Python 3.5 in windows 10 ]

### ISSUE THREAD

**Issue by algobasket** [PyMySQL/mysqlclient-python#86]
Error message : 

(myenv) E:\py-test>pip install MySQL-python
Collecting MySQL-python
  Using cached MySQL-python-1.2.5.zip
Building wheels for collected packages: MySQL-python
  Running setup.py bdist_wheel for MySQL-python ... error
  Complete output from command e:\py-test\myenv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ALGOBA~1\\AppData\\Local\\Temp\\pip-build-i0p6rlub\\MySQL-python\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d C:\Users\ALGOBA~1\AppData\Local\Temp\tmp7hy7_45apip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.5
  copying _mysql_exceptions.py -> build\lib.win32-3.5
  creating build\lib.win32-3.5\MySQLdb
  copying MySQLdb\__init__.py -> build\lib.win32-3.5\MySQLdb
  copying MySQLdb\converters.py -> build\lib.win32-3.5\MySQLdb
  copying MySQLdb\connections.py -> build\lib.win32-3.5\MySQLdb
  copying MySQLdb\cursors.py -> build\lib.win32-3.5\MySQLdb
  copying MySQLdb\release.py -> build\lib.win32-3.5\MySQLdb
  copying MySQLdb\times.py -> build\lib.win32-3.5\MySQLdb
  creating build\lib.win32-3.5\MySQLdb\constants
  copying MySQLdb\constants\__init__.py -> build\lib.win32-3.5\MySQLdb\constants
  copying MySQLdb\constants\CR.py -> build\lib.win32-3.5\MySQLdb\constants
  copying MySQLdb\constants\FIELD_TYPE.py -> build\lib.win32-3.5\MySQLdb\constants
  copying MySQLdb\constants\ER.py -> build\lib.win32-3.5\MySQLdb\constants
  copying MySQLdb\constants\FLAG.py -> build\lib.win32-3.5\MySQLdb\constants
  copying MySQLdb\constants\REFRESH.py -> build\lib.win32-3.5\MySQLdb\constants
  copying MySQLdb\constants\CLIENT.py -> build\lib.win32-3.5\MySQLdb\constants
  running build_ext
  building '_mysql' extension
  error: Unable to find vcvarsall.bat

  ----------------------------------------
  Failed building wheel for MySQL-python
  Running setup.py clean for MySQL-python
Failed to build MySQL-python
Installing collected packages: MySQL-python
  Running setup.py install for MySQL-python ... error
    Complete output from command e:\py-test\myenv\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ALGOBA~1\\AppData\\Local\\Temp\\pip-build-i0p6rlub\\MySQL-python\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\ALGOBA~1\AppData\Local\Temp\pip-xires3pm-record\install-record.txt --single-version-externally-managed --compile --install-headers e:\py-test\myenv\include\site\python3.5\MySQL-python:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.5
    copying _mysql_exceptions.py -> build\lib.win32-3.5
    creating build\lib.win32-3.5\MySQLdb
    copying MySQLdb\__init__.py -> build\lib.win32-3.5\MySQLdb
    copying MySQLdb\converters.py -> build\lib.win32-3.5\MySQLdb
    copying MySQLdb\connections.py -> build\lib.win32-3.5\MySQLdb
    copying MySQLdb\cursors.py -> build\lib.win32-3.5\MySQLdb
    copying MySQLdb\release.py -> build\lib.win32-3.5\MySQLdb
    copying MySQLdb\times.py -> build\lib.win32-3.5\MySQLdb
    creating build\lib.win32-3.5\MySQLdb\constants
    copying MySQLdb\constants\__init__.py -> build\lib.win32-3.5\MySQLdb\constants
    copying MySQLdb\constants\CR.py -> build\lib.win32-3.5\MySQLdb\constants
    copying MySQLdb\constants\FIELD_TYPE.py -> build\lib.win32-3.5\MySQLdb\constants
    copying MySQLdb\constants\ER.py -> build\lib.win32-3.5\MySQLdb\constants
    copying MySQLdb\constants\FLAG.py -> build\lib.win32-3.5\MySQLdb\constants
    copying MySQLdb\constants\REFRESH.py -> build\lib.win32-3.5\MySQLdb\constants
    copying MySQLdb\constants\CLIENT.py -> build\lib.win32-3.5\MySQLdb\constants
    running build_ext
    building '_mysql' extension
    error: Unable to find vcvarsall.bat

**Comment by methane** [comment]
Have you searched duplicate issue is reported?
See #54

**Comment by algobasket** [comment]
how to resolve it ?

**Comment by methane** [comment]
Oracle releases MySQL Connector/C for VC14 (Visual Studio 2015).

**Comment by mniknezhad** [comment]
conda install -c anaconda mysql-connector-python
conda install -c bioconda mysqlclient

**Comment by donato95** [comment]
not resolved yet?!
