### ISSUE TITLE
'surrogates not allowed' error on stored procedure call for unicode argument

### ISSUE THREAD

**Issue by jinto** [PyMySQL/mysqlclient-python#90]
On python 3.5.1, mysqlclient 1.3.7

cursor.callproc() with unicode string argument generates error below 
`'utf-8' codec can't encode character '\udceb' in position 39: surrogates not allowed`

The code works if I change  below code

```
def literal(self, o): 
    s = self.escape(o, self.encoders)
    if not PY2 and isinstance(s, bytes):
        return s.decode('ascii', 'surrogateescape')
    return s
```
to

```
def literal(self, o): 
    s = self.escape(o, self.encoders)
    if not PY2 and isinstance(s, bytes):
        return s.decode('utf8', 'surrogateescape')
    return s
```
changes :  'ascii' to 'utf8' 
ps. tested string was korean string, "제권".

**Comment by jinto** [comment]
I think problem was not in literal(), but in the callproc() after calling literal().

**Comment by NitBrok** [comment]
RuntimeWarning: Surrogate character '\ude46' will be ignored. You might be using a narrow Python build

can u tell me about above error??

**Comment by jinto** [comment]
It was fixed by https://github.com/PyMySQL/mysqlclient-python/pull/91 .
I cannot remember the details. I think this is closed 3 years ago.
If you are interested in the issue you can digg into the pr above.
