### ISSUE TITLE
_mysql.free_result() not necessary?

### ISSUE THREAD

**Issue by imdaveho** [PyMySQL/mysqlclient-python#94]
http://dev.mysql.com/doc/refman/5.7/en/mysql-free-result.html

It suggests that once you're finished using the result set, it is recommended to free it up. Is there a reason it is not a method for _mysql? I tried using `with conn.store_result() as result` such that it runs the destructor on the result object, but it threw an AttributeError complaining there was no \__exit\___
I've been meaning to understand whether or not I can reuse the connection (ie. conn.query('something'), get results, query again, get results, query again) without opening/closing a new connection every time. I've been getting some MySQL read locks (just using SELECT statements) from the 3-6 threads I'm using to access the DB concurrently. I'm wondering if it has anything to do with not releasing the memory after each store_result() and starting another query...

If this is explained in PEP or is not relevant to the issue tracker, please let me know and close this thread. Thanks.

**Comment by methane** [comment]
If you worried about such a low level C API, why don't you read C source?
https://github.com/PyMySQL/mysqlclient-python/blob/master/_mysql.c#L2314

**Comment by imdaveho** [comment]
@methane I have read the C source. And as I have no real experience with C, I was hoping to get some context in understanding if the behavior was left out on purpose for a reason. Sure, I can modify the source and implement it my self's hopefully without any errors, but 1/ I'm not comfortable modifying C code, 2/ if there is a good reason it was NOT implemented or the behavior exists, I'd like to know.

I may not have been clear in my above question, thanks for being patient. Cheers.

**Comment by methane** [comment]
If you can't find answer of your question, you shouldn't use low level API.
Just use cursor, the high level API.
You can reuse connection after closing cursor.
