### ISSUE TITLE
Wheel packages for non-Win and for CPython 3.4/3.5 on Win

### ISSUE THREAD

**Issue by tnir** [PyMySQL/mysqlclient-python#97]
[PyMySQL](https://pypi.python.org/pypi/PyMySQL) has provided their wheel package as reported in [Python Wheels](http://pythonwheels.com/), [mysqlclient-python](https://pypi.python.org/pypi/mysqlclient) has only wheel packages for CPython 2.7 on Win 32/64 to provide.

Do you have plan to package wheels for non-Win (Mac only? No Linux?) and for Python 3?

**Comment by methane** [comment]
See #54 for Python 3.5 on Windows.

Platform other than Windows, I don't want to maintain binary distribution containing OpenSSL.

**Comment by tnir** [comment]
@methane ok thx.
